### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#10]
**Motive**
The plugin may be used in other contexts that en-US and en-GB. Currently all language maps use these languages.

**Result**
For activity (e.g. course) names and descriptions the best we can assume is that these are in the default language of the Moodle site. This is a config setting found at /moodle/admin/settings.php?section=langsettings which should be accessible programmatically. 

The verb display should ideally also be in the default language of the Moodle site and make use the language files rather than being hard coded. It should fall back to some default language or use all available languages if the default language isn't found in the language pack. 

**Additional information**
Note that Moodle stores languages differently from the ISO standard. See https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/locallib.php#L525

**Comment by ryasmi** [comment]
This is definitely something that should be worked on before this plugin gets to 1.0.0

**Comment by jlowe64** [comment]
Yeah, in the original version of my plugin I wanted to use the Moodle localisation system to do this, so it's worth revisiting. Moodle is different in the way it does localisation, but it's pretty easy to understand and works fairly well (minus a couple of oddities).
