### ISSUE TITLE
Changing last version in moodle website

### ISSUE THREAD

**Issue by bseclier** [davidpesce/moodle-logstore_xapi#106]
Hi,
Thanks for the last work with these new releases.
I can see on the moodle website (https://moodle.org/plugins/pluginversions.php?plugin=logstore_xapi) that the current version is still 1.0.0. Is there any reason for that ?
Can I safely upgrade the plugin in my moodle ?

Thanks again for you work,
Cheers,

**Comment by davidpesce** [comment]
We are working on getting access to the Moodle plugin listing to make the update there. The version currently on GitHub is safe to update to (and encouraged). One caveat, we are releasing a new build in the next day or two that has a significant upgrade. If you can hold out, it'll be worth it. 

Additionally, the 4 repositories that make up the plugin will be combined into one. I'm hoping to make that available in the next two weeks. Thanks for your interest; stay tuned!

**Comment by bseclier** [comment]
Thank you for the tip, I'll wait until this new release then !

**Comment by jlowe64** [comment]
@davidpesce if @ryansmith94 agrees, I can add you as collaborator on the Moodle page, so you can take over releases as you continue development.

**Comment by ryasmi** [comment]
Definitely agreed, I tried contacting you to get that changed a couple of
weeks ago Jerrett

**Comment by jlowe64** [comment]
@ryansmith94 that's probably because I left my job around 2 weeks ago and wasn't answering my Charitylearning email! @davidpesce what is your moodle community id?

**Comment by davidpesce** [comment]
@jlowe64 it should be 'davidpesce'

**Comment by jlowe64** [comment]
Both of you should now be maintainers, so you should be able to make releases!

**Comment by davidpesce** [comment]
Awesome! Thanks, @jlowe64 !! Hope to see you back on here some day!

**Comment by davidpesce** [comment]
Latest version is posted on Moodle plugin site. Closing issue.
