### ISSUE TITLE
Feature: Include Learning Plan and Competency Events

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-logstore_xapi#113]
As of Moodle 3.1 the concept of learning plans and competencies has been added: 
- https://docs.moodle.org/33/en/Learning_plans
- https://docs.moodle.org/33/en/Competencies

The following events seem like a good start to adding this functionality:
- \core\event\competency_plan_viewed
- \core\event\competency_plan_review_started
- \core\event\competency_plan_completed
- \core\event\competency_viewed
- \core\event\competency_framework_viewed

**Comment by nadavkav** [comment]
There are also some potentially interesting user competency events that should be implemented too:
https://github.com/moodle/moodle/tree/master/lib/classes/event
competency_user_competency_*

**Comment by davidpesce** [comment]
Cleaning up old issues.
