### ISSUE TITLE
Enhancement: Use Moodle DEBUG_DEVELOPER for debug 

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-logstore_xapi#114]
Should we start using Moodle's developer debug level for troubleshooting? Rather than the log to text file.

**Comment by ryasmi** [comment]
Probably a good idea.

**Comment by davidpesce** [comment]
Issue #89 has additional details on this.

**Comment by ryasmi** [comment]
Added for V3 PR https://github.com/xAPI-vle/moodle-logstore_xapi/pull/172/commits/0f562bb09135c973593b6bbab5484987da762b9f

**Comment by ryasmi** [comment]
Notes to self:
- https://github.com/moodle/moodle/blob/4b82c15cdbb8a4b71edea7983441832e6725da27/lib/weblib.php#L3103
- https://docs.moodle.org/31/en/Debugging

**Comment by ryasmi** [comment]
Think this done now @davidpesce. Please reopen if that's not the case.
