### ISSUE TITLE
Plugin Architecture

### ISSUE THREAD

**Issue by ryasmi** [davidpesce/moodle-logstore_xapi#115]
Just wanted to make a thread for discussing future architectural changes to the plugin now that's all in one Github repository (awesome work @davidpesce!).

**Comment by ryasmi** [comment]
My two cents.

Essentially this is an ETL tool. Data is extracted from Moodle, transformed from Moodle data to xAPI data, and loaded into an LRS. Hence, I firstly think we should rename the parts to reflect this (Extractor instead of Expander, Transformer instead of Translator, and Loader instead of Emitter). This would cut out some logic in the translator, because we'd no longer go from Moodle data to recipe data to xAPI data, we'd simply go from extracted Moodle data to data that can be loaded in the LRS. However, cutting out this logic may not be a good idea, in which case, I'd ensure that the Expander outputs recipes made out of extracted Moodle data (not sure if that's a good idea, something to discuss).

Each of these parts should implement an interface with a single function that receives an array of events as input and produces a new array of events as output. Technically, I'd rather that was implemented as a single function not a class with one function, my preference would be to avoid classes where possible (reserving their usage for data structures rather than functionality). For example, the Extractor might look something like the Extractor below.

```php
interface ExtractorRepo {
  // Repo methods.
}

class ExtractorConfig {
  public $repo; // ExtractorRepo
  // Other configuration properties.
}

$extractor = function (ExtractorConfig $config) {
  return function (array $events) use ($config) {
    // Extract $events so that they contain all the data required to create xAPI statements.
  };
};

$extractorConfig = new ExtractorConfig();
$extractorConfig->repo = $extractorRepo;
$events = [];
$etl($extractorConfig)($events);
```

I think these parts would be best combined by a function that takes the 3 parts and an array of events as input, uses the 3 parts, and then returns the array of transformed events after they were loaded. This would allow one set of behaviour driven tests that create the events as they are in the standard log store, and then assert that the correct events are loaded. I hope that makes sense, I've included an example of this in PHP below.

```php
class ETLConfig {
  public $extractor; // Callable
  public $transformer; // Callable
  public $loader; // Callable
  // Other configuration properties.
}

$etl = function (ETLConfig $config) {
  return function (array $events) use ($config) {
    $extractedEvents = $config->extractor($events);
    $translatedEvents = $config->translator($extractedEvents);
    $loadedEvents = $config->loader($translatedEvents);
    return $loadedEvents;
  };
};

$etlConfig = new ETLConfig();
$etlConfig->extractor = $extractor;
$etlConfig->transformer = $transformer;
$etlConfig->loader = $loader;
$stdLogEvents = [];
$etl($etlConfig)($stdLogEvents);
```

Finally, I'd recommend not using classes for events/recipes. Use functions instead, the functions should take one event and return an array of events (potentially empty). Currently the amount of inheritance being used leads to a lot of file hopping. It would probably be easier to understand and result in less file hopping if they were a set of utility functions (i.e. createActivity, createActor) that were used in the events. This is because the entire statement would need to be specified in the function rather than part of it.

```php
// lib/transformer/utils/readUser.php
function readUser(array $inputUser) => {
  return [
    'objectType' => 'Agent',
    'name' => $inputUser['name'],
    'account' => [
      'homePage' => $input['url'],
      'name' => $input['id'],
    ],
  ];
}

// lib/transformer/events/courseView.php
function courseView(TransformerConfig $config, array $inputEvent) => {
  return [[
    'actor' => readUser($inputEvent['user']),
    'verb' => [
      'id' => 'http://id.tincanapi.com/verb/viewed',
      'display' => readVerbDisplay($inputEvent),
    ],
    'object' => readCourse($inputEvent),
    'context' => [
        'platform' => $inputEvent['context_platform'],
        'language' => $inputEvent['context_lang'],
        'contextActivities' => [
            'grouping' => [
                readApp($inputEvent)
            ],
            'category' => [
                readSource($inputEvent)
            ]
        ],
    ],
    'timestamp' => $inputEvent['time'],
  ]];
}
```

**Comment by davidpesce** [comment]
I haven't fully unpacked all of the items in this issue, but agree with the general idea of the architecture. :thumbsup:

**Comment by ryasmi** [comment]
@davidpesce updated the code examples in my comment a little bit.

**Comment by ryasmi** [comment]
It might be useful to have classes for the different data structures in the extractor, for example:

```php
// lib/extractor/models/ExtractedUser.php
class ExtractedUser {
  public name;
  public url;
  public id;
  // ...
}

// lib/extractor/models/ExtractedCourseView.php
class ExtractedCourseView {
  public user;
  // ...
}

// lib/transformer/utils/readUser.php
function readUser(ExtractedUser $inputUser) => {
  return [
    'objectType' => 'Agent',
    'name' => $inputUser->name,
    'account' => [
      'homePage' => $inputUser->url,
      'name' => $inputUser->id,
    ],
  ];
}

// lib/transformer/events/courseView.php
function courseView(TransformerConfig $config, ExtractedCourseView $inputEvent) => {
  return [[
    'actor' => readUser($inputEvent->user),
    'verb' => [
      'id' => 'http://id.tincanapi.com/verb/viewed',
      'display' => readVerbDisplay($inputEvent),
    ],
    'object' => readCourse($inputEvent),
    'context' => [
        'platform' => $inputEvent->platform,
        'language' => $inputEvent->lang,
        'contextActivities' => [
            'grouping' => [
                readApp($inputEvent)
            ],
            'category' => [
                readSource($inputEvent)
            ]
        ],
    ],
    'timestamp' => $inputEvent->time,
  ]];
}
```

**Comment by ryasmi** [comment]
### Step 1
- Create the ETL function I described above that unifies the parts of this plugin.
- Use the ETL function in the plugin and the cron.
- Change the tests to become more behavioural (end-to-end) by only utilising the ETL function in the tests.

### Step 2
- Rename the Expander part to the Extractor and ensure that the Extractor outputs events in the format the current Emitter expects to receive events.
- Remove the Translator part.
- Split the Emitter into the following pieces:
    - Transformer part that creates xAPI statements from events outputted by the Extractor.
    - Loader part that loads the xAPI statements outputted by the Transformer to an LRS.

### Step 3
Move from using classes and inheritance towards functions and composition in order to "shorten the conceptual gap between the static program and the dynamic process" (Dijkstra). Currently it's quite hard to find out what values an event is outputting because of the inheritance chains. Instead we should strive to define the entire event in the file by re-using small functions for parts of the event. This has been tried and tested with success on other ETL projects here at HT2Labs.

**Comment by ryasmi** [comment]
https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v3.0.0
