### ISSUE TITLE
The 'plugin design' doc needs amending as of v2.0.0

### ISSUE THREAD

**Issue by mikemcgowan** [davidpesce/moodle-logstore_xapi#116]
[This one](https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/docs/design.md) probably needs updating to state that the three underlying components in the pipeline are now in the `lib/` directory rather than separate repos.

**Comment by mikemcgowan** [comment]
Also, [this one](https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/docs/developers.md) for developers.

**Comment by davidpesce** [comment]
This is resolved.
