### ISSUE TITLE
No coverage for code in classes/ directory

### ISSUE THREAD

**Issue by mikemcgowan** [davidpesce/moodle-logstore_xapi#118]
While the test coverage for the `lib/` directory is good (90% currently), there's no test coverage at all for the `classes/` directory.

This is particularly important because the `process_events()` method of the `store` class is critical to the successful functioning of the plugin as a whole. Also, the `execute()` method of the `emit_task` class would benefit from some coverage.

**Comment by ryasmi** [comment]
See the thread on architecture #115
