### ISSUE TITLE
Add "source" and "recipe" context activities

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#12]
**Motive**
It may be helpful to know that a statement came from Moodle vs. some other LMS or source. 

**Result**
Add activities to the context like the below. Note that `http://example.com/recipe-for-tracking-lmss` is a placeholder and the recipe should be published with it's own id.  

It might also be worth adding the plugin and it's version as a source. 

```
"context": {
        "contextActivities": {
            "category": [
                {
                    "id": "http://example.com/recipe-for-tracking-lmss",
                    "definition": {
                        "type": "http://id.tincanapi.com/activitytype/recipe"
                    },
                    "objectType": "Activity"
                },
                {
                    "id": "https://docs.moodle.org/29/",
                    "definition": {
                        "name": {
                            "en-US": "Moodle 2.9"
                        },
                        "description": {
                            "en-US": "Moodle is a learning platform designed to provide educators, administrators and learners with a single robust, secure and integrated system to create personalised learning environments."
                        },
                        "type": "http://id.tincanapi.com/activitytype/source"
                    },
                    "objectType": "Activity"
                }
            ]
        }
    },
```

**Additional information**
{{additionalInfo}}

**Comment by ryasmi** [comment]
> It may be helpful to know that a statement came from Moodle vs. some other LMS or source.

I believe that the platform (`context.platform`) is set to "Moodle" on every statement.

> Add activities to the context like the below. Note that http://example.com/recipe-for-tracking-lmss is a placeholder and the recipe should be published with it's own id.

There isn't really recipe as of yet, hence why that isn't included already.

> It might also be worth adding the plugin and it's version as a source.

I agree that might be useful, but why do you think it would be useful?

**Comment by garemoko** [comment]
context.platform does say Moodle and that is probably sufficient. In a lot of cases though, Tin Can tracking is done client side and platform is used (if used) to convey browser information. I'm encouraging others including authoring tools to include the source context activity; it's not widely in use yet but I hope it will become so. 

Part of this issue is an encouragement to write the recipe :-)

It's useful to know plugin and version in case the statements sent vary between versions. Tools consuming the data might handle data from different versions of the plugin differently.

**Comment by ryasmi** [comment]
Hmmm... I think the reverse could probably be encouraged too.

Plugin and version of the plugin can go in the context extensions.

**Comment by ryasmi** [comment]
Work in progress to be edited Monday.

``` json
"context": {
        "contextActivities": {
            "category": [
                {
                    "id": "http://lrs.learninglocker.net/define/recipe/assignment_graded",
                    "definition": {
                        "type": "http://id.tincanapi.com/activitytype/recipe"
                    },
                    "objectType": "Activity"
                }
            ]
        },
        "extensions": {
          "http://lrs.learninglocker.net/define/extension/moodle": "1.9.8+ (Build: 20100512)",
          "http://lrs.learninglocker.net/define/extension/moodle_logstore_xapi": "0.1.0"
        }
    }
```
