### ISSUE TITLE
Statement Templates

### ISSUE THREAD

**Issue by FeLungs** [davidpesce/moodle-logstore_xapi#124]
**Description**
- Find appropriate places within existing xAPI fields for the data that is contained in the extensions.

**Comment by ryasmi** [comment]
Most of the extensions will be removed.

**Comment by FeLungs** [comment]
Why throw away that data?

**Comment by ryasmi** [comment]
Essentially the data that currently exists in the extensions falls into three categories:
1. It's stored elsewhere in the statement already (hence it's duplicated and should be removed).
2. It's not stored elsewhere in the statement, but it's null or not useful, etc (hence remove it).
3. It's not stored elsewhere in the statement, but it's useful (hence we should keep it somehow).

**Comment by FeLungs** [comment]
Gotcha, If you would like any help with 3. I can help refactor the current statement templates,  I would just need event fixture data

**Comment by ryasmi** [comment]
Awesome, I'll let you know, I don't think it'll be something we'll tackle right now as we try to [clean up the code](https://github.com/xAPI-vle/moodle-logstore_xapi/pull/119) and [re-architect some pieces](https://github.com/xAPI-vle/moodle-logstore_xapi/issues/115).

**Comment by FeLungs** [comment]
:+1:
