### ISSUE TITLE
Allow ignoring guest access logs

### ISSUE THREAD

**Issue by fishfree** [davidpesce/moodle-logstore_xapi#126]
There should be a setting to allow ignoring guest access logs, because guest access generates too many meaningless data.

**Comment by garemoko** [comment]
Worth noting as well that the xAPI launch plugin probably breaks for guests, so people using both plugins together with guests are going to have a bad time.

**Comment by davidpesce** [comment]
This is implemented in the current version of the plugin (2.2.2)
