### ISSUE TITLE
Error when validating logstore_xapi

### ISSUE THREAD

**Issue by abalderas** [davidpesce/moodle-logstore_xapi#128]
**Description**
- I'm trying to install logstore_xapi plugin on Moodle 3.3, but I am receving an error when validating (Validating logstore_xapi ... Error). Then the installation is cancelled.

**Version**
- version: 2017061100
- release: 2.0.0
- requires: 2014111000
- maturity: MATURITY_STABLE

**Steps to reproduce the bug**
1. Site administration --> Install plugins --> Install plugin from Moodle plugins directory
2. Go to https://moodle.org/plugins/logstore_xapi
3. Clic on Install now
4. Confirm the installation (in Moodle now) --> Clic on Continue
5. Error:
Install plugins from the Moodle plugins directory
Downloading logstore_xapi ... OK
Validating logstore_xapi ... Error
  [Error] Extracted file not found [{"file":"xapi\/vendor\/bin\/"}] 
Installation aborted due to validation failure

**Expected behaviour**
- log_xapi plugin should be installed because I have proceed as a usually do with other plugins.

**Actual behaviour**
- log_xapi plugin installation is aborted (see error message above).

**Server information**
- MySQL 5.7.14 with Apache/2.4.23 (Win64) PHP/5.6.25.

**Client information**
- OS: Windows 10
- Browser: Google Chrome version 59.0.3071.115 (Build oficial) (64 bits)

**Additional information**
- I try to install it using the zip file, but it does not work either (same error).
- I try also in a docker container with Ubuntu, but again, it does not work (same error).

**Comment by deedey** [comment]
Hi @abalderas,
I have the same problem with the new version of logstore_xapi. 
Note that I continue using version 2016012900 release 1.0.0.

**Comment by ryasmi** [comment]
@davidpesce does this not happen on your Moodle installations? Seems like the files in vendor/bin are missing in the zip

**Comment by davidpesce** [comment]
Odd, I just pulled the zip from github and it has the vendor folder and the (remaining) dependencies. Maybe it's limited to the one posted to Moodle plugins. Let me look.

**Comment by davidpesce** [comment]
Confirmed, the remaining composer dependencies are included in the Moodle plugin listing here: https://moodle.org/plugins/logstore_xapi

**Comment by ryasmi** [comment]
The files in the `vendor/bin` directory are missing though for me when I download the zip from Github. Does the installation work with that zip for you?

**Comment by davidpesce** [comment]
Yikes, yea, you're right. I wonder if removing the dependencies broke the packaging script.

**Comment by ryasmi** [comment]
Possibly, really not sure. @abalderas use v1.0.0 of the plugin for now.

**Comment by deedey** [comment]
I use V-1.0.0 also , @ryansmith94 , and I tried to download and install V 2.0.0 today @davidpesce . vendor/bin repository is always empty and I've the same notification.

**Comment by abalderas** [comment]
Thank you all for your comments.  I installed V.1 and it works perfectly.

**Comment by davidpesce** [comment]
@ryansmith94 I went back to the last version submitting by Jerret and found that it is also missing files in the vendor/bin directory. Then checked the moodle plugin site and downloaded v1. There's not even a bin folder in vendor. Within vendor, there is composer, learninglocker, and rusticisoftware.

**Comment by ryasmi** [comment]
Okay that's strange. Not sure what the issue is, I wonder if it's something to do with the code not passing the Moodle code checker, I think I merged a PR for that since the 2.0.0 release

**Comment by nikidev** [comment]
Hi all ! :)   I had the same problem  but what I decided to do  is just to delete  the **/bin**  folder. After that the validation passed !  I want to mention that  there isn't anything broken. The plugin works.

**Comment by ryasmi** [comment]
Thanks @nikidev that's awesome! @davidpesce perhaps try deleting the vendor directory, reinstalling and then building the zip. If that doesn't resolve the issue we'll have to delete the bin folder in the vendor directory as part of the zip building process.

**Comment by dgcruzing** [comment]
Was getting same problems as above. 
Was using the plugin from moodle.. and haven't bothered to upgrade for a few months. 
Decided to pull the master from here last night and give it a go.
but it hosed something within the moodle database I think .. as validated fine but never got past the "Moodle database upgrading" part.. had to reboot the server as I lost the ability to use admin and also to go down to " /moodle/my/" level.. 
just seemed like for some reason this path was corrupt. 
Had to go into "/admin/tool/log/store" and delete the plugin to get the system back. 
 Running Moodle 3.1.1 (Build: 20160711) on a AWS Bitnami server. 
mysql (5.6.31)

Will have to come back to this as will test on my development server that is running 3.2.2

**Comment by paulraper** [comment]
I could now install the master file, but after installation, I can no longer access my administrator page! Shit. Now what do I do?

**Comment by paulraper** [comment]
Thanks dgcruzing for a most helpful tip. I have managed to get my system back to near normal thanks to your very helpful tips.
Now all that remains is for a stable release of the plugin to be released.

**Comment by paulraper** [comment]
The last version of the plugin that will install, though with the error message described above, and that will not corrupt the Moodle database such that you have no access to your administration level, is version 1.4.0.
All versions of the plugin after this date do not work: so DONOT try to install them, in fact best would be for them to be taken down before they cause others a whole load of headaches.

**Comment by ryasmi** [comment]
Ok just an update. It seems to me that there were probably two issues here.
1. Code checks by Moodle were probably failing because we didn't follow their code guidelines in the sub repos that got merged in here. This was resolved in #119.
2. The silly "xapi/vendor/bin/" folder that's empty in the zip file.

I'm currently working in my own time to create an auto-releasing process using our Travis builds. In doing that I'll ensure the bin folder is removed in the zip file and I'll hopefully that'll resolve the issues here. Unfortunately HT2 cannot allocate any time to fix this right now, so I'm doing it in my own time like I said, I would hope to get this fixed very soon. The auto-releasing process, will also allow me to merge more pull requests to get community contributed bug fixes out the door much sooner 👍

**Comment by ryasmi** [comment]
Hey guys, I got some free time tonight due to a change of plans. It's taken all night, but I've finally got automatic releases to work. It'd be awesome if someone else could try out [version 2.1.2](https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v2.1.2). You can [download the zip file](https://github.com/xAPI-vle/moodle-logstore_xapi/releases/download/v2.1.2/xapi.zip) like usual. Assuming that works I'll upload the zip file to the [Moodle plugins directory](https://moodle.org/plugins/logstore_xapi).

**Comment by ryasmi** [comment]
I'm aware that the release is missing from the version.php file. That does need fixing in the "scripts/generateVersionFile.sh" file

**Comment by ryasmi** [comment]
[v2.1.4](https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v2.1.4) fixes the release string in the version.php file. You can download the xapi.zip file from that link 👍

**Comment by ryasmi** [comment]
Just tried this out and it works for me now, so I'm closing this issue. I've uploaded the zip file to plugins directory too.

**Comment by paulraper** [comment]
@ryansmith94 Thanks for you super input and support. I have just installed and tested release 2.1.5 from the Moodle repository, and it works fine so far. Excellent and thank you again for your help.

**Comment by paulraper** [comment]
That was my Moodle test site: will be installing on the production site later today. Thanks again @ryansmith94 you are amazing. 👍

**Comment by ryasmi** [comment]
No worries @paulraper, you're very welcome 👍 thanks for testing it out and posting your feedback here. I'm glad it's working well for you, I hope the install on your production site goes well today 😄
