### ISSUE TITLE
Quiz "completed" event is not working with any version of Moodle above 3.1.2

### ISSUE THREAD

**Issue by nikidev** [davidpesce/moodle-logstore_xapi#129]
**Description**
- Quiz "completed" event is not working with any version of Moodle above 3.1.2

Hi all ! 

I noticed the following problem. When I complete a quiz in a version of Moodle which is above 3.1.2 (for example  3.1.5, 3.2, 3.3)  the logstore xAPI plugin is not sending a completed statement with a result. I checked  the event list  of the moodle instances but I didn't find any difference. Do you have an idea what might be the problem ? :)

**Comment by garemoko** [comment]
I would guess maybe the Moodle quiz module changed their database structure.

**Comment by nikidev** [comment]
Yes, you are right ! There are some small differences. Some new fields are added.  But I can't find nothing in common with the problem.  I am wondering how should  I proceed to get it to work with newer versions of Moodle.

**Comment by garemoko** [comment]
Tricky one. We either need to have something in the code to detect the Moodle version and change behaviors accordingly, or have branches targeting different Moodle versions.

**Comment by nikidev** [comment]
It's interesting  what is the difference  which  prevents  the event to be triggered. I can't find it.

**Comment by nikidev** [comment]
By the way  in the same context the  enrolment_created event  also does not work.  :)

**Comment by davidpesce** [comment]
Has anyone resolved this one (or made any progress on it)?

**Comment by ryasmi** [comment]
Not that I know of @davidpesce

**Comment by davidpesce** [comment]
Which event was this originally set to trigger off of? I'm only showing the following:

        '\mod_quiz\event\attempt_abandoned' => 'AttemptEvent',
        '\mod_quiz\event\attempt_preview_started' => 'AttemptEvent',
        '\mod_quiz\event\attempt_reviewed' => 'AttemptEvent',
        '\mod_quiz\event\attempt_viewed' => 'AttemptEvent',
        '\mod_quiz\event\course_module_viewed' => 'ModuleEvent',

**Comment by davidpesce** [comment]
@nikidev do you have the list of differences in the quiz table between Moodle 3.1.2 and 3.2?

**Comment by davidpesce** [comment]
I just tried this on a local version of Moodle 3.4.1 and it worked perfectly. 

What's odd is that I have client Moodle instances that this does not work on. And another 3.3.4+ instance that has the quiz completed statement for one particular quiz, but not others.

**Comment by davidpesce** [comment]
I think this is the event we need to capture: \mod_quiz\event\attempt_submitted

**Comment by davidpesce** [comment]
@nikidev it can't be the original one because it's not in the codebase. I think that's a new one. Do you remember the original one?

**Comment by davidpesce** [comment]
@nikidev @ryansmith94 OK, I think I have it figured out. Well, partly. It looks like the \mod_quiz\event\attempt_reviewed (which is mapped to the recipe attempt_completed is what has triggered the quiz completed statement. Guessing that if a site doesn't allow the quiz to be reviewed, then the event is never triggered. 

On my testing, I did a quick quiz as an admin and left review on. After submitting, it immediately dumps me to the review (which triggers the statement send).

I thiiiink we should remove the attempt_reviewed event tracking and create a new attempt_submitted to more accurately track quiz completions. Or map the reviewed statement to a different recipe/verb that more fits what it does.

Thoughts?

**Comment by ryasmi** [comment]
Yeah I think removing the attempt_reviewed and using attempt_submitted sounds like a good idea. May want to also create a new recipe for the attempt_reviewed.

**Comment by nikidev** [comment]
Absolutely !   While I was testing the quiz completion  the emitter was emitting only **attempt_started**  but **attempt_completed**  wasn't working. So, this means that it fails on the reviewing.

**Comment by davidpesce** [comment]
@nikidev can you test PR #157 

It should fix the issue. Make sure you are logged in as a user. If you're in as an admin, you automatically go to attempt_review.

**Comment by davidpesce** [comment]
@garemoko @ryansmith94 @nikidev 
Also worth discussing...

This comes through with the verb "completed". It makes sense to me, but may not be straight-forward to Moodle users (since moodle is using "submitted"). 

Also of note. Reviewed now shows correctly. As an admin I can go in and review an attempt. The xapi statement comes across to the LRS with a verb "reviewed", but within the statement, the userid (of the user who took the quiz) is used instead of something easier to identify. Thoughts? Leave or improve?

The last item is that the quiz "viewed" statements are verbose. If the Moodle quiz questions are separated to individual pages, every page view sends a statement. Then another statement is sent for every time the user answers. Easy enough to filter out, but seems overkill. Thoughts?

**Comment by ryasmi** [comment]
> This comes through with the verb "completed". It makes sense to me, but may not be straight-forward to Moodle users (since moodle is using "submitted").

Probably should change this to submitted if it makes sense for the statement.

> Also of note. Reviewed now shows correctly. As an admin I can go in and review an attempt. The xapi statement comes across to the LRS with a verb "reviewed", but within the statement, the userid (of the user who took the quiz) is used instead of something easier to identify. Thoughts? Leave or improve?

I guess there are two options here. Firstly use the context instructor to contain the user id of the user reviewing the attempt (I think this is preferred as it keeps the actor focus on the learner). Secondly, use the user id of the user reviewing the attempt in the actor and put the learner somewhere else.

> The last item is that the quiz "viewed" statements are verbose. If the Moodle quiz questions are separated to individual pages, every page view sends a statement. Then another statement is sent for every time the user answers. Easy enough to filter out, but seems overkill. Thoughts?

I think we can probably leave this for now. If it becomes a problem we can revisit.

**Comment by garemoko** [comment]
> This comes through with the verb "completed". It makes sense to me, but may not be straight-forward to Moodle users (since moodle is using "submitted").

The terminology used by Moodle is almost irrelevant. The point is to standardize the data so that it can be used alongside data from other quizzing applications. 

>  As an admin I can go in and review an attempt. The xapi statement comes across to the LRS with a verb "reviewed", but within the statement, the userid (of the user who took the quiz) is used instead of something easier to identify.

Should be the user id of the person reviewing. Would make sense to include the learner id somewhere in the statement though. Think carefully about the object and context for this statement; not an easy one to design.

**Comment by davidpesce** [comment]
@garemoko yeah, the actor of the statement is the person reviewing. That's all good. 

In the object, it includes the userid of the person who took the quiz, but nothing more of an identifier.

```
"object": {
      "definition": {
        "extensions": {
          "http://lrs.learninglocker.net/define/extensions/moodle_attempt": {
            "timefinish": "1519248245",
            "userid": "3",
            "sumgrades": "10.00000",
            "currentpage": "4",
            "preview": "0",
            "layout": "1,0,2,0,3,0,4,0,5,0",
            "name": "Attempt 7",
            "uniqueid": "7",
            "timemodifiedoffline": "0",
            "questions": [
```

I want to be careful with sending anything more (especially with the EU privacy law). 

P.S. Don't worry, the activity URLs are on my list. :) Are we still using tincanapi (registry.tincanapi.com) as the main source?

**Comment by garemoko** [comment]
do you mean activity types?

**Comment by davidpesce** [comment]
Yea. Issue #63

**Comment by davidpesce** [comment]
The quiz completed fix has been merged into master.
