### ISSUE TITLE
Log Quiz attempted rather than attempt started

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#13]
**Motive**
Currently we're logging the start and completion of the quiz-attempt (and using the type `http://activitystrea.ms/schema/1.0/page`?!?). The data generated would fit better with data from e-learning courses if we instead track the attempt and completion of the quiz. 

**Result**
Track the quiz, not the attempt. 

**Additional information**
See [the prototypes](prototypes-getting-started) for examples, especially the quiz at the end of the golf example.

**Comment by ryasmi** [comment]
I agree that the activity type should be changed, however we track the "attempt" not the "quiz" to stay closer to Moodle's log store.

**Comment by garemoko** [comment]
IMHO design of the data sent should not be primarily based on the data available, although obviously that's a constraint. The primary goal of the data sent in statements should be interoperability with other similar data. 

That's my opinion; feel free to disagree!

**Comment by ryasmi** [comment]
I agree that we should try to be interoperable, but not at the cost of clarity. I'm not overly familiar with Moodle and their terminology, but if it's presented in the UI as an attempt then it should be tracked as such.
