### ISSUE TITLE
Scheduled task does not delete records from 'mdl_logstore_xapi_log'

### ISSUE THREAD

**Issue by dasu2013** [davidpesce/moodle-logstore_xapi#130]
**Description**
- Records didn't get deleted from 'mdl_logstore_xapi_log' after successfully sent them to Learning Locker.

**Version**
- 2017061100

**Steps to reproduce the bug**
1. To load the history into Learning Locker, I populated 'mdl_logstore_xapi_log' table and executed scheduled task (similar to this https://github.com/xAPI-vle/moodle-logstore_xapi/issues/42#issuecomment-252853343).
2. Records successfully sent into Learning Locker, however records didn't get deleted from 'mdl_logstore_xapi_log'

**Expected behaviour**
- Records get deleted from 'mdl_logstore_xapi_log' table after successfully sent them to Learning Locker.

**Additional information**
- I found this issue here in store.php
$xapiEvents = $xapiController->createEvents($translatorEventsBatch);
foreach(array_keys($xapiEvents) as $key) {
if (is_numeric($key)) {
$sentEvents[$xapiEvents[$key]['context']['extensions'][$translatorEventReadReturn[0]['context_ext_key']]['id']] = $xapiEvents['last_action_result'];
}
}

$xapiEvents variable get response like this,
Array(
[statements] => Array()
[response] => TinCan\LRSResponse Object(
[success] => 1
[content] => Array() 
)
Therefore is_numeric doesn’t work as array keys are ‘statements’ and ‘response’. Further there is no attribute called 'last_action_result' here.

**Comment by davidpesce** [comment]
Is this only after using the legacy import script that pulls previous log data into the logstore table?

**Comment by Dasuntha** [comment]
Hi David,
This issue is in scheduled task (emit_task.php). It is not affect only for previous log data import. There is an option in plugin settings to 'Send statements by scheduled task'. If user ticked this option, then same event data will send again and again into LRS.

Regards
Dasu

**Comment by davidpesce** [comment]
Ahhh, that makes sense! I was wondering how I wasn't experiencing any of those issues. I should be able to review it this week.

**Comment by bseclier** [comment]
Hello,
Does somebody know if this problem is fixed ?
Thanks,

**Comment by ryasmi** [comment]
Hi @bseclier, I think this is fixed by #131 thanks to @Dasuntha. Unfortunately no one has had time to test it yet so it's not been released.

**Comment by bseclier** [comment]
Hi @ryansmith94,
I just had time to test it and it work very well.
Thank you @Dasuntha !

**Comment by ryasmi** [comment]
Oh that's awesome, thanks @bseclier, I'll get that merged and released.
