### ISSUE TITLE
Feature request: Support username or id-number field as actor account "name" value

### ISSUE THREAD

**Issue by henrikvongunten** [davidpesce/moodle-logstore_xapi#132]
It would be very useful if the plugin could be configured to send the username or user ID-number (HR Import user identifier) instead of the internal Moodle user identifier.

**Comment by garemoko** [comment]
See also https://github.com/xAPI-vle/moodle-logstore_xapi/issues/35

**Comment by ryasmi** [comment]
Good point @garemoko, closing this as a duplicate/extension of #35.
