### ISSUE TITLE
Email is incorrect in actor object for course 'completed' event

### ISSUE THREAD

**Issue by Dasuntha** [davidpesce/moodle-logstore_xapi#135]
Actor's email address is incorrect for course completed event. It picks admin's email address not user's email address. 

"actor": {
      "mbox": "mailto:moodle@example.com",
      "name": "Ann Smith",
      "objectType": "Agent"
    }

**Comment by ryasmi** [comment]
Hi @Dasuntha, thanks for reporting this issue 👍

**Comment by Dasuntha** [comment]
To fix this we need to add email address here,
https://github.com/LearningLocker/Moodle-xAPI-Translator/blob/master/src/Events/CourseCompleted.php#L26-L28

 public function read(array $opts) {
        return [array_merge(parent::read($opts)[0], [
            'recipe' => 'course_completed',
            'user_id' => $opts['relateduser']->id,
            'user_url' => $opts['relateduser']->url,
            'user_name' => $opts['relateduser']->fullname,
            **'user_email' => $opts['relateduser']->email,**
        ])];
    }

**Comment by ryasmi** [comment]
Nice, thanks for that! Feel free to make a pull request for this if you don't want to wait for us to get around to it 😄

**Comment by ryasmi** [comment]
I'm going to try to find some time to automate releases for this repository so we can get these kind of fixes merged more quickly.
