### ISSUE TITLE
SCORM statements not passing activity name or completed status

### ISSUE THREAD

**Issue by mpendergast79** [davidpesce/moodle-logstore_xapi#136]
**Description**
- {{Brief description of your bug}}

**Version**
- {{branch}} at {{commit}} on {{version - found in your copy of the VERSION file}} 

**Steps to reproduce the bug**
1. {{steps}}

**Expected behaviour**
- {{feature}} should be {{expectedResult}} because {{reason}}.

**Actual behaviour**
- {{feature}} is {{actualResult}}.

**Server information**
- {{database}} with {{authentication}}.

**Client information**
- OS: {{operatingSystem}}
- Browser: {{browser}} {{version}}

**Additional information**
- {{additionalInfo}})

**Comment by mpendergast79** [comment]
We are using Moodle 3.2 with the Logstore xAPI plugin. Our content is published for SCORM 1.2 and are published to report Complete/Incomplete. The statements we see in the LRS do not match what we expected to see. When a user views a SCORM activity, the statement that is passed shows the course ID rather than the activity name, and does not pass completed status. We have enabled all possible statements in the xAPI settings page.

**Comment by ryasmi** [comment]
Hi @mpendergast79, thanks for reporting your issue here. Hopefully someone will be able to look at changing the statement soon. The plugin is open to public code changes, so if you can't wait you may be interested in trying to contribute to the code.

**Comment by ryasmi** [comment]
I think this was resolved in version 3 (see example statements below). Going to close this and reopen if it becomes active again.

https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/tests/mod_scorm/scoreraw_submitted/existing_scoreraw_submitted/statements.json
https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/tests/mod_scorm/status_submitted/existing_status_submitted/statements.json
