### ISSUE TITLE
Logstore XAPI for Moodle 3.3 not installing.

### ISSUE THREAD

**Issue by paulraper** [davidpesce/moodle-logstore_xapi#137]
**Description**
XAPI doesn't install in Moodle 3.3

**Version**
2.0.0 

**Steps to reproduce the bug**
1. Try installing it in Moodle 3.3 either directlly from Moodle Plugin Repository, or via the ZIP file directly into Moodle

**Expected behaviour**
Should install

**Actual behaviour**
Error Extracted file not found.

**Server information**
I'm using a mysql database

**Client information**
Debian
Microsft EDGE, Firefox

**Additional information**
None

**Comment by scara** [comment]
For reference, https://tracker.moodle.org/browse/MDL-49329 improved the validations e.g. checking that files listed in the archive are actually expanded into the filesystem.

An empty folder is not extracted from the archive i.e. it doesn't exist in the file system => error. You should get rid of that empty `/bin` folder from the archive.

Note: the issue has been discussed in the Moodle Community first, https://moodle.org/mod/forum/discuss.php?d=358882.

HTH,
Matteo

**Comment by garemoko** [comment]
Is this a duplicate of https://github.com/xAPI-vle/moodle-logstore_xapi/issues/128 ?

**Comment by ryasmi** [comment]
Certainly looks like it @garemoko

**Comment by paulraper** [comment]
It may be a duplicate, but the problem still persists, and is causing some serious issues to arise with all the co-related work required to repair things after platforms are messed up.

**Comment by paulraper** [comment]
The question therefore remains, is a fix in the offing, and if so, when will it be released?

**Comment by ryasmi** [comment]
Closing this as a duplicate of #128. @paulraper this issue is a high priority for this repository and should be in the next release. I can't say when that will be released at this stage as I'm required to work on other projects.

**Comment by paulraper** [comment]
@ryansmith94 Thanks for you super input and support. I have just installed and tested release 2.1.5 from the Moodle repository, and it works fine so far. Excellent and thank you again for your help.
