### ISSUE TITLE
module_viewed not triggered by all modules. 

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#14]
**Version**
{{branch}} at {{commit}} on 2015071400 

Moodle build 2014111001

**Steps to reproduce the bug**
Set up plugin 
Add "External activity" or "Tin Can Launch Link" activity to course.
Open activity 

**Expected behaviour**
module_viewed statement appears in configured LRS

**Actual behaviour**
No statement. Note that this works for some activities and not others. In all cases the event does appear in the standard logging report at /report/log/index.php

**Server information**
Mac with MAMP

**Client information**
OS: Mac
Browser: Chrome version 43

**Additional information**
SCORM Cloud LRS

**Comment by garemoko** [comment]
Also: I get no errors even with developer errors set to maximum.

**Comment by ryasmi** [comment]
You won't get any errors because some modules are not supported by this plugin. The [documentation](https://github.com/jlowe64/moodle-logstore_xapi/blob/master/docs/readme.md#supported-events) states which events are supported.
