### ISSUE TITLE
Maximun Batch Size is not respected

### ISSUE THREAD

**Issue by Nicosoft** [davidpesce/moodle-logstore_xapi#140]
**Description**
I want to load my Learning Record Store/LRS (LearningLocker) by batch (scheduled task).
In the plugin settings, Max Batch Size is set up to 100.
So when the task run for the first time, I am expecting to find 100 records in my LRS, but all the records are sent.

**Version**
- version: 2.0 

**Steps to reproduce the bug**
1. Create a brand new Store in Learning Locker
2. Change the plugin settings as is:
   - maximum batch size=100,
   - Send statements by scheduled task= Yes (ticked)
<img width="725" alt="screen shot 2017-10-05 at 3 10 00 pm" src="https://user-images.githubusercontent.com/4625910/31210774-5433c24c-a9e0-11e7-96f6-8cc80864c840.png">
3. Populate table mdl_logstore_xapi_log by mdl_logstore_standard_log using the following SQL statement.

```sql
INSERT INTO `mdl_logstore_xapi_log` (`eventname`, `component`, `action`, `target`, `objecttable`, `objectid`, `crud`, `edulevel`, `contextid`, `contextlevel`,`contextinstanceid`, `userid`, `courseid`, `relateduserid`, `anonymous`, `other`, `timecreated`, `origin`, `ip`, `realuserid`) SELECT `eventname`, `component`,`action`, `target`, `objecttable`, `objectid`, `crud`, `edulevel`, `contextid`, `contextlevel`, `contextinstanceid`, `userid`, `courseid`, `relateduserid`,`anonymous`, `other`, `timecreated`, `origin`, `ip`, `realuserid` FROM `mdl_logstore_standard_log` 
```

4. Run the schedule task: 
```
php schedule_task.php  --execute=\\logstore_xapi\\task\\emit_task
```

**Expected behaviour**
- When the scheduled task run, 100 statements **should** be added to the Learning Record Store **because** in the plugin settings Maximum Batch Size = 100.

**Actual behaviour**
- When the scheduled task run, **ALL** the statements are sent to the Learning Record Store. **The limit Maximum Batch Size is not respected**.

<img width="353" alt="screen shot 2017-10-05 at 3 24 10 pm" src="https://user-images.githubusercontent.com/4625910/31210922-4a11fa44-a9e1-11e7-8e8a-5912a77d4e24.png">

**Comment by ryasmi** [comment]
Hi @Nicosoft, thanks for reporting this issue 👍

**Comment by Nicosoft** [comment]
Hi @ryansmith94 

There is no issue. After digging into the code, I realised that I misunderstood the 'Maximum Batch Size' settings.

To be clear, let's use an example.
- In your XAPI log table you have 2435 records.
- In your plugin settings, you set Maximum Batch Size = 100.

When the scheduled task run, the system will send ALL the records to your Learning Record Store by group of 100 statements (100 because of Maximum Batch Size set to 100).
In our example, the task will make 25 calls to the Learning Record Store, each call will include 100 statements (except in the last call, it will only send 35 statements).  

Conclusion, the 'Maximum Batch Size' setting works correctly. @ryansmith94 you can close this issue.

Note 1: During a call, if 1 of the statements is rejected, all the statements included in the call will be rejected. So you better set up 'Maximum Batch Size' with a low number.

Note 2: Don't forget that if the task takes too long, Moodle will stop the task. (more see issue #134)

**Comment by ryasmi** [comment]
Ah okay thanks @Nicosoft! 👍

**Comment by garemoko** [comment]
> During a call, if 1 of the statements is rejected, all the statements included in the call will be rejected. So you better set up 'Maximum Batch Size' with a low number.

Really we should have some kind of re-try functionality here if we don't already.

**Comment by ryasmi** [comment]
Yeah I agree @garemoko. Probably a separate issue.
