### ISSUE TITLE
Adding user (actor) group support into context

### ISSUE THREAD

**Issue by nadavkav** [davidpesce/moodle-logstore_xapi#146]
**Description**
- We have users in course groups (not cohorts) that are learning and taking part in various activities on one or more courses. It is also common that, at the same course, users change groups when they switch and move from one activity to the other.
Looking at the statements coming off the Moodle system using xapi_logstore and into the LRS (LLv2) it seems no group information is included. (apart from general information about weather the course "object" is using groupmode, as such)

It seems it should be part of the statements as it is part of the spec, for the actor:
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#2422-when-the-actor-objecttype-is-group
But what would actually be even better is to have it part of the context, as defined here:
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#details-14

(I am also not sure of the LLv2 LRS is actually supporting filtering the statements by actor or context groups, but this is another issue)

Also, seems there is a related open issue:
https://github.com/xAPI-vle/moodle-logstore_xapi/issues/87

**Version**
- xapi_logsotore 2017051500

**Steps to reproduce the bug**
1. Send xAPI events from a Moodle 3.3 course and have the users assigned into groups.

**Expected behaviour**
- xAPI statement should include some group information (maybe, in context of the activity also, as the user switches groups during the course, and it will not be correct to assume she/he is bound to one group for the whole course and have it be part of the actor metadata).

**Actual behaviour**
- No group information in the xAPI statement (as far as I can tell).

**Comment by ryasmi** [comment]
Hey @nadavkav, thanks for reporting this feature request.

In terms of LLV2, I'm pretty sure it does support filtering statements by actor and context groups. You may also want to have a look at using [additional persona data in LLV2](https://ht2ltd.zendesk.com/hc/en-us/articles/115001223771-Adding-Additional-Data-to-People-via-CSV).

**Comment by nadavkav** [comment]
Thank you for confirming my suspicions about this missing feature.
I will try to patch the code myself and add this team support to the activity context 
(hope I do not mess the xAPI spec :wink: )

And great link, thanks! I was not aware I can do that :+1:

**Comment by ryasmi** [comment]
No worries @nadavkav.

Okay that would be great! Haha it'll be fine, I'll review your PR to make sure it's okay.

No worries. I'm glad you found it useful 😄

**Comment by ryasmi** [comment]
I think this could be represented a persona attribute, hence this is somewhat a duplicate of #87, so I'm going to close this.
