### ISSUE TITLE
Log type of module

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#15]
I imagine there will be a lot of data I viewed some course-module. It would be interesting to know what type of course module it was. 

I'm wondering if we can programmtically generate the activity type instead of using "module". Something like "https://moodle.org/plugins/view/" plus [this value](https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/docs/examples/ModuleViewed.json#L42)

**Comment by ryasmi** [comment]
Sounds like a good idea. Currently the only way to tell which type of module was used is by the `object.id`. For example a page's `object.id` looks like `http://localhost/moodle/mod/page/view.php?id=2`.
