### ISSUE TITLE
need to update readme docs

### ISSUE THREAD

**Issue by burkeallen** [davidpesce/moodle-logstore_xapi#155]
documents refer to these directories

vendor/learninglocker/moodle-log-expander
vendor/learninglocker/moodle-xapi-translator
vendor/learninglocker/xapi-recipe-emitter

I do not see where those directories exist in the current repository structure

**Comment by ryasmi** [comment]
Hey @burkeallen, it should be these directories now

- lib/expander
- lib/translator
- lib/emitter

Which documents refer to those directories?

**Comment by burkeallen** [comment]
Ryan,

this is the readme I am referring to

https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/docs/design.md


*Burke Allen*
*NovoLogic, Inc*
*mobile 770-265-4362 *

**Comment by ryasmi** [comment]
Right I think I've fixed them all. Thanks for raising this @burkeallen, give me a shout in this issue if I've missed anything and I'll reopen 👍
