### ISSUE TITLE
Trim attempt_reviewed statement to only include necessary parts

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-logstore_xapi#160]
attempt_reviewed statements are a bit verbose for what they are. Should be a simple statement of:

User reviewed attempt.

Also, remove the QuestionSubmitted recipe so that answers aren't submitted every time.         
https://github.com/xAPI-vle/moodle-logstore_xapi/blob/516bf881c09ff2ddee43694edfb84cde42ebe4e5/lib/translator/src/Controller.php#L52

**Comment by ryasmi** [comment]
In the new architecture branch I've started stripping a lot of stuff from
statements, mostly extensions and descriptions.

**Comment by binote00** [comment]
We want to use logstore_xapi plugin in our Moodle projects and possibly modify the plugin.
Your architecture branch looks very interesting especially when you said "stripping a lot of stuff from statements, mostly extensions and descriptions"
What's your plans about [this](https://github.com/xAPI-vle/moodle-logstore_xapi/issues/115) branch ? Any ETA ?

**Comment by ryasmi** [comment]
https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v3.0.0
