### ISSUE TITLE
Divide by zero error on scoreraw_submitted event

### ISSUE THREAD

**Issue by binote00** [davidpesce/moodle-logstore_xapi#161]
**Description**
- if scoremin and/or scoremax are not defined when the scoreraw_submitted event is triggered then score values are not sent to the LRS. It generate a divide by zero php error.

**Version**
- branch master at commit 516bf88 version 2017061100

**Additional information**
- Tested with SCORM 1.2 basic golf scorm

**Comment by davidpesce** [comment]
Thanks for submitting this! I've just merged it into master. We've got a few other upcoming changes before adding another version release.
