### ISSUE TITLE
Include cmi.interactions_x data as extension in scorm completion

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-logstore_xapi#164]
I'm not sure if this is a global thing, but in an Articulate SL course, the answers to assessment questions are included as cmi.interactions data. It'd be nice to capture this! 

We may also be able to interpret it a bit and send them as individual statements.

**Comment by garemoko** [comment]
I'm surprised if we aren't already doing this.

**Comment by ryasmi** [comment]
Which events would require this change and how would it effect the statements @davidpesce?
