### ISSUE TITLE
Cron should be the default way to send statements

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-logstore_xapi#165]
Switch the default plugin setting to use the Moodle cron to send statements.

The alternative is blocking execution if Moodle isn't able to handle the load and/or the LRS not able to receive (and respond). The cron would send them as a batch (less load on both Moodle and LRS)

**Comment by ryasmi** [comment]
If existing users are using the current default setting (non-cron), does changing this default mean that their setting will be changed @davidpesce? I wouldn't have thought that would be the case, but if it is then we probably can't change this default.

If we can change this default then I suggest we do it now, but make sure there is a note somewhere that this plugin requires the cron setup by default.
