### ISSUE TITLE
Incorrect site ID set

### ISSUE THREAD

**Issue by kineodarrenr** [davidpesce/moodle-logstore_xapi#168]
**Description**
Copied from our Developer:
This is an issue with the HT2 plugin, currently it assumes that the site id is 1, but it's not in our site, they should be using the get_site function:

diff --git a/admin/tool/log/store/xapi/lib/expander/src/Repository.php b/admin/tool/log/store/xapi/lib/expander/src/Repository.php
index f560170..e5ff19b 100644
--- a/admin/tool/log/store/xapi/lib/expander/src/Repository.php
+++ b/admin/tool/log/store/xapi/lib/expander/src/Repository.php
@@ -300,7 +300,7 @@ class Repository extends PhpObj {
      * @return PhpObj
      */
     public function read_site() {
-        $model = $this->read_course(1);
+        $model = $this->read_course(get_site()->id);
         $model->url = $this->cfg->wwwroot;
         $model->type = "site";
         return $model;

**Version**
v2.2.4

**Comment by ryasmi** [comment]
Hey @kineodarrenr, thanks for reporting this. It's being fixed as part of version 3 which we're hoping to release between the end of May and middle of June.

For the record, this isn't a HT2 plugin, whilst initial development was started by HT2 and CLC this plugin is not actually owned by anyone.

**Comment by ryasmi** [comment]
https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v3.0.0
