### ISSUE TITLE
Logs being written to publicly facing directory

### ISSUE THREAD

**Issue by kineodarrenr** [davidpesce/moodle-logstore_xapi#169]
**Description**
there is an issue with the logging in this plugin which means it fails our security standard, if debugging is switched on then it will try to write to a public facing directory:

    private function error_log($message) {
        if ($this->loggingenabled) {
            // @codingStandardsIgnoreLine
            error_log($message."\r\n", 3, __DIR__.'/error_log.txt');
        }
    }

This should be changed to a configurable location or changed to output to the moodledata directory, otherwise sensitive information could be exposed.

**Version**
v2.2.4

**Comment by ryasmi** [comment]
Hey, thanks for reporting the issue @kineodarrenr, I can't remember how that logging is enabled, but pretty sure it's always turned off in production.

**Comment by garemoko** [comment]
I wonder if there's a central Moodle log place that we should be using.

**Comment by davidpesce** [comment]
Not that I've seen. The logging is in the Moodle interface or the web server (apache) logs.

**Comment by ryasmi** [comment]
https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v3.0.0
