### ISSUE TITLE
Implementation of the Moodle privacy API

### ISSUE THREAD

**Issue by peterdobinson** [davidpesce/moodle-logstore_xapi#171]
**Description**
The latest GDPR 'compliant' versions of Moodle require plugins to implement the privacy API, so that they can allow for a subject access request or a subject deletion request.

You can read about the plugin here, https://docs.moodle.org/dev/Privacy_API the main part thats going to have to be implemented is the external export indication as per https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location .

**Comment by ryasmi** [comment]
Certainly something we'll look into for version 3, thanks @peterdobinson 👍

**Comment by ewallah** [comment]
The privacy api has been updated in the last months, so testing this api produces 2 failures:

vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php

There were 2 failures:

1) provider_testcase::test_all_providers_compliant with data set "logstore_xapi" ('logstore_xapi', 'logstore_xapi\privacy\provider') Failed asserting that false is true.

2) provider_testcase::test_table_coverage
The following tables with user fields must be covered with metadata providers:
  - logstore_xapi_log (userid)
  - logstore_xapi_failed_log (userid)

**Comment by ryasmi** [comment]
Interesting, thanks @ewallah. Definitely something that needs to be addressed quite urgently.

**Comment by davidpesce** [comment]
There is a PR (#605) for this. Closing unless there are objections.
