### ISSUE TITLE
Not registering questionaries statements 

### ISSUE THREAD

**Issue by ghost** [davidpesce/moodle-logstore_xapi#185]
**Description**
- Some statements aren't sent for the LRS

**Version**
- Moodle -> 3.5
- Logstore_xapi -> Last

**Steps to reproduce the bug**
1. Finish any questionary

**Client information**
- OS: all of they
- Browser: any browser

**Additional information**
- Some statements were sent and others not when some user finish an activity type questionary.

**Comment by davidpesce** [comment]
Hi @lucasmellos . Thanks for reporting! Work is already underway on fixing this: https://github.com/xAPI-vle/moodle-logstore_xapi/pull/183

**Comment by ryasmi** [comment]
Yeah the conversation can be followed in #183 and #174. I've updated the title of #174 to more accurately describe the present discussions in that issue.
