### ISSUE TITLE
Scaled scores are not being calculated accurately.

### ISSUE THREAD

**Issue by FeLungs** [davidpesce/moodle-logstore_xapi#191]
**Description**

Scaled score is being calculated incorrectly [here](https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/src/transformer/events/mod_assign/assignment_graded.php#L52) as defined by the [xAPI Spec](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#Score)

**Steps to reproduce the bug**

1. look at the data, the min scaled score can be is 0 when its suppose to be -1.0
- see [here](https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/tests/mod_quiz/attempt_submitted/existing_attempt_submitted/statements.json#L31), the scaled value should be 0.0 not 0.5.

**Expected behaviour**
- when raw is 50, min is 0 and max is 100, scaled value should be 0.0. If raw was 75 with the same min and max, the scaled value would be 0.5. This is due to the definition of scaled scores within xAPI statements linked to above.

**Additional information**

generic scaling equation:

x1 is the original scale min, y1 is the new scale min.

x2 is the original scale max, y2 is the new scale max.

raw is the value to be converted from (x1, x2) to (y1, y2)

the fn is:
  f(raw,x1,x2,y1,y2) = raw((y1 - y2) / (x1 - x2)) +  (y1 - x1((y1 - y2) / (x1 - x2)))

  - this is just f(x) = ax + b
    - a = ((y1 - y2) / (x1 - x2))
    - b = y1 - x1a

To create a scaled score according to the xAPI spec, 
y1 should be -1.0 and y2 should be 1.0 and x1 is the current min and x2 should be the current max.

**Comment by garemoko** [comment]
xAPI doesn't define how scaled score should be calculated. It's up the the LRP (i.e. the authors of this plug) to define a sensible way to calculate it.

**Comment by FeLungs** [comment]
IMO, the purpose of having a scaled score is so that performance can be compared across statements and LRPs.

While you are technically correct, the spec doesn't enforce one way to calculate the scaled score, I think there needs to be consensus within the larger xAPI community on how the scaled field is used or at least a way to describe the scaling methodology within the statement.
