### ISSUE TITLE
"THIS REPO IS UNDER HEAVY DEVELOPMENT AND IS NOT PRODUCTION READY"

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#2]
With all the fanfare, is this still true?

**Comment by jlowe64** [comment]
I wouldn't say it's unsafe to install, but you will have a very limited view of the overall activity. There's only a small sampling of events that have been translated. 

Will depend on your expectations.

**Comment by ryasmi** [comment]
Let's just remove that notice now.

**Comment by jlowe64** [comment]
Agreed. I was mostly for while it wasn't working at all.

**Comment by jlowe64** [comment]
Fixed with [commit 93df073a10](https://github.com/jlowe64/moodle-logstore-xapi/commit/93df073a10108dd5adc579b56d4fee84bcbab6b8)
