### ISSUE TITLE
Report success and scaled score for quizzes and assignments

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#22]
Assignments and quizzes currently report completion and raw score. It would be useful for these to also report scaled score and success if the data is available. 

In Moodle the pass mark for an assignment, quiz or other scored item can be set in grade administration. Go to course admin / grades / Grade report. Then turn editing on an click the cog under the item to set the pass mark.

**Comment by jlowe64** [comment]
We can definitely look into this! Probably would help with certain activities on the dashboards that will eventually be made for it. :)

**Comment by jlowe64** [comment]
Just to make this simpler for me, what DB tables, or relevant functions within Moodle would be used if this suggestion were taken on board?

**Comment by garemoko** [comment]
@jlowe64 does this block of code give you what you need?

https://github.com/leo-platforms/moodle-quiz-tincan/blob/master/report/tincan/lib.php#L513-L529

**Comment by jlowe64** [comment]
Yes, that looks good to me!

**Comment by jlowe64** [comment]
I'll add this to the list of things to do for the 0.4.0 release.

**Comment by ryasmi** [comment]
What's the state of this? Seems we're at 0.5.1 now.

**Comment by jlowe64** [comment]
Was a bit more than I had time for for the release.  And by "0.4.0" I meant the libraries not this one.

**Comment by ryasmi** [comment]
Ok :smile:

**Comment by garemoko** [comment]
There's 3 PRs out to cover this now:
- https://github.com/LearningLocker/Moodle-Log-Expander/pull/20
- https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/23
- https://github.com/LearningLocker/xAPI-Recipe-Emitter/pull/20

**Comment by garemoko** [comment]
All PRs merged so I'm closing this.
