### ISSUE TITLE
Re-consider object for quiz attempt completed 

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#23]
**Motive**
The quiz attempt completed  graded event could be very useful to report on how a group of learners did in a particular  quiz. As it is, this statement only identifies which quiz has been completed in the contextActivities.grouping property, alongside other activities. 

This makes it difficult for reporting tools to report on a group of learners attempts at a quizl unless they have been specifically designed to work with this Moodle data, defeating the purpose of interoperability.

**Result**
Instead, the quiz should be the object of the statement, or an additional statement should be recorded of the structure learner completed/passed/failed the quiz.

**Comment by garemoko** [comment]
Below is an example of a configurable report in Watershed LRS that illustrates one side affect of treating attempts as activities. Note "Attempt 1" and "Attempt 2" in the list. 

![image](https://cloud.githubusercontent.com/assets/1363163/9938250/5a0c216e-5d5c-11e5-84da-b5f8d019e9e2.png)

**Comment by jlowe64** [comment]
@garemoko I am not as much an xAPI expert as you or ryan are. Could you please do me a favor and show me an example of the statement before your change and after your change so I can see the changes? I'm much more a visual learner.

**Comment by garemoko** [comment]
Sure. I'll do a PR to the documentation perhaps.

**Comment by garemoko** [comment]
See the commit above for the diff in the example statement.

**Comment by jlowe64** [comment]
I see no reason why this can't be done, and your case does make a lot of sense. I'll add this to the list of things needed for the 0.4.0 release.
