### ISSUE TITLE
Re-consider object for assignment attempt graded

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#24]
**Motive**
Similar to #23. It would be helpful to be able to report on the grades of learners on a given assignment. This is difficult with the current AssignmentGraded statement as the assignment being graded is only included as a grouping contextActivity. 

**Result**
There are arguments for a few different statement objects, which we can discuss here. My preference is that the object is a [statement reference](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#statement-references) for the related assignment submitted statement. I.e. Tutor graded Learner submitted Assignment.

**Comment by ryasmi** [comment]
Might be easier for you to implement as a sub statement first @jlowe64.

**Comment by jlowe64** [comment]
@garemoko similar to the other, could you show me an example of the statement before and after? I've been googling substatements, and there seems to be some info within TinCanPHP that is relevant, so I'll take a look at the exact implementation later.

**Comment by garemoko** [comment]
Statement reference would be better but @ryansmith94 is right that sub statement would be easier. Lets figure out if statement reference is possible before I do the example statement: is there any way you can store the statement id for the assignment submitted statement within the plugin and retrieve that id when the assignment is graded?

**Comment by jlowe64** [comment]
I think that would involve setting up another db table to hold assignment submitted statements in a queue until assignment graded is sent off. It may, indeed, be easier to do a substatement right now until that can be a focus.

**Comment by garemoko** [comment]
I don't think the queue is a good solution because it's possible the assignment is never graded (or waits several weeks to be graded) - you'd still want to know that it was submitted. We'd just want to store the statement id in the database, associated with the assignment submission that's waiting to be graded. 

I'll draw up a sub statement using one of those in the documentation as I did for the other issue.

**Comment by jlowe64** [comment]
That's exactly what I was suggesting, maybe I wasn't clear. Sorry about that.

Thank you!

**Comment by garemoko** [comment]
Here's an example of using a sub-statement: https://github.com/LearningLocker/xAPI-Recipe-Emitter/compare/master...garemoko:patch-2

What I did was: 
1. Copied the [assignment submitted statement](https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/docs/examples/AssignmentSubmitted.json) and made it the object.
2. Removed the authority, stored and id properties from this copy. 
3. Added `"objectType": "SubStatement",`

Assuming that you are still going to issue the assignment submitted statement on it's own, you could prune the sub statement, removing the context, and activity definition. Ideally you should keep the timestamp and use the context.statementRef property, but if you know the statement reference, you should just use a statement reference object instead anyway.  

Another approach to get the statement reference would be to [query the LRS](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#stmtapiget) for a statement matching the learner, verb and assignment activity id. That would save you storing anything in the database. Statement reference really would be the best approach here. 

With TinCan PHP fetching statements is something like:

```
$statementsQuery = array(
    "verb"=>"http://adlnet.gov/expapi/verbs/completed",
    "activity"=>"http://localhost/moodle/mod/assign/view.php?id=10",
    "agent"=> array(
        "account"=> array(
            "name"=> "2",
            "homePage"=> "http://localhost/moodle"
        )
    )
);

$statementsResponse = $lrs->queryStatements($statementsQuery);
$firstStatement = array_values($statementsResponse->content->getStatements())[0];
$statementId = $statement->getId();
```

Obviously you'd need to fill in some of these values programmatically. 

Taking the first statement assumes that there is only one submission per assignment. If there is the possibility of multiple submissions, we'd need some way of knowing which submission was being graded. Maybe there's something in the moodle_logstore_standard_log we can match on?

**Comment by garemoko** [comment]
Coming back to this, I don't like either the sub statement or statement reference approaches because they both assume that the teacher is grading a submission. However, in Moodle the teacher grades the student for the assignment, rather than a particular submission for that assignment. Further, sub statements and statement references as objects are not commonly used and therefore are not well supported by reporting tools (such as Watershed). 

Actually, what I think is important in this event is not that the teacher graded the student, but that the student received the grade. On that basis, I'm going to change the statement to Student Scored for Assignment (instructor). It looks like I can achieve that by changing the recipe emitter only, though I'll probably also bulk out the result object as I've done for quizzes at the same time, which may require changes elsewhere. 

If in future there's a use case for tracking teacher activity and that statement is not sufficient, then we can look at sending two statements.

**Comment by ryasmi** [comment]
I agree the student should be the focus and this actually solves [another issue](https://github.com/LearningLocker/StatementFactory/pull/7) for me.
