### ISSUE TITLE
Not getting 'submission_graded' event

### ISSUE THREAD

**Issue by talbronfer** [davidpesce/moodle-logstore_xapi#247]
**Description**
I've managed to setup the plugin successfully, and I've getting events with verbs such as 'completed' and 'viewed'. However, I'm looking for the submission_graded event (in my scenario, the grade is applied by an external tool). I **can** see the event recorded in the course logs (viewing the logs from Moodle), but they are never sent to the LRS.

I've seen [this was an issue in the past](https://github.com/xAPI-vle/moodle-logstore_xapi/issues/173) and seemingly resolved, however still not working for me even after double checking and updating the plugin.

**Version**
- master, version 3.17.0

**Steps to reproduce the bug**
1. Grade a student assignment
2. Look for the log

**Expected behaviour**
- The log should be recorded with the 'graded' verb and the corresponding event_name

**Actual behaviour**
- Grading events are not recorded

**Client information**
Moodle 3.5.1+

**Comment by ryasmi** [comment]
Hi @talbronfer, thanks for reporting this issue. Can you please check for statements with the scored verb (`http://adlnet.gov/expapi/verbs/scored`) and let me know if you see any of those?

As shown in the additional information below, this event has been supported and tested, it's possible that if there are no statements for this event, there may be some error preventing it from sending. This error should be in your PHP logs or wherever Moodle is configured to write error logs.

### Additional Information
Relevant transformer:
https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/src/transformer/events/mod_assign/assignment_graded.php

Relevant example statement:
https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/tests/mod_assign/assignment_graded/existing_assignment_graded/statements.json

Relevant test data:
https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/tests/mod_assign/assignment_graded/existing_assignment_graded/data.json

Relevant test event:
https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/tests/mod_assign/assignment_graded/existing_assignment_graded/event.json

**Comment by garemoko** [comment]
If the assignments in question had a negative grade, or if the grade was lower than the pass mark, it could have been generating an invalid statement and being rejected by the LRS. 

These issues were fixed in https://github.com/xAPI-vle/moodle-logstore_xapi/pull/362

**Comment by davidpesce** [comment]
Fixed per @garemoko . Closing
