### ISSUE TITLE
Add context activties

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#25]
**Motive**
It would be nice to be able to filter groups of statements for those that originated from Moodle in general and from a particular Moodle instance. 

**Result**
To do this, we should add a context activity (category) for Moodle as a technology and another for the Moodle instance (grouping).

**Comment by ryasmi** [comment]
Sounds like a duplicate of #11

**Comment by garemoko** [comment]
Oh, I just realised that I didn't get the latest version before testing this yesterday. Sorry about that. Please ignore my issues for now (but leave them open). I'll aim to test them with the latest version asap.

**Comment by ryasmi** [comment]
No worries, I've asked Jerrett to make a new release with the updated
dependencies.

**Comment by jlowe64** [comment]
I'll be working on a new release this week. This week will be mostly cleaning up PRs, and updating with the libraries. I'll leave this open until you confirm that it's okay.

**Comment by jlowe64** [comment]
@garemoko could you please take a look again to see if your issues have been fixed in the newest version (v0.5.1)? https://moodle.org/plugins/view/logstore_xapi

**Comment by garemoko** [comment]
@jlowe64 the contextActivities property is being used now, however it is listing a course as the context activity and not the site. (Possibly related to #28). 

Currently we have:

```
"contextActivities": {
            "grouping": [
                {
                    "id": "http://localhost:8888/moodle/course/view.php?id=1",
                    "definition": {
                        "name": {
                            "en": "test"
                        },
                        "description": {
                            "en": "A Moodle course"
                        },
                        "type": "http://lrs.learninglocker.net/define/type/moodle/course"
                    },
                    "objectType": "Activity"
                }
            ]
        }
```

I would like:

```
"contextActivities": {
    "grouping": [
        {
            "id": "http://localhost:8888/moodle/",
            "definition": {
                "name": {
                    "en": "test"
                },
                "description": {
                    "en": "test"
                },
                "type": "http://id.tincanapi.com/activitytype/site"
            },
            "objectType": "Activity"
        }
    ], 
    "category": [
        {
            "id": "http://moodle.org",
            "definition": {
                "name": {
                    "en": "Moodle"
                },
                "description": {
                    "en": "Moodle is a open source learning platform designed to provide educators, administrators and learners with a single robust, secure and integrated system to create personalised learning environments."
                },
                "type": "http://id.tincanapi.com/activitytype/source"
            },
            "objectType": "Activity"
        }
    ]  
}
```

**Comment by jlowe64** [comment]
Will look into this this week!

**Comment by ryasmi** [comment]
Is there any progress on this @jlowe64?

**Comment by jlowe64** [comment]
Nothing beyond a bit of local research. Was planning on picking this up after my holiday.

**Comment by ryasmi** [comment]
Ok :+1:

**Comment by garemoko** [comment]
@jlowe64 I'm planning on tackling this and the two other issues I've raised tomorrow. If you'd rather I don't (e.g. if you've already done a bunch of work) please let me know. Also if you have any hints on how to get started on any of these, that's also very welcome. I'm loosely aiming to get all the events currently tracked by this plugin sending statements that work well with LRS reports (specifically Watershed LRS) by the end of January.

**Comment by jlowe64** [comment]
@garemoko I have been swamped at work (got like 2 or 3 huge projects going on at the same time), so I haven't been able to tackle these things myself. I would absolutely love for someone else to help out to keep the project moving along. 

The biggest tip I can give you is to look at the example statements included in each of the 3 steps (libraries) and match those, and to write the tests first or in sequence with your development. One of the other contributors didn't do this, so I wasn't able to integrate his work into the plugin. If you have any specific questions just open an issue and we can work through the specifics together. 

Thank you so much for taking this up! I really appreciate it.

**Comment by ryasmi** [comment]
@garemoko like @jlowe64 said it would be awesome to have someone else to help out, so thanks a lot :+1:

I think the [Developer Guide](https://github.com/jlowe64/moodle-logstore_xapi/blob/master/docs/developers.md) will have everything you need to get started.

**Comment by garemoko** [comment]
I'm planning to modify the createEvent function in vendor/xapi-recipe-emitter/src/Controller.php so that it adds these context activities to each statement.

**Comment by ryasmi** [comment]
Hey @garemoko, you should use [vendor/xapi-recipe-emitter/Events/Event.php](https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/src/Events/Event.php) instead. The logic of the Controlller should be restricted to routing only.

**Comment by garemoko** [comment]
@ryansmith94 thanks. I didn't spot that file.

**Comment by ryasmi** [comment]
No worries :+1:

**Comment by garemoko** [comment]
Two questions: 
1. How do I get the error messages generated from the plugin for debugging purposes?
2. Whats the best way to get the Moodle site url, name and description within that event.php file? Do i need to add something to Event.php's read function in the log expander?

**Comment by ryasmi** [comment]
1. Logging is a pain in the backside with Moodle, but if you check out [classes/log/store.php](https://github.com/jlowe64/moodle-logstore_xapi/blob/master/classes/log/store.php#L99) you will see a bunch of comments around line 99. If you uncomment those you should get some logging in a "error_log.txt" file in that directory.
2. I think you should be able to use `$opts['app']['url']`, etc from looking at the [docs in the translator](https://github.com/LearningLocker/Moodle-xAPI-Translator/blob/master/docs/examples/ModuleViewed.json#L98).

**Comment by garemoko** [comment]
Thanks for the hint on the logging. Ill get that set up after lunch. It looks like $opts['app']['url'] is the url of the first course, rather than the site, so I've added another opt key called "site" that passes through the event.php file of the three parts of the plugin. Seems to work!

I'll figure out tests and make a PR for this one this afternoon.

**Comment by ryasmi** [comment]
In Moodle the first course is actually the site.

**Comment by garemoko** [comment]
@ryansmith94 right, we've discussed that before, but an activity object representing the site should different in two ways:
1. the activity id is the base site url rather than the course url
2. the default name and description needs to be "A Moodle site" rather than "A Moodle course" 

These points will make more sense when I publish the PR if they don't already.

**Comment by garemoko** [comment]
The three PRs above are now complete and ready for review. Due to the complexities of this multi-repository project and since this is my first contribution, I'm going to hold off tackling the other issues until at least getting feedback on those PRs and ideally getting them merged.

**Comment by ryasmi** [comment]
Sorry @garemoko, I actually thought both of those issues had been corrected. If not, then the contents of `app` needs changing in the expander. I don't think we should create a new key (`site`).

Thanks for the PRs, I'll try to take a look. No worries.

**Comment by garemoko** [comment]
Yeh, as you'll have now already seen, that's the approach I took. 

Thanks for your feedback; those are now ready for another review.

**Comment by garemoko** [comment]
Yeh, as you'll have now already seen, that's the approach I took. 

Thanks for your feedback; those are now ready for another review.

**Comment by ryasmi** [comment]
Yeah nicely done :+1: I've just given them another review and merged one of them :smile:

**Comment by garemoko** [comment]
Pending tests passing on the emitter, these are good to go. I'm now going to start work on the next issue.

**Comment by ryasmi** [comment]
Ok. By the way, if you run `./vendor/bin/phpunit` in the plugin directory it will run [integration tests](https://github.com/jlowe64/moodle-logstore_xapi/tree/master/tests) for the three components (expander, translator, and emitter). If you didn't add new events, it should all pass I think.

**Comment by garemoko** [comment]
All PRs merged so closing.

**Comment by ryasmi** [comment]
Reopening this because https://github.com/LearningLocker/xAPI-Recipe-Emitter/pull/19 needs revisiting.

**Comment by garemoko** [comment]
@ryansmith94 thanks!

**Comment by ryasmi** [comment]
I think this is resolved now, can you confirm @garemoko?

**Comment by ryasmi** [comment]
Make sure you run the [integration tests](https://github.com/jlowe64/moodle-logstore_xapi/issues/25#issuecomment-170944314) every now and then too @garemoko.

**Comment by garemoko** [comment]
@ryansmith94 the way I'm set up is a little different to the instructions, so I'm not sure I can run the integration tests, however I am testing In Moodle to make sure the thing actually works. If you or @jlowe64 runs integration tests before doing a release, that should catch any problems I miss. I don't want to spend a bunch of time messing with my set up now.

**Comment by ryasmi** [comment]
@garemoko ok that's fine then. I have asked @jlowe64 to run the integration tests before doing a release to be sure everything is working.
