### ISSUE TITLE
Confusing release zip/tz files

### ISSUE THREAD

**Issue by Nicosoft** [davidpesce/moodle-logstore_xapi#261]
Hi there,

**Description**
- I am confused with the release zip/tz files

**Version**
Let's take an example: Release v3.17.0
In this release you offer 3 different files:
- xapi.zip
- Source Code (zip)
- Source Code (tar.gz)

**Expected behaviour**
- The version number should be identical in all files (version.php) for a specific release

**Actual behaviour**
The version number is different in the xapi.zip compare to Source Code files in version.php file.
Only xapi.zip is correct.
- xapi.zip
`$plugin->version = 2018090301;`
- Source Code (zip)
`$plugin->version = 2018082100;`
- Source Code (tar.gz)
`$plugin->version = 2018082100;`

Don't you agree that this behaviour is confusing? and could lead to issues?
Or is there a specific reason?

Cheers

**Comment by ryasmi** [comment]
Hi @Nicosoft, the "Source Code (zip)" and "Source Code (tar.gz)" are not to be used, they're created by Github by default so we don't have control over them. In all of our documentation we say to use "xapi.zip".

Thanks for reporting this, but nothing we can actually do unfortunately.
