### ISSUE TITLE
Discontinue PHP 5 support.

### ISSUE THREAD

**Issue by ryasmi** [davidpesce/moodle-logstore_xapi#268]
When we hit 1st January 2019 we should stop testing for PHP 5.6 and only test on PHP 7.1 and above 
since PHP 5.6 will no longer receive security patches.

This will certainly suck for some people using Moodle on older versions of PHP, but they should definitely be upgrading to PHP 7.1 for security patches and we don't want to encourage people to use insecure versions of PHP.

As a benefit it will mean that we can start using PHP 7.1 features like scalar types, etc.

**Comment by davidpesce** [comment]
Fixed in PR #612
