### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: PHP catchable fatal error

### ISSUE THREAD

**Issue by CinecaElearning** [davidpesce/moodle-logstore_xapi#27]
when the logstore-xapi is enabled, the moodle cron job (./admin/cli/cron.php) often returns error messages (even though the module seems to do its job correctly). This happens, for example, once a user completes a course:

$ php ./html/admin/cli/cron.php 
PHP Warning:  var_export does not handle circular references in /var/www/html/lib/classes/shutdown_manager.php on line 83
PHP Warning:  var_export does not handle circular references in /var/www/html/lib/classes/shutdown_manager.php on line 83
PHP Warning:  var_export does not handle circular references in /var/www/html/lib/classes/shutdown_manager.php on line 83
PHP Warning:  var_export does not handle circular references in /var/www/html/lib/classes/shutdown_manager.php on line 83
PHP Warning:  var_export does not handle circular references in /var/www/html/lib/classes/shutdown_manager.php on line 83
Exception ignored in shutdown function array (
  0 => 
  tool_log\log\manager::__set_state(array(
     'readers' => 
    array (
      'logstore_standard' => 
      logstore_standard\log\store::__set_state(array(
         'logguests' => '1',
         'manager' => NULL,
         'component' => 'logstore_standard',
         'store' => '',
         'buffer' => 
        array (
        ),
         'buffersize' => '50',
         'count' => 0,
      )),
    ),
     'writers' => 
    array (
      'logstore_standard' => 
      logstore_standard\log\store::__set_state(array(
         'logguests' => '1',
         'manager' => NULL,
         'component' => 'logstore_standard',
         'store' => '',
         'buffer' => 
        array (
        ),
         'buffersize' => '50',
         'count' => 0,
      )),
      'logstore_xapi' => 
      logstore_xapi\log\store::__set_state(array(
         'manager' => NULL,
         'component' => 'logstore_xapi',
         'store' => '',
         'buffer' => 
        array (
        ),
         'buffersize' => 50,
         'count' => 0,
      )),
    ),
     'stores' => 
    array (
      'logstore_standard' => 
      logstore_standard\log\store::__set_state(array(
         'logguests' => '1',
         'manager' => NULL,
         'component' => 'logstore_standard',
         'store' => '',
         'buffer' => 
        array (
        ),
         'buffersize' => '50',
         'count' => 0,
      )),
      'logstore_xapi' => 
      logstore_xapi\log\store::__set_state(array(
         'manager' => NULL,
         'component' => 'logstore_xapi',
         'store' => '',
         'buffer' => 
        array (
        ),
         'buffersize' => 50,
         'count' => 0,
      )),
    ),
  )),
  1 => 'dispose',
):Coding error detected, it must be fixed by a programmer: PHP catchable fatal error

**Comment by jlowe64** [comment]
That error seems a bit useless, however there's a PR currently being reviewed that may fix this issue. Perhaps in the next release your problem will be addressed!

**Comment by jlowe64** [comment]
Could you please check if this still happens with the newest release v0.5.1? You can find it here: https://moodle.org/plugins/view/logstore_xapi

**Comment by jlowe64** [comment]
This no longer an issue after accounting for NULL's.
