### ISSUE TITLE
Scaled score not calculated properly for quizzes that use marks

### ISSUE THREAD

**Issue by petarnikolovski** [davidpesce/moodle-logstore_xapi#271]
**Description**

I have a course that uses both "marks" and "grades" e.g.

![Marks vs Grades - Moodle](https://i.imgur.com/SDLkJHS.png)

But when a user completes a quiz, the quiz score is not calculated properly, instead of getting 1 for the scaled results, a user gets instead mark (raw) converted to percents. In this case: 0.16 (for the last attempt). Also, the attempt was success, and it's accepted, but the success status is set to `false`.

```
    "timestamp": "2018-09-24T10:55:11+01:00",
    "result": {
      "score": {
        "raw": 16,
        "min": 0,
        "max": 100,
        "scaled": 0.16
      },
      "completion": true,
      "success": false,
      "duration": "PT96S"
    }
```

The quiz can have maximum mark of 16, which when scaled to grade is 100%.

**Version**
```
$plugin->version = 2018080302;
$plugin->release = 'v3.14.1';
$plugin->requires = 2014111000;
```

**Steps to reproduce the bug**
1. Download this course https://moodle.net/?coverage=all&language=en&orderby=newest&search=python&downloadable=1&enrollable&submitbutton=1 (Python for Beginners 1 - Python Language Basics)
2. Do any quiz

**Expected behaviour**
- `scaled` should be '1' because user had 16/16 mark.
- `success` should be `true` because user has passed the quiz.

**Actual behaviour**
- `scales` is `0.16`.
- `success` is set to `false`.

**Server information**
- Moodle with Mysql on one server
- LRS is on a separate server running Learning Locker with mongo db

**Client information**
- OS: Ubuntu 16.04

**Comment by ryasmi** [comment]
Hi @petarGitNik thanks for reporting this. Looks like the max score was picked up incorrectly as 100. Could you please share the full statement (removing any personally identifiable information)? The full statement has some additional information in which is useful for us in tracking down the issue.

**Comment by petarnikolovski** [comment]
Hi Ryan, here is the full statement:

```json
{
  "stored": "2018-09-24T10:00:04.323Z",
  "active": true,
  "completedForwardingQueue": [],
  "failedForwardingLog": [],
  "client": "5ba236a44512b2044907712a",
  "lrs_id": "5ba241f24512b2044907712b",
  "completedQueues": [
    "STATEMENT_FORWARDING_QUEUE",
    "STATEMENT_QUERYBUILDERCACHE_QUEUE",
    "STATEMENT_PERSON_QUEUE"
  ],
  "activities": [
    "http://lms.example.com/mod/quiz/view.php?id=11"
  ],
  "hash": "cee6f2a96cad4157fc5decda358fc99d2b01ac22",
  "agents": [
    "mailto:petargitnik@example.com"
  ],
  "statement": {
    "authority": {
      "objectType": "Agent",
      "name": "New Client",
      "mbox": "mailto:hello@learninglocker.net"
    },
    "stored": "2018-09-24T10:00:04.323Z",
    "context": {
      "platform": "Moodle",
      "language": "en",
      "extensions": {
        "http://lrs.learninglocker.net/define/extensions/info": {
          "http://moodle.org": "3.4.4 (Build: 20180709)",
          "https://github.com/xAPI-vle/moodle-logstore_xapi": "v3.14.1",
          "event_name": "\\mod_quiz\\event\\attempt_submitted",
          "event_function": "\\src\\transformer\\events\\mod_quiz\\attempt_submitted\\handler"
        }
      },
      "contextActivities": {
        "other": [
          {
            "id": "http://lms.example.com/mod/quiz/attempt.php?attempt=24&cmid=11",
            "definition": {
              "type": "http://adlnet.gov/expapi/activities/attempt",
              "name": {
                "en": "Attempt"
              }
            },
            "objectType": "Activity"
          }
        ],
        "grouping": [
          {
            "id": "http://lms.example.com",
            "definition": {
              "type": "http://id.tincanapi.com/activitytype/lms",
              "name": {
                "en": "Test Moodle LMS Site"
              }
            },
            "objectType": "Activity"
          },
          {
            "id": "http://lms.example.com/course/view.php?id=2",
            "definition": {
              "type": "http://id.tincanapi.com/activitytype/lms/course",
              "name": {
                "en": "Python for Beginners 1 - Python Language Basics"
              },
              "extensions": {
                "https://w3id.org/learning-analytics/learning-management-system/short-id": "PFB1"
              }
            },
            "objectType": "Activity"
          }
        ],
        "category": [
          {
            "id": "http://moodle.org",
            "definition": {
              "type": "http://id.tincanapi.com/activitytype/source",
              "name": {
                "en": "Moodle"
              }
            },
            "objectType": "Activity"
          }
        ]
      }
    },
    "actor": {
      "name": "Petar Nikolovski",
      "mbox": "mailto:petargitnik@example.com",
      "objectType": "Agent"
    },
    "timestamp": "2018-09-24T10:55:11+01:00",
    "version": "1.0.0",
    "id": "c1ecc927-a13d-4705-8755-a9529c501e18",
    "result": {
      "score": {
        "raw": 16,
        "min": 0,
        "max": 100,
        "scaled": 0.16
      },
      "completion": true,
      "success": false,
      "duration": "PT96S"
    },
    "verb": {
      "id": "http://adlnet.gov/expapi/verbs/completed",
      "display": {
        "en": "completed"
      }
    },
    "object": {
      "id": "http://lms.example.com/mod/quiz/view.php?id=11",
      "definition": {
        "type": "http://adlnet.gov/expapi/activities/assessment",
        "name": {
          "en": "Conditionals Review Quiz"
        }
      },
      "objectType": "Activity"
    }
  },
  "hasGeneratedId": true,
  "deadForwardingQueue": [],
  "voided": false,
  "verbs": [
    "http://adlnet.gov/expapi/verbs/completed"
  ],
  "personaIdentifier": "5ba243915ab4db76bdb20819",
  "processingQueues": [],
  "person": {
    "_id": "5ba24391b6b0ab0462bb1626",
    "display": "Petar Nikolovski"
  },
  "__v": 1,
  "timestamp": "2018-09-24T09:55:11.000Z",
  "relatedActivities": [
    "http://lms.example.com/mod/quiz/view.php?id=11",
    "http://lms.example.com",
    "http://lms.example.com/course/view.php?id=2",
    "http://moodle.org",
    "http://lms.example.com/mod/quiz/attempt.php?attempt=24&cmid=11"
  ],
  "relatedAgents": [
    "mailto:petargitnik@example.com",
    "mailto:hello@learninglocker.net"
  ],
  "organisation": "5ba23205800a333be8838ce4",
  "_id": "5ba8b5a424b2f30493b8a28b",
  "registrations": [],
  "pendingForwardingQueue": []
}
```

**Comment by BrendanHalley** [comment]
I just had a quick look and it seems like the max should be coming from the `sumgrades` column on the `quiz` table instead of the grades.

**Comment by ryasmi** [comment]
Thanks @petarGitNik. For reference the specifically useful info is in the context extensions

```json
{
  "http://moodle.org": "3.4.4 (Build: 20180709)",
  "https://github.com/xAPI-vle/moodle-logstore_xapi": "v3.14.1",
  "event_name": "\\mod_quiz\\event\\attempt_submitted",
  "event_function": "\\src\\transformer\\events\\mod_quiz\\attempt_submitted\\handler"
}
```

Relevant code files
- https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/src/transformer/events/mod_quiz/attempt_submitted/handler.php
- https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/src/transformer/events/mod_quiz/attempt_submitted/attempt_submitted.php
- https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/src/transformer/utils/get_attempt_result.php

Relevant test folders
- https://github.com/xAPI-vle/moodle-logstore_xapi/tree/master/tests/mod_quiz/attempt_submitted

Nice digging @trewq, think you might be able to fix this one to get yourself used to contributing?

[Line 24 in the `get_attempt_result` util](https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/src/transformer/utils/get_attempt_result.php#L24) currently defines the max score that is used on line 28 in the same file to calculate the scaled score. The max score is taken from the `grademax` column in the `gradeitem` table. Line 31 in that file defines whether the learner successfully passed the quiz, which uses the `gradepass` column from the `gradeitem` table.

**Comment by BrendanHalley** [comment]
> think you might be able to fix this one to get yourself used to contributing?

Yep, I'll take this on. Thanks for all the context.

**Comment by ryasmi** [comment]
Awesome thanks @trewq, give me a shout if you need any further context 👍

**Comment by akcapinar** [comment]
This problem still exists in the version v4.2.0 (2019010801). Following method is still getting a total score from `$maxscore` instead of `sumgrades`. Can you please tell me if there is any solution.

```
function get_scaled_score($rawscore, $minscore, $maxscore) {
    if ($rawscore >= 0) {
        return $rawscore / $maxscore;
    } else {
        return $rawscore / $minscore;
    }
```

**Comment by BrendanHalley** [comment]
@akcapinar I plan on resolving this tomorrow.

**Comment by akcapinar** [comment]
> @akcapinar I plan on resolving this tomorrow.

@BrendanHalley I have tested with the new release (v4.2.2) but the scaled score is still wrong.

**Comment by BrendanHalley** [comment]
@akcapinar Other things came up and I haven't had a chance to look at it yet. I'll get to it ASAP.

**Comment by akcapinar** [comment]
@BrendanHalley OK, thanks!

**Comment by BrendanHalley** [comment]
@ryansmith94 This one can be closed now.

**Comment by ryasmi** [comment]
Thanks @BrendanHalley 👍
