### ISSUE TITLE
Add test coverage for when config options are enabled

### ISSUE THREAD

**Issue by BrendanHalley** [davidpesce/moodle-logstore_xapi#273]
Currently no tests exist for custom options that add/change data in statements.

Currently the following need tests:

- send_mbox
- send_response_choices
- send_short_course_id
- send_course_and_module_idnumber
- send_username

**Comment by BrendanHalley** [comment]
@ryansmith94 can you please assign this to me.

**Comment by ryasmi** [comment]
Hey @trewq, thanks for this, just assigned you. We do have a couple of tests for `send_response_choices` (linked below). Those tests may serve as a useful example for the others.

- https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/tests/mod_quiz/attempt_submitted/multichoice_withchoices/test.php#L33
- https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/tests/mod_quiz/attempt_submitted/multichoiceset_withchoices/test.php#L33

**Comment by caperneoignis** [comment]
I'll be updating due to an issue I just listed where HTML formatting of the questions and response choices are being included in the string. So may update test to include this, in one or two of the response questions to ensure it is being properly handled.
