### ISSUE TITLE
Object of log in/log out is a course, rather than the site

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#28]
**Version**
Release 0.5.1 version 2015081002

**Steps to reproduce the bug**
Log in and look at the statement generated. 

**Expected behaviour**
The object of the statement is an activity representing the Moodle site, e.g.

```
"object": {
        "id": "http://localhost:8888/moodle/",
        "definition": {
            "name": {
                "en": "test"
            },
            "description": {
                "en": "test"
            },
            "type": "http://id.tincanapi.com/activitytype/site"
        },
        "objectType": "Activity"
    }
```

**Actual behaviour**
The object of the statement is a course on the site:

```
"object": {
        "id": "http://localhost:8888/moodle/course/view.php?id=1",
        "definition": {
            "name": {
                "en": "test"
            },
            "description": {
                "en": "A Moodle course"
            },
            "type": "http://lrs.learninglocker.net/define/type/moodle/course"
        },
        "objectType": "Activity"
    }
```

**Comment by jlowe64** [comment]
I think you're right, this is probably related behavior to your other bug. I'll get on this for this week!

**Comment by jlowe64** [comment]
@garemoko I'm running into a bit of a snag. I'm not sure where Moodle actually holds the site title other than the theme. I mean I think I could use the $PAGE global to get the theme settings, but that seems a bit hacky to me. Do you know of a reliable place I could get that bit of info?

**Comment by ryasmi** [comment]
What's the issue with 
1. A Moodle admin naming the course in Moodle?
2. Us changing the object definition type in the emitter?

**Comment by ryasmi** [comment]
To clarify Andrew, the very first course in Moodle does actually represent the site. This is the course given in the statement. When you navigate to that course, Moodle redirects you to the home page because it's kind of a pseudo course.

**Comment by garemoko** [comment]
@ryansmith94 gotcha. 

So in that case it's just the description, type and probably id that should change.

**Comment by jlowe64** [comment]
I've updated according to the remaining suggestions. I've also taken into account @ryansmith94's advice.  I will update this repo next week to update the libraries.
