### ISSUE TITLE
Does not work out of the box

### ISSUE THREAD

**Issue by mudrd8mz** [davidpesce/moodle-logstore_xapi#3]
When following the documented installation procedure, I end up with

```
Fatal error: require_once(): Failed opening required 'admin/tool/log/store/xapi/classes/log/../../vendor/autoload.php'
```

caused by the line

```
require_once __DIR__ . '/../../vendor/autoload.php';
```

in classes/log/store.php

**Comment by ryasmi** [comment]
At which step in the installation procedure does this issue occur?

**Comment by mudrd8mz** [comment]
The installation completes fine. The error is thrown when I visit Site administration ► Plugins ► Logging ► Manage log stores to enable the store. In any case, the line itself is clear - the plugin does not contain the required file.

**Comment by jlowe64** [comment]
I think maybe you got mixed up between the github/composer way and just downloading the zip file, and unzipping the "xapi.zip" and dropping that file into the appropriate place. Your error suggests that you didn't run composer to download and install the vendor folder.

I believe if you followed these instructions it will probably work: 
https://github.com/jlowe64/moodle-logstore-xapi/blob/master/docs/readme.md#adding-events

**Comment by jlowe64** [comment]
This could probably be explicitly cleared up and made to be more moodle community friendly.

**Comment by mudrd8mz** [comment]
Thing is, most Moodle plugins are supposed to work out of the box. Many sites admins do not have access to shell or are otherwise limited from using composer. If your plugin requires such a post-installation step (the docs you refer above looked like steps for developers, not end users btw), it will need to be put into a special category in the Moodle Plugins directory with certain limitations.

What you might want to consider is packaging your plugin together with dependencies into a single package that would be then installed. In which case, you will need to make sure that all the licenses of the dependencies are compatible with GPLv3 and as such can be distributed together in one package.

**Comment by jlowe64** [comment]
We actually did that but I believe Ryan ran into some issues with travis because of this very thing. I wanted to avoid it, but we may have to create another branch of the repo for just the "public" plugin. I'll have a think about it over the weekend.

**Comment by garemoko** [comment]
You could just make sure the zip files in the plugins database are 'pre-composed' or whatever the right term is. Obviously you can't do that now because you're not yet in the plugins database, but presumably that process will be complete soon.

**Comment by jlowe64** [comment]
The xapi.zip file is precisely that, a precomposed plugin that is drag-and-drop. I think, though, maybe the instructions should be a bit more clear.

**Comment by ryasmi** [comment]
The xapi.zip file should be a drag-and-drop install. There is absolutely no need to use Composer unless you're running our tests or trying to develop on the sub repos. @mudrd8mz @jlowe64 @garemoko

**Comment by ryasmi** [comment]
That file is definitely included in the [xapi.zip file](https://github.com/jlowe64/moodle-logstore-xapi/blob/master/xapi.zip?raw=true) so either you've installed some other way or something else is going on that we're unaware of. This has been tested on the most recent version of Moodle on Windows and Mac.

**Comment by mudrd8mz** [comment]
I must be missing something. How does xapi.zip get unzipped so that it can be actually used?

**Comment by jlowe64** [comment]
I have edited the instructions to be a bit more clear. 

Basically you will just go here: https://github.com/jlowe64/moodle-logstore_xapi/blob/master/docs/installation.md

If you click on the "download" link in item 1, it will download xapi.zip automatically, which will include everything needed to run. 

I assume you used github's built in .zip file, which will get you the repo that is meant for developers.

**Comment by ryasmi** [comment]
@mudrd8mz please remove your current attempt to install this plugin and retry using the slightly adjusted [instructions](https://github.com/jlowe64/moodle-logstore_xapi/blob/master/docs/installation.md). These instructions have been followed and the plugin has been successfully used by others, so this must be an issue with your particular installation.

> How does xapi.zip get unzipped so that it can be actually used?

Moodle should be unzipping it for you when you drag and drop it (step 3 in the instructions).

**Comment by mudrd8mz** [comment]
Ah, I think I know what's going on now. I encountered this issues while reviewing the plugin submitted into the [Moodle Plugins directory](https://moodle.org/plugins/). The ZIP plugin package uploaded there is what should be considered as primary distribution channel for your plugin (as that is what most people will download and install and eventually where all updates will be fetched). The ZIP uploaded there is not your xapi.zip, it is a snapshot of your whole Git repository.

If you want to have the plugin published in the Moodle Plugins directory, the ZIP released there is what counts.

**Comment by mudrd8mz** [comment]
... so you probably want to use "Upload a new version" at your plugin page in the plugins directory, providing the correct ZIP package. Please hide the previous (currently uploaded) version there and I can eventually remove it completely then.

**Comment by jlowe64** [comment]
Sounds like a plan!

**Comment by jlowe64** [comment]
I've uploaded a second version of nothing but the .zip file and hidden the old version which was more or less a copy of our repo. I'll leave this issue open until I get confirmation from you.

**Comment by mudrd8mz** [comment]
I can confirm the second uploaded version has correct format now. I removed the previously uploaded (now hidden) version. This issue can be closed now, thanks.
