### ISSUE TITLE
Add question submitted event

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#32]
**Motive**
Question level tracking is nice and sent by most good e-learning courses

**Result - Phase 1**
A standard question submitted event with low hanging fruit data about the question. 

**Result - Phase 2**
A question submitted event with custom behaviour for each question type and comprehensive statements for the multi-choice question type. 

**Result - Phase n**
Comprehensive statements for additional question type(s).

**Comment by jlowe64** [comment]
The intent is to get all events labelled student level interaction within Moodle, so this is definitely something that needs to happen. Also, it's well in line with my manager's tracking ideas.

**Comment by garemoko** [comment]
So, we have a situation here where a single event in moodle (submitting the assessment) triggers multiple statements (questions are submitted withe the assignment). I'm clear that there should be multiple events in the emitter, but do we put multiple events in the expander, or put all the data in one expander event and then have the translator divide that out into multiple xapi events? I'm leaning towards the later. PR incoming to illustrate the approach.

**Comment by ryasmi** [comment]
I'll look into this sometime tomorrow, too late in evening to wrap my head around haha.

**Comment by garemoko** [comment]
@ryansmith94 no problem. I can start work on the expander in the meantime.

**Comment by ryasmi** [comment]
Ok I so I think the translator should make multiple events not the Emitter. In that case, the Translator should always return an array of events which is looped through.

**Comment by garemoko** [comment]
Ok. Having had a second look at the "always an array" option it's not as big a change as I thought. It just means wrapping what's returned by each event into an array.

**Comment by jlowe64** [comment]
This seems to have been completed. I'm closing this!
