### ISSUE TITLE
Moodle doesn't provide a way to automatically create new plugin versions.

### ISSUE THREAD

**Issue by ryasmi** [davidpesce/moodle-logstore_xapi#325]
Until Moodle provides a way to automatically create new versions from Github releases we will no longer be publishing new versions in the plugin registry sorry, please track their progress on this via the [JIRA MDLSITE-1865 Ticket](https://tracker.moodle.org/browse/MDLSITE-1865?focusedCommentId=646150&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-646150).

We previously used a [package I made](https://github.com/ryansmith94/moodle-plugin-release) to automatically publish new versions, but since Moodle changed some parts of their login process that no longer works.

**Comment by caperneoignis** [comment]
That is annoying. Why can't they just make a function/class included in their CI plugin to run upon a successful completion and allow travisci secrets to be used to do tagging based on branch, and do the export to the Moodle plugin directory. I mean, seriously, that way all the changes are always updated in their plugin and it is seamless to plugin development.

**Comment by ryasmi** [comment]
Yeah very annoying, to do it manually, I have to wait for the CI tool to finish two builds (for master and then the release tag that's automatically made from the build on master) which usually takes around 10 minutes by the time we get to the front of Travis' queue. Then I have to wait for the zip to appear in Github's UI, download the zip, go to Moodle, login to get access to the dev functions of the plugin, go to the versions page, upload the zip, copy the release notes over from Github, and then fill out a form about the Moodle versions we support etc (remembering which ones we do support from previous versions), click a few more buttons. In total it takes about 15 minutes. We have 73 releases right now so that's over 18 hours of my life (`(73*15)/60`) spent on something that could be automated.

**Comment by ewallah** [comment]
Not yet tried, but this looks promising: https://github.com/ryansmith94/moodle-plugin-release

**Comment by jrchamp** [comment]
Moodle released a GitHub workflow to do this in June 2021:
https://github.com/moodlehq/moodle-plugin-release

**Comment by davidpesce** [comment]
Huzzah! Githubactions to the rescue. We're all set here.
