### ISSUE TITLE
Question: failed statements

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#33]
How does this plugin handle a loss of connection to the LRS? Do statements get dropped or are they saved for later? 

Is there a way of notifying an admin of the loss of LRS connection?

**Comment by jlowe64** [comment]
@garemoko I believe this is handled in this PR: https://github.com/jlowe64/moodle-logstore_xapi/pull/26/

Essentially if there is an error sending a batch of events, they will be retried. There is no constant connection with an LRS. It simply sends the events to the endpoint provided, and retries on failed. They are kept in the DB until they are successfully sent.

**Comment by garemoko** [comment]
@jlowe64 great! Thanks!

How about notifying an admin by email in the event of failures so they can go check the LRS?

**Comment by jlowe64** [comment]
It's my personal opinion, and @ryansmith94 can argue against me, that it would be slightly out of scope for this particular plugin, mostly on the grounds that I feel like that's a feature the LRS should provide the admin, not this plugin.

If I'm overruled we could totally look at it. I'm all about group consensus.

**Comment by ryasmi** [comment]
If the LRS is down for some reason, it may have no idea that requests were even sent to it. So I think something is needed here. It depends how the retries are implemented though.

**Comment by ryasmi** [comment]
With the current implementation of retries they will retry forever until they send.

**Comment by ryasmi** [comment]
I think it might be a good idea to notify someone if an event has been waiting more than X minutes or retried more than Y times. This is useful if:
1. The LRS is down for X minutes and the plugin user doesn't know
2. A statement is invalid (hence the plugin has a bug)
3. The LRS is incorrectly returning an error for a valid statement (hence the LRS has a bug)

**Comment by garemoko** [comment]
Thanks. This answers the question so I'm going to close this and open a feature request, stealing @ryansmith94's rationale plus adding my own.
