### ISSUE TITLE
\core\event\course_viewed in failed log

### ISSUE THREAD

**Issue by ryasmi** [davidpesce/moodle-logstore_xapi#343]
**Version**
- 3.17.0

**Steps to reproduce the bug**
1. Run the plugin with `\core\event\course_viewed` events in the xapi log.
2. Observe the failed log.

**Expected behaviour**
- Event should be emitted and removed from the xapi log.

**Actual behaviour**
- Event is not emitted, it is removed from the xapi log, but it is added to the failed log.

**Server information**
- Postgres on Ubuntu 14.04 LTS

**Comment by garemoko** [comment]
@ryansmith94 this may be fixed in the latest version. I'm currently running the version as shown in this commit: https://github.com/xAPI-vle/moodle-logstore_xapi/pull/340/commits/96cfa15079eac7be532823ff8c98516356b9d9ef

And the course view event works. 

This is xampp on Windows 10

**Comment by ryasmi** [comment]
Okay that's awesome, thanks @garemoko. I'll close this and reopen if the issue is found beyond v3.18.4.
