### ISSUE TITLE
Improve actor population

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#35]
The Tin Can launch module has some clever stuff to get the most appropriate actor identifier for actors. We should implement that here too. 

See https://github.com/garemoko/moodle-mod_tincanlaunch/blob/4b2959943e6d8740e3bc913af9637aabff0742cf/lib.php#L683-L731

Note: don't forget to apply this to instructors for the assignment graded event too.

**Comment by ryasmi** [comment]
Something similar could be implemented in the Expander, but it should not contain any xAPI specific information. Use the Translator to make something more xAPI specific from Moodle using the data from the Expander, then obviously use the Emitter to generate what's needed for the statement.

**Comment by garemoko** [comment]
More information: 
Currently the logstore uses the id property (the index of the user table) rather than username, which the launch plugin doesn't use in any mode. I dislike this approach because it'll cause problems if a user is removed and re-added for any reason e.g. via an HR system integration.

**Comment by ryasmi** [comment]
ID is used to maintain anonymity

**Comment by garemoko** [comment]
I can see some logic there, we also populate the actor.name property so it seems pointless and also causes problems if users get removed and re-added. 

I can see us having an anonymity setting that uses id and doesn't include the name, in which case people using the data would have to accept that they really didn't know who the user with a particular id is or even if its the same user each time. (I need to check - if you delete and re-add a user, do ids get recycled?)

**Comment by ryasmi** [comment]
Ah I forgot that the `actor.name` field was filled now, we should probably remove that by default and then include a setting to turn that on. Definitely should be off by default to maintain anonymity though.

**Comment by ryasmi** [comment]
I'm fairly certain that ID's don't get recycled. Recycling identifiers isn't really a good idea in the "Internet of Things".

**Comment by CinecaElearning** [comment]
Users never get completely deleted from the users moodle table, they are identified by a "deleted" tag. That's a plus on sending the ID. There is a con anyway: things can get complicated when users are exported form a moodle and imported to another, since another user on the new Moodle can already occupy the imported user ID. This is a know user export problem though.

**Comment by garemoko** [comment]
@CinecaElearning thanks for that insight. 

Regarding the con, I don't think that's a problem for us since presumably the other moodle where users are imported to sits at a different url and therefore has a different account homepage. Is that a fair assumption?

**Comment by jlowe64** [comment]
@garemoko I am assuming this is fixed by https://github.com/LearningLocker/Moodle-Log-Expander/pull/32 and /xAPI-vle/moodle-logstore_xapi/issues/60?

If so, we can close this down as I've merged the relevant PRs.

**Comment by garemoko** [comment]
No, this is something different and a little more work. The other thing was actor.name, this is the actor's id.

**Comment by ryasmi** [comment]
Will be resolved in #181.
