### ISSUE TITLE
Proper Moodle localization for verb display properties

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#36]
Currently verb displays are defined in the emitter so we'd have to 
- move verb display definitions to the translator
- have the translator look up /lang/en/logstore_xapi.php
- populate logstore_xapi.php, that with all the verb display properties

**Comment by ryasmi** [comment]
Seems reasonable. Agree that this should be something for the translator as this needs to be Moodle and xAPI specific.

**Comment by jlowe64** [comment]
Yes, I've been wanting this big time. Would help with localisation of the statements. +1 from me as well.

**Comment by davidpesce** [comment]
@garemoko this seems straight-forward in our rewrite, but I can't find any reference to xapi verbs/activities/etc that aren't english. Should we include both the word itself along with the URL to it?

Verb: attended
URL: http://activitystrea.ms/schema/1.0/accept

**Comment by garemoko** [comment]
@davidpesce the ids stay the same because the meaning is the same. We just add in additional languages to the display property's language map.

**Comment by davidpesce** [comment]
@ryansmith94 ahh, that makes sense. works for me!
