### ISSUE TITLE
score of 0 is omitted from statements

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#38]
This is a bug in TinCanPHP https://github.com/RusticiSoftware/TinCanPHP/issues/48

We'll need to update TinCanPHP version once that's resolved.

**Comment by jlowe64** [comment]
@garemoko can I get a timeframe on this? Just so I can get a frequency I should check in on it.

**Comment by garemoko** [comment]
@jlowe64 there's a [PR](https://github.com/RusticiSoftware/TinCanPHP/pull/49/) in, just waiting for some input from @brianjmiller. I don't know what his timescales are at the moment. You could subscribe to notifications on the PR.

I'll take another look at TinCanPHP tests to see if I can fathom that part out myself.

**Comment by jlowe64** [comment]
You know, I've seen that subscribe button and it just never registered what it was for. Thanks for pointing that out. I've subscribed, no pressure. :smile:

**Comment by jlowe64** [comment]
Noticed that this was fixed a day ago in a new release `0.40.0`. Will be putting this into the next version.

**Comment by jlowe64** [comment]
Closing this issue as I've changed it locally.. will be integrating in the next release.
