### ISSUE TITLE
'Include actions with these routes' setting does not work for  \mod_book\event\chapter_viewed using cron

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#390]
**Description**
I've been merrily testing using the new  \mod_book\event\chapter_viewed event and it's working fine. I've only just realized that on my local Moodle it's been configured not to track so in fact it should not have been working. (I guess off is the default for new events). 

![image](https://user-images.githubusercontent.com/1363163/50792718-d5681d80-12bd-11e9-9ba7-2464ad1316d2.png) 

**Version**
https://github.com/xAPI-vle/moodle-logstore_xapi/pull/367/commits/08e72bdecc52fe26a4208e08a8dc82d169f8b80b on development

**Steps to reproduce the bug**
1. Configure the plugin to use scheduled tasks with the  \mod_book\event\chapter_viewed event disabled
2. View a chapter in a book and confirm in the database that a \mod_book\event\chapter_viewed event has been triggered both in the standard and xapi logs
3. Run cron. 
4. Confirm in the LRS that the \mod_book\event\chapter_viewed event has been sent

**Expected behaviour**
The event should not be added to the xapi log table. 

**Actual behaviour**
The event is added to the table and is sent to the LRS.

**Comment by ryasmi** [comment]
That's really odd, yeah I think the default for new events is off which is pretty annoying. I don't know if there is a way to get around that.

In terms of it not actually disabling the event, I believe the [`is_event_ignored` function](https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/classes/log/store.php#L53) is meant to handle that, but I guess it might be getting skipped in which case it would just inserting everything into the xapi logstore table on [line 74](https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/classes/log/store.php#L74).

**Comment by BrendanHalley** [comment]
I've just done some testing and the checkboxes for disabling statements are working as expected. Logs aren't entered into the xapi logstore table when backgroundmode is on and not sent at all when it's disables - as expected.

I'll install an older version of the plugin and "upgrade" it at some point to see if I can replicate the issue.

**Comment by ryasmi** [comment]
Thanks @BrendanHalley 👍

**Comment by BrendanHalley** [comment]
Just completed an "upgrade" test.

- Installed v3.8.0
- Upgrade to v4.2.4
- `\core\event\course_module_completion_updated` & `\mod_book\event\chapter_viewed` unticked as expected (new events)
- Trigger both `\core\event\course_module_completion_updated` & `\mod_book\event\chapter_viewed` 
- No xAPI statement for both (as expected)
- Enable backgroundmode
- Trigger both `\core\event\course_module_completion_updated` & `\mod_book\event\chapter_viewed` 
- No xAPI statement for both (as expected)

@garemoko @ryansmith94 I'd say this one can be closed, I'm unable to replicate.

**Comment by ryasmi** [comment]
Ok will close this and reopen if needed. Thank you for investigating @BrendanHalley, really appreciated 👍

**Comment by garemoko** [comment]
Weird. Thanks for testing.
