### ISSUE TITLE
Not relevant strings

### ISSUE THREAD

**Issue by mudrd8mz** [davidpesce/moodle-logstore_xapi#4]
I found strings like modulename, modulenameplural, modulename_help, xapiname, xapiname_help and possibly others that do not seem to be valid for the logstore plugin type.

**Comment by ryasmi** [comment]
Hi @mudrd8mz, can you please be more specific as to where you're seeing these strings and why you believe they're not valid?

**Comment by jlowe64** [comment]
I believe he means it's in the lang file. I can clean these up as they are stragglers from a previous version.

**Comment by mudrd8mz** [comment]
Yes what @jlowe64 says, they are defined in the lang file and it seems like a wrong template was used for this file.

**Comment by jlowe64** [comment]
Fixed with commit https://github.com/jlowe64/moodle-logstore-xapi/commit/b515f15a25570d362e9f6533d1bebbafdd5edb73

Although I did leave one string as I will probably use it in the near future.
