### ISSUE TITLE
Failed transform for event when userid=0

### ISSUE THREAD

**Issue by ngarafol** [davidpesce/moodle-logstore_xapi#413]
**Description**
Trying to emit historical data to LRS

**Version**
- master at v4.2.0 on 2019010801

**Steps to reproduce the bug**
1. Try to emit historical data to LRS

**Expected behaviour**
- Data transformed to statements in LRS

**Actual behaviour**
- Transform failing due to logs having userid=0

**Server information**
- pgsql with manual auth (testing server)

**Client information**
- OS: ubuntu 18
- Browser: latest chrome

**Additional information**
- For testing purposes I copied 1mil lines from standard_log to logstore_xapi table in order to feed historical data to LRS, just as a test. Transform fails on records with userid being set to 0, and in those 1mil lines there are around 129k lines with userid=0.

What is the proper solution here? Delete all lines with userid=0 ? Implement some code

log from emit to lrs:

`Execute scheduled task: Emit records to LRS (logstore_xapi\task\emit_task)
... started 08:30:09. Current memory use 10.9MB.
Failed transform for event id #37146146: user not found.
line 89 of /admin/tool/log/store/xapi/classes/log/store.php: call to debugging()
line 46 of /admin/tool/log/store/xapi/src/transformer/handler.php: call to logstore_xapi\log\store->logstore_xapi\log\{closure}()
line ? of unknownfile: call to src\transformer\{closure}()
line 57 of /admin/tool/log/store/xapi/src/transformer/handler.php: call to array_map()
line 35 of /admin/tool/log/store/xapi/src/handler.php: call to src\transformer\handler()
line 121 of /admin/tool/log/store/xapi/classes/log/store.php: call to src\handler()
line 96 of /admin/tool/log/store/xapi/classes/task/emit_task.php: call to logstore_xapi\log\store->process_events()
line 104 of /lib/cronlib.php: call to logstore_xapi\task\emit_task->execute()
line 292 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
line 91 of /admin/tool/task/schedule_task.php: call to cron_run_single_task()
#0 /var/www/html/admin/tool/log/store/xapi/src/transformer/repos/Repository.php(55): src\transformer\repos\MoodleRepository->read_record('user', Array)
#1 /var/www/html/admin/tool/log/store/xapi/src/transformer/events/core/course_viewed.php(25): src\transformer\repos\Repository->read_record_by_id('user', '0')
#2 /var/www/html/admin/tool/log/store/xapi/src/transformer/handler.php(32): src\transformer\events\core\course_viewed(Array, Object(stdClass))
#3 [internal function]: src\transformer\{closure}(Object(stdClass))
#4 /var/www/html/admin/tool/log/store/xapi/src/transformer/handler.php(57): array_map(Object(Closure), Array)
#5 /var/www/html/admin/tool/log/store/xapi/src/handler.php(35): src\transformer\handler(Array, Array)
#6 /var/www/html/admin/tool/log/store/xapi/classes/log/store.php(121): src\handler(Array, Array)
#7 /var/www/html/admin/tool/log/store/xapi/classes/task/emit_task.php(96): logstore_xapi\log\store->process_events(Array)
#8 /var/www/html/lib/cronlib.php(104): logstore_xapi\task\emit_task->execute()
#9 /var/www/html/lib/cronlib.php(292): cron_run_inner_scheduled_task(Object(logstore_xapi\task\emit_task))
#10 /var/www/html/admin/tool/task/schedule_task.php(91): cron_run_single_task(Object(logstore_xapi\task\emit_task))
#11 {main}
line 89 of /admin/tool/log/store/xapi/classes/log/store.php: call to debugging()
line 47 of /admin/tool/log/store/xapi/src/transformer/handler.php: call to logstore_xapi\log\store->logstore_xapi\log\{closure}()
line ? of unknownfile: call to src\transformer\{closure}()
line 57 of /admin/tool/log/store/xapi/src/transformer/handler.php: call to array_map()
line 35 of /admin/tool/log/store/xapi/src/handler.php: call to src\transformer\handler()
line 121 of /admin/tool/log/store/xapi/classes/log/store.php: call to src\handler()
line 96 of /admin/tool/log/store/xapi/classes/task/emit_task.php: call to logstore_xapi\log\store->process_events()
line 104 of /lib/cronlib.php: call to logstore_xapi\task\emit_task->execute()
line 292 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
line 91 of /admin/tool/task/schedule_task.php: call to cron_run_single_task()`

line from logstore table:

`moodle=# select * from mdl_logstore_standard_log where id=37146146;
    id    |         eventname         | component | action | target | objecttable | objectid | crud | edulevel | contextid | contextlevel | contextinstanceid | userid | courseid | relateduserid | anonymous | other
 | timecreated | origin |       ip       | realuserid 
----------+---------------------------+-----------+--------+--------+-------------+----------+------+----------+-----------+--------------+-------------------+--------+----------+---------------+-----------+------
-+-------------+--------+----------------+------------
 37146146 | \core\event\course_viewed | core      | viewed | course |             |          | r    |        2 |         2 |           50 |                 1 |      0 |        1 |               |         0 | N;   
 |  1503049410 | web    | <ip address removed> |           
(1 row)
`

EDIT:
Think its only a "warning" as actual events get deleted from logstore_xapi_log table, meaning they cant be transformed as there is no userid, so they get removed anyway as they are "processed".

**Comment by garemoko** [comment]
A few notes:

User 0 is not the guest account or the admin (guest is user 1). It means there is no user at all and appears to happen if either there is no user (action performed by a scheduled task) or due to some sort of bug or database issue e.g. when restoring from a backup. So really there's no way for the plugin to correctly handle that data, it has to be thrown out as bad data.

The line of code throwing the error is here: https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/src/transformer/events/core/course_viewed.php#L25

We already have an issue around better errors when database record not found: https://github.com/xAPI-vle/moodle-logstore_xapi/issues/386 I would argue that that issue is the best solution to implement here.

**Comment by ryasmi** [comment]
Haha thanks @garemoko I was literally just replying and your response popped up, good live updating from Github there. I think you're right, the plugin is correct in throwing this out and #386 is the best solution here.

**Comment by ryasmi** [comment]
Since the plugin is behaving as expected @ngarafol, I'm going to close this, but please feel free to follow #386.
