### ISSUE TITLE
Send multiple statements in one request

### ISSUE THREAD

**Issue by micaherne** [davidpesce/moodle-logstore_xapi#43]
**Motive**
Now that the plugin supports sending statements in the background (https://github.com/jlowe64/moodle-logstore_xapi/pull/26), it is very inefficient to send each statement in its own HTTP request. Sending multiple statements in a single API call is supported by the xAPI spec, Learning Locker and the rusticisoftware library the plugin is using.

**Result**
The enhancement would be to either:
1. Introduce a "bulk mode" which could be switched on by systems administrators in system settings. This would have a "bulk size" setting which would determine the maximum number of statements to be sent at once.
2. Introduce a "bulk size" setting and always send multiple statements. Default to 1 for compatibility with existing functionality.

**Additional information**
I'd be quite happy to code this myself, but need some advice. Implementation would require simultaneous patches to both logstore-xapi and xAPI-Recipe-Emitter and I'm not sure how this would work. Also, the minimal change to xAPI-Recipe-Emitter's Controller class would mean passing an array of events, which are already arrays, so this could be very confusing. It might be better if the creation of statements and emitting them could be separated in xAPI-Recipe-Emitter, but I'm not sure if this would be acceptable. If you can give me some ideas about this I'll try to sort out an implementation and pull request.

Cheers, Michael

**Comment by garemoko** [comment]
+1

This is even more needed once we are sending questions per quiz question. 

I think the approach i'd take is to make the following change to line 24 of Controller.php in the emitter:

```
$this->store->queueStatement(new TinCanStatement($event));
```

Then do the rest of the changes in logstore-xapi, possibly as a new component of the plugin that handles queuing, sending and re-trying statements. 

An alternative approach to batching statements up to a bulk size is to send every X minutes/seconds. That way you don't have statements waiting for potentially long periods of time to make up the batch size. Batching should be the default (and in my opinion only) behavior.

**Comment by garemoko** [comment]
Possibly the emitter could be renamed "statement-izer" or something. :-P

**Comment by jlowe64** [comment]
Fantastic suggestion @micaherne. 

As far as simultaneous patches, I could time the releases so that these features go out at the same time. That will be no problem at all.

**Comment by ryasmi** [comment]
I think the best solution here, is to enable the controllers in all three repositories to receive multiple events. I think it's important that the function of emitting the statements to the LRS remains in the Emitter so that this function is maintained if and when that repository is used elsewhere. It also avoids leaking abstractions (such as the use of TinCanPHP by the Emitter).

**Comment by garemoko** [comment]
@ryansmith94 @micaherne what if the emitter continued to receive single events and then was responsible for queuing and batching? 

If the emitter has to receive multiple events, then the queuing needs to be done either by the expander or the translator, with a lot of complexity added everywhere. If the emitter receives a stream of single events  and then batches them, it's a lot more compartmentalized. I don't think it's less efficient either as the HTTP requests aren't done until we get to the emitter anyway. 

Perhaps something like this. The top row is a quiz with 3 questions. The batcher might be part of the emitter or a separate component. 
![image](https://cloud.githubusercontent.com/assets/1363163/12553324/b574b494-c36e-11e5-9651-d7827b19bb08.png)

**Comment by ryasmi** [comment]
In the solution I'm thinking of, the only change is to the Controllers.

**Comment by garemoko** [comment]
@ryansmith94 I think I understand now. So you'd get rid of the foreaches in process_events in the store and pass an array of the events through the controllers? 

I like that.

**Comment by ryasmi** [comment]
Yeah that's right @garemoko. Give more control to the Controllers.

**Comment by micaherne** [comment]
Sounds good to me too. The implementation I'd been messing around with had process_events() building up an array of "translator event" data, then flushing it to a new createEvents() method on XREmitter\Repository once the batch size was reached (and at the end of the method). It was kind of hacky, though, and adding array support to all controllers sounds much better.

If all controllers were updated to support arrays, where would the actual control of the batch sizes be done? The emitter controller seems like the best place to me - maybe we could pass the maximum batch size as a constructor parameter? That would make the patch to logstore_xapi just a case of adding a Moodle setting and passing its value when connecting to the xapi repository in process_events().

**Comment by garemoko** [comment]
@micaherne You could control the batch sizes (or time delay) by controlling the batches that you send to process_events in the first place.

**Comment by micaherne** [comment]
@garemoko That makes sense. So if I create a patch for the Moodle plugin, can someone else add array support to the libraries?

**Comment by ryasmi** [comment]
+1 for Andrew's batch size solution.

**Comment by garemoko** [comment]
@micaherne I'd be happy to add it to my todo list but I'm not sure exactly when I'd get to it. If I didn't do it this week, i wouldn't do it next week either. 

That said, I don't think it'd be a big job.

**Comment by garemoko** [comment]
@micaherne if you want to address this yourself, below is my first bash at code for this. The time consuming bit is making sure it works and updating the tests and docs but hopefully this will set you on the right path. 

In moodle-logstore-xapi/classes/log/store.php

``` php
    public function process_events(array $events) {

        // Initializes required services.
        $xapicontroller = new xapi_controller($this->connect_xapi_repository());
        $moodlecontroller = new moodle_controller($this->connect_moodle_repository());
        $translatorcontroller = new translator_controller();

        // Emits events to other APIs.
        foreach ($events as $index => $event) {
            $events[$index] = (array) $event;
        }

        $this->error_log('');
        $this->error_log_value('events', $events);
        $moodleevents = $moodlecontroller->createEvents($events);
        $this->error_log_value('moodleevent', $moodleevents);
        $translatorevents = $translatorcontroller->createEvents($moodleevents);
        $this->error_log_value('translatorevents', $translatorevents);
        $xapievents = $xapicontroller->createEvents($translatorevents);
        $this->error_log_value('xapievents', $xapievents);
    }
```

In the expander controller:

``` php
    /**
     * Creates a new event.
     * @param [String => Mixed] $events
     * @return [String => Mixed]
     */
    public function createEvents(array $events) {
        $results = [];
        foreach ($events as $index => $opts) {
            $route = isset($opts['eventname']) ? $opts['eventname'] : '';
            if (isset(static::$routes[$route]) && ($opts['userid'] > 0 || $opts['relateduserid'] > 0)) {
                $event = '\LogExpander\Events\\'.static::$routes[$route];
                array_push($results , (new $event($this->repo))->read($opts));
            } 
        }
        return $results;
    }
```

In the translator controller:

``` php
    /**
     * Creates a new event.
     * @param [String => Mixed] $events
     * @return [String => Mixed]
     */
    public function createEvents(array $events) {
        $results = [];
        foreach ($events as $index => $opts) {
            $route = isset($opts['event']['eventname']) ? $opts['event']['eventname'] : '';
            if (isset(static::$routes[$route])) {
                    $route_events = is_array(static::$routes[$route]) ? static::$routes[$route] : [static::$routes[$route]];
                    foreach ($route_events as $route_event) {
                    try {
                        $event = '\MXTranslator\Events\\'.$route_event;
                        foreach ((new $event())->read($opts) as $index => $result) {
                             array_push($results, $result);
                         }
                    } catch (UnnecessaryEvent $ex) {}
                }
            } 
        }
        return $results;
    }
```

~~In the emitter controller:~~ Edit: don't use this one, see below!

``` php
    /**
     * Creates a new event.
     * @param [String => Mixed] $events
     * @return [String => Mixed]
     */
    public function createEvents(array $events) {
        $results = [];
        foreach ($events as $index => $opts) {
            $route = isset($opts['recipe']) ? $opts['recipe'] : '';
            if (isset(static::$routes[$route])) {
                $event = '\XREmitter\Events\\'.static::$routes[$route];
                $service = new $event($this->repo);
                $opts['context_lang'] = $opts['context_lang'] ?: 'en';
                $statement = $service->read($opts);
                array_push($results, $service->create($statement));
            } 
        }
        return $results;
    }
```

I've tested this code on my Moodle and it works (the statements are still sent; I didn't check if they are actually batching or not). I didn't check in batching mode.

**Comment by ryasmi** [comment]
Nice work @garemoko. From what I can see that's doing everything we need except batching at the end. 
- The Emitter Controller needs a new method called `send` which takes an array of statements and returns an array of responses using `$this->repo->createEvents($statements)`.
- The Emitter Repository needs a new method called `createEvents` which sends a batch of statements and returns an array of responses.
- After that the Emitter Controller's `createEvents` method should look like...

``` php
   /**
     * Creates a new event.
     * @param [String => Mixed] $events
     * @return [String => Mixed]
     */
    public function createEvents(array $events) {
        $statements = [];
        foreach ($events as $index => $opts) {
            $route = isset($opts['recipe']) ? $opts['recipe'] : '';
            if (isset(static::$routes[$route])) {
                $event = '\XREmitter\Events\\'.static::$routes[$route];
                $service = new $event($this->repo);
                $opts['context_lang'] = $opts['context_lang'] ?: 'en';
                array_push($statements, $service->read($opts));
            } 
        }
        return $this->send($statements);
    }
```

**Comment by garemoko** [comment]
@ryansmith94 good catch, so create events in the emitter repository looks like:

```
    /**
     * Creates an event in the store.
     * @param [string => mixed] $statements
     * @return [string => mixed]
     */
    public function createEvents(array $statements) {
        $this->store->saveStatements($statements);
        return $statements;
    }
```

and the two new/editted methods in the controller look like:

```
   /**
     * Creates a new event.
     * @param [String => Mixed] $events
     * @return [String => Mixed]
     */
    public function createEvents(array $events) {
        $statements = [];
        foreach ($events as $index => $opts) {
            $route = isset($opts['recipe']) ? $opts['recipe'] : '';
            if (isset(static::$routes[$route])) {
                $event = '\XREmitter\Events\\'.static::$routes[$route];
                $service = new $event($this->repo);
                $opts['context_lang'] = $opts['context_lang'] ?: 'en';
                array_push($statements, $service->read($opts));
            } 
        }
        return $this->repo->createEvents($statements);
    }

```

~~That works and my logs suggest that multiple statements are indeed being sent together. I can't help but think that the send method is a little unnecessary though?~~

**Comment by ryasmi** [comment]
Looks good @garemoko :+1: 

> I can't help but think that the send method is a little unnecessary though?

It is a little bit, I suppose we can remove it.

**Comment by garemoko** [comment]
Edited the above to reflect

**Comment by ryasmi** [comment]
:+1:

**Comment by micaherne** [comment]
Wow, thanks @garemoko! I'll try that out and see how it goes.

**Comment by micaherne** [comment]
OK, I tried that code and it's working well. The unit tests for the three library projects are passing, and with a slight tweak to pass an array instead of an object, the plugin tests are mostly passing. There are three failures, which are just tests of library versions, and three errors, which are all "Undefined index: grade_items". 

I'm not convinced the errors are related to the new code, although I haven't had time to try running the tests on the master branch of the plugin using the master branches of the libraries.

I think we still need to be able to control the size of the batches being sent from within Moodle, but it should be a relatively simple patch and I'll have a look at it tomorrow.

**Comment by garemoko** [comment]
@micaherne grade_items is something I added recently and that we haven't yet worked out plugin tests for. Feel free to fix it though if you like ;-p

**Comment by ryasmi** [comment]
Good stuff @micaherne! :smile:

**Comment by micaherne** [comment]
Hi guys, I've created pull requests for these changes. Hopefully they'll make sense! A few things:
- The change to the translator code breaks backwards compatibility with the existing createEvents() method. It looks as if this was only renamed a couple of weeks ago, so I wasn't sure if it would be an issue or not. I can't find any code that calls this method, but I'm not sure where else the library is being used.
- I realised that passing batches into process_events() doesn't quite work, because in background mode every event raised by Moodle since the last run is passed into process_events() but only a small (and unpredictable) fraction of these actually ends up as statements to be sent to the LRS. There's probably something to be said for processing the events in batches to avoid high RAM use but that doesn't seem as important as being able to send the statements to the LRS efficiently.
- Out of interest, why is the library split across 3 Github projects? I found it a real nightmare to work with, and have been racking my brains trying to work out what the benefits might be!

**Comment by garemoko** [comment]
@micaherne I don't understand point 2 but would like to. Please can you add more explanation to what your initial approach is and why that's failing? 

I have no answer to point 3 :-)

**Comment by micaherne** [comment]
@garemoko Sorry, it's a bit garbled but I'll try to explain. This is purely to do with background mode - when the statements are being sent in user time there's not a lot of point limiting the batch size as there probably won't be more than a couple per request. 

My initial attempt in emit_task::execute() was to get all the events that have been stored since the last time the task ran and to split these into batches of whatever maximum size I had set (say 1000) and send these to process_events(). However, I hadn't taken into account that there are a lot of events that no statements are generated for, so out of that 1000 you could end up with (for example) only 100 statements being sent to the LRS. 

The idea of the maximum batch size was to control the number of statements that would be sent to the LRS in one request so this doesn't work very well. Obviously, it does limit the number but it's very inefficient. The intention was that, for example, if you had 25010 statements and a max of 1000, then they would be sent to the LRS in 26 requests - 25 batches of 1000 and one of 10. Using the initial approach, it's completely unpredictable how many requests to the LRS you'd end up making.

I realise this all seems like hair splitting, but I'm running a big Moodle installation that is generating hundreds of events per minute so it's important to be able to make the scheduled task run as efficiently as possible.

Hope this makes more sense.

**Comment by garemoko** [comment]
@micaherne perfect sense, thanks. I actually thought of a similar problem with the initial approach this morning so was pleasantly surprised to see you'd dodged the issue when I reviewed the PR. See https://github.com/jlowe64/moodle-logstore_xapi/pull/44#discussion_r50974940.

**Comment by jlowe64** [comment]
@micaherne thanks for explaining that, now it makes a lot more sense. 

I, sadly, can't address your #3 fully, maybe @ryansmith94 could when he gets time? My original and very rudimentary and poor design of the plugin had everything all in one. My idea from what I've gathered from this iteration is that the 3 parts exist because 2 of the libraries are being used for other plugins with other LMSes and only one is Moodle specific. 

I think in [this](https://github.com/jlowe64/moodle-logstore_xapi/blob/master/docs/design.md) document, it could be explained a little better to be clearer the intent of the 3 libraries. 

Either way, I think if it becomes frustrating/difficult to work between the 4 repos, then we should probably think on some ways to make debugging a little better.

**Comment by ryasmi** [comment]
To address the three points in @micaherne's [earlier comment](#issuecomment-175673950).
1. This is fine. However the break in backwards compatibility should bump the next version of the plugin components to v1.0.0 @jlowe64.
2. From your [most recent comment](#issuecomment-175695867) @micaherne, it seems we should have two settings, one that determines how many events to process at a time and one that determines how many statements to batch to the LRS.
3. As @jlowe64 said, it is split into 3 parts because some of the parts will be used elsewhere and in some installations some of the parts may be replaced. However, I am aware of how much pain this is causing, so I have been thinking about other ways to do this. Once I've collected my thoughts on the matter I'll raise a new issue for it.

**Comment by garemoko** [comment]
I'm generally against settings where they can be avoided, especially in Moodle where there are too many already. Is batching processing events really a performance gain and if so, can we pick a sensible number and just use that?

**Comment by ryasmi** [comment]
I don't think the setting matters when it has a sensible default.

**Comment by micaherne** [comment]
I did think about getting the events out of the database in batches, but couldn't see a simple way to do it that wouldn't conflict with the way I was hoping the batching of statements would work. The main issue is again the fact that you don't know until the events have been through the translator how many statements you will end up with. 

So, for example:
- max statement batch size is 30
- max event processing size is 100
- each batch of events results in 31 statements (I realise this is unrealistic, but it's just for illustration!)

If you process 1000 events, this will result in 20 calls to the LRS compared to 11 when you process all the events at once.

That said, it's maybe not necessary for the sending of statements to be maximally efficient, so it might be worth considering a compromise to avoid uncontrolled use of RAM. To be honest, I don't have a feel for whether the RAM use would actually be an issue, even with large numbers of events. Even if it is it might be better just to use raise_memory_limit() like some other Moodle bulk processing tasks do rather than to try to batch them.

**Comment by ryasmi** [comment]
Should this be closed @jlowe64? I've looked at it properly, but judging from the title I think this is done now.

**Comment by jlowe64** [comment]
It's been done. Thanks for pointing this out. I meant to close this when I did the release!

**Comment by ryasmi** [comment]
No worries @jlowe64, thanks for the confirmation.
