### ISSUE TITLE
misleading wording in mtrace message

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#454]
The message "X event(s) have been successfully sent to the LRS" is traced when running the cron task. This is misleading because many events are successfully processed but actually do not send any data to the LRS (i.e. stuff that Moodle logs that we haven't yet implemented tracking for). 

Suggested new wording: "X event(s) have been successfully processed"

For unsuccessfully processed events, "X event(s) have failed to send to the LRS" is probably accurate, since I don't think we can fail on events that do not attempt to send data to the LRS.

**Comment by ryasmi** [comment]
Yeah good catch, sorry I didn't reply sooner.

**Comment by davidpesce** [comment]
Fixed in PR #627
