### ISSUE TITLE
zip bash script should remove any gitignore files

### ISSUE THREAD

**Issue by jlowe64** [davidpesce/moodle-logstore_xapi#48]
**Version**
Current master branch, version 1.0.0

**Steps to reproduce the bug**
Install on site that uses the xapi plugin and also uses git as version control.

**Expected behaviour**
Plugin should not interfere with existing git repos.

**Actual behaviour**
Plugin interferes with existing git repos by not including the /vendor folder. 

**Additional information**
The fix should be that upon zip creation, .gitignore should be removed from the version of the plugin intended for installing in moodle installs.

**Comment by ryasmi** [comment]
Good find.

**Comment by jlowe64** [comment]
Completed with: https://github.com/jlowe64/moodle-logstore_xapi/commit/58a17c7bc70971424f8122f2e47137e8ae0f0b1e
