### ISSUE TITLE
Listen for custom Moodle Events

### ISSUE THREAD

**Issue by Straafe** [davidpesce/moodle-logstore_xapi#49]
Hello,

I recently installed your plugin to my test Moodle server and was amazed by the functionality right out of the box! I made my own custom Moodle event, which does fire and is viewable in the Moodle log, and now need to add the php files in order to get the plugin to listen for it and to fire a statement over to my LRS and I am haveing issues.

I can't seem to get a statement sent over to my LRS from my custom Moodle event. It is a very simple event, so I basically copies the files from another simple event that was pre-existing, the "ScormLaunched" event. From there, I simply changed the recipe/event/class names to my new moodle event, which is "course_mistake" in moodle and "CourseMistake" for your plugin.

I added "'\core\event\course_mistake' => 'CourseMistake'," and "'course_mistake' => 'CourseMistake'" to the Controller.php files as well. 

Any ideas on pointing me in the right direction as to why my statements are not firing?

**Comment by ryasmi** [comment]
Hey @Straafe, it's good to hear your experience with the plugin. It sounds like you've made the right changes. Could you please copy the changes you have made into a new comment so that we can help you further?

**Comment by Straafe** [comment]
Thanks for responding so quickly. Since I last posted, I remodeled it after the log in event, which appears to only use the translator and emitter since it is a simple test to see if I can get custom events working. Here's what I've done:

CourseMistake.php in emitter's src/events folder:

```
<?php namespace XREmitter\Events;

class CourseMistake extends Event {
    protected static $verb_display = [
        'en' => 'made a boo boo'
    ];

    /**
     * Reads data for an event.
     * @param [String => Mixed] $opts
     * @return [String => Mixed]
     * @override Event
     */
    public function read(array $opts) {
        return array_merge(parent::read($opts), [
            'verb' => [
                'id' => 'http://www.merriam-webster.com/dictionary/mistake',
                'display' => $this->readVerbDisplay($opts),
            ],
            'object' => $this->readApp($opts),
        ]);
    }
}
```

CourseMistake.php in Translator's src/events folder:

```
<?php namespace MXTranslator\Events;

class CourseMistake extends Event {
    /**
     * Reads data for an event.
     * @param [String => Mixed] $opts
     * @return [String => Mixed]
     * @override Event
     */
    public function read(array $opts) {
        return [array_merge(parent::read($opts)[0], [
            'recipe' => 'course_mistake',
        ])];
    }
}
```

Added line to Controller.php in translator's src folder:

`'\core\event\course_mistake' => 'CourseMistake',`

Added line to Controller.php in emitter's src folder:

`'course_mistake' => 'CourseMistake',`

My custom event for Moodle is working and visible in the log. It's class/php name is "course_mistake" and you can see it in the log:

![log](https://cloud.githubusercontent.com/assets/7477619/13512188/03e95858-e14e-11e5-893e-2ef53d7631ae.jpg)

Not sure where I went wrong.

**Comment by ryasmi** [comment]
You're welcome @Straafe :smile: From what I can see you've actually done everything right so far (good work :+1:).

The only thing that's missing is an update to the Controller.php file in the Expander's src folder. I think you should be able to reuse the Expander's Event class to get a quick test going, so you'll need to add `'\core\event\course_mistake' => 'Event'` to the routes.

Let me know how that goes :+1:

**Comment by Straafe** [comment]
D'oh! I can't believe I left that out! Custom event is firing and LRS is picking it up! Thank you very much. 

I've never been so excited to "FAIL MISERABLY" and to "make a boo boo" in my life, ahaha.

LRS statement viewer:

![lrslog](https://cloud.githubusercontent.com/assets/7477619/13512506/e7ae40f2-e14f-11e5-818f-4ae2a84dc3be.jpg)

**Comment by ryasmi** [comment]
No worries, it's easy to make a mistake when the components aren't explicitly linked, that'll be something for us to work on in the future.

Awesome! You're very welcome :smile:

Haha good stuff :+1:
