### ISSUE TITLE
Way to have transformer ignore an event

### ISSUE THREAD

**Issue by creighton** [davidpesce/moodle-logstore_xapi#493]
This is a question really, not a bug. I want to modify course_module_completion_updated to only send a statement if `completionstate` is 1. If I return 0, false or [], I get errors farther up the stack because it's expecting an array with at least one statement. Is there a way to do this within the transformer class or does this require more modifications?

**Comment by BrendanHalley** [comment]
@creighton If I were tackling this issue I'd start by looking at the `is_event_ignored` function in `classes/log/store.php`. You should be able to stop the processing of a log event completely with conditions in this function.

**Comment by creighton** [comment]
Hey thanks for the info. I plugged in a check for the event and condition in that function and it seems to be working like a champ. 

Appreciate your help @BrendanHalley
