### ISSUE TITLE
Add more forum events

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#50]
**Motive**
It would be interesting to report on posts created and replies made alongside post views. 

**Result**
Add create post and reply to post events. 

**Additional information**
I haven't checked whether or not the events are available in Moodle yet.

**Comment by jlowe64** [comment]
I have the following events on my list to be done for the next release:

```
\mod_forum\event\post_created
\mod_forum\event\subscription_created
\mod_forum\event\subscription_deleted
\mod_forum\event\discussion_subscription_created
\mod_forum\event\discussion_subscription_deleted
```

Is this what you were thinking of?

**Comment by garemoko** [comment]
It looks like the two I'm talking about are:

\mod_forum\event\discussion_created (start a new discussion)
\mod_forum\event\post_created (reply to a discussion)

We already track discussion views:
\mod_forum\event\discussion_viewed

I'm less worried about subscriptions, but they aren't totally uninteresting.

**Comment by jlowe64** [comment]
To be honest, those were more my manager's interest. I think I could replace the subs with your two and it'd probably pull in a lot more interesting data than the subs.

**Comment by jlowe64** [comment]
And furthermore, I doubt people actually subscribe to posts actively as they respond.

**Comment by RikGr** [comment]
Hello, 

I tried to add a post_created event myself but I am afraid my PHP skills are not sufficient. Do you know when these events will be added? Can I do more suggestions for events?

**Comment by ryasmi** [comment]
Hi @RikGr, no worries. Not too sure when they'll be added right now, @davidpesce and I are pretty busy at the moment. Yeah you can certainly suggest new events.

**Comment by ryasmi** [comment]
If we make progress here let's target the following events first, then close this issue in favour of separate issues per event.

- `\mod_forum\event\discussion_created` (start a new discussion)
- `\mod_forum\event\post_created` (reply to a discussion)

**Comment by davidpesce** [comment]
Completed in PR #616
