### ISSUE TITLE
Composer removing support for uppercase characters in package names

### ISSUE THREAD

**Issue by Tawmu** [davidpesce/moodle-logstore_xapi#504]
**Description**
- Composer deprecating use of upper case characters in package names in version 2.0.

**Version**
- master at 2d68f13 on 2018082100 

**Steps to reproduce the bug**
1. Use Composer to manage a Moodle installation
2. Add xAPI has a required package
3. run `composer install`

**Expected behaviour**
- Composer should install Moodle and all plugins with no warnings or errors.

**Actual behaviour**
- Composer builds the package but gives a warning about deprecating upper case characters in package names:
`Deprecation warning: require.xAPI-vle/moodle-logstore-xapi is invalid, it should not contain uppercase characters. Please use xapi-vle/moodle-logstore-xapi instead. Make sure you fix this as Composer 2.0 will error.`

**Server information**
- MySQL 5.7

**Client information**
- OS: Alpine Linux, Mac, Windows
- Browser: N/A

**Additional information**
- Doesn't currently break installation but may do in future.

**Comment by ryasmi** [comment]
Thanks @Tawmu, didn't actually know people were installing this plugin in that way.

**Comment by davidpesce** [comment]
Fixed in PR #615
