### ISSUE TITLE
Add feedback module events

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#51]
**Motive**
The feedback module is disabled by default, but gets a lot of use in corporate settings for course evaluations. 

**Result**
Add tracking for the following events and data:

Events:
\mod_feedback\event\course_module_viewed
\mod_feedback\event\response_submitted

Data/statements for submission
-> question text
-> question response
-> question options (for multichoice and multichoicerated) 
-> question score (for multichoicerated)
-> feedback completion and min/raw/max/scaled score (if feedback contains multichoicerated)

**Additional information**
The presentation field of the mdl_feedback_item table contains most of the juicy data. Separated by pipes and hashes. This will need to be processed. 

E.g.

```
r>>>>>0#### foo|1#### bar
```

This means two options, foo and bar, with a score rating of 0 and 1 respectively.

**Comment by garemoko** [comment]
I'm not planning on making new events in the xapi recipe emitter, but instead I want to try and and re-use the existing QuestionAnswered and AttemptCompleted events. This will require some tweaks to those events, for example handling null scores as the feedback does not always have a score.

**Comment by ryasmi** [comment]
Ok @garemoko that sounds like a good idea, obviously if it doesn't work out it's pretty easy to extend the existing events and add them to the controller.

**Comment by garemoko** [comment]
Closing because this is done! \0/

**Comment by jlowe64** [comment]
And as soon as I'm not buried under pointless meetings I'll get to merging into a release in the main plugin. lol
