### ISSUE TITLE
Add facetoface module events

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#52]
**Motive**
The face to face module is a non-core module used to manage attendance at face to face events. 

**Result**
Tracking for the following events:
- \mod_facetoface\event\signup_success
- \mod_facetoface\event\cancel_booking
- \mod_facetoface\event\take_attendance

The focus of tracking for this last event should be 'learner attended event' rather than 'trainer marked attendance'. 

Other possible interesting events as a phase 2 development:
- \mod_facetoface\event\add_session
- \mod_facetoface\event\delete_session
- \mod_facetoface\event\update_session

**Additional information**
We should follow the attendance recipe: http://xapi.trainingevidencesystems.com/recipes/attendance/0_0_1/

Facetoface plugin:
https://moodle.org/plugins/pluginversions.php?plugin=mod_facetoface
https://github.com/catalyst/facetoface-2.0/

Bug with one of the events and how to get the latest version with that bug fixed: https://tracker.moodle.org/browse/CONTRIB-6200

**Comment by jlowe64** [comment]
The only one I have on my list is:

```
\mod_facetoface\event\signup_success
```

But I agree we should look at those other two later on.

**Comment by garemoko** [comment]
@jlowe64 Just to keep you in the loop, today I'm doing some planning around my next phase of Moodle/Watershed integration work, which includes both xAPI tracking and some Watershed specific integration.  

The issues I'm creating today are strong candidates to form part of that work, so I may end up taking all three of these events on myself in the next few weeks.

**Comment by jlowe64** [comment]
If you took that on, then it would relieve me of the pressure of about 15 events myself! I would really appreciate the help.

I'm currently working on adding the new scorm tracking events (btw, thank you for all the work you put into the batching and questions, because it's helped with scorm a bit) that will be integrated into moodle 3.1.

**Comment by garemoko** [comment]
@jlowe64 SCORM tracking events sounds really interesting!

**Comment by garemoko** [comment]
This just reached the top of my to-do list. Tackling now!

**Comment by garemoko** [comment]
Those three events are now added, with 2 limitations:
- signup_success event is not triggered when people are enrolled by an admin. 
- The unenrol event is not capturing the reason for the unenrolment, which could be nice to capture. 

I'm not planning to address those limitations myself. 

PRs:
- https://github.com/LearningLocker/Moodle-Log-Expander/pull/34
- https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/42
- https://github.com/LearningLocker/xAPI-Recipe-Emitter/pull/35

**Comment by jlowe64** [comment]
Fantastic. By end of next week I should have these merged into a new version along with scorm tracking. I'm just now getting the freedom to actually do that. @garemoko may pick your brain if you had time if I run into any issues.

**Comment by garemoko** [comment]
Absolutely. I can't promise a quick reply but will do my best. Really looking forward to seeing the SCORM tracking.
