### ISSUE TITLE
include error in failed events log

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#522]
It would be really useful to include the reason why an event failed in the mdl_logstore_xapi_failed_log to avoid having to re-run the events and look at the cron trail, especially on production environments. This could just be an extra column including the error string.

**Comment by ryasmi** [comment]
That's a good idea.

**Comment by AlexTo** [comment]
hi @garemoko 
Could you tell me what is the "cron trail"? All of my records are sent to mdl_logstore_xapi_failed_log and I not sure where to look at to debug it.
Thanks

**Comment by ryasmi** [comment]
@AlexTo sounds like you might have misconfigured your LRS details if everything is ending up in the failed log.

**Comment by AlexTo** [comment]
Actually I don't have a LRS, I have a 1 liner Spring RestController with Basic Authentication to retrieve the records sent from Moodle xAPI

I described my issue in #608

The configuration should be very simple so I'm not sure what is wrong. 

My configuration is something like
Endpoint: http://myendpoint/xAPI
User: user
Password: password

If I use CURL as described in #608, the endpoint can receive the String just fine :(

Is there a log or something from this plug in that I can use to troubleshoot?

Thanks a lot

**Comment by ryasmi** [comment]
Ok responded over there.

**Comment by davidpesce** [comment]
I'm forgetting where, but this has been implemented already.
