### ISSUE TITLE
Scorm tracking event

### ISSUE THREAD

**Issue by jlowe64** [davidpesce/moodle-logstore_xapi#53]
@garemoko and @ryansmith94 midway through getting the design of the scorm events added to my local repo. Since it's about to be finalized at Moodle, I would like to run a bit of a design question by both of you. 

The proposed event for scorm status submission and scorm score submission will return all the standard bits of an event, plus a serialized array of 3 cmi fields: attempt number, status/score, and the element. It basically hyper targets one line in scorm_scoes_track. However, this info could be used to pull over the entirety of the tracking data.

I'm having trouble deciding if I should just expand the serialized array in Expander, and then pull out the scorm tracking in the translator, or pull out both the serialized array and scorm tracking in expander, and then add fields for the types of information we'd want to know in the translator?

Does this make sense? Any guidance would be very much appreciated!

**Comment by ryasmi** [comment]
I'm not sure I understand, but like always, bits that only require Moodle go into the Expander, bits that only require the xAPI go into the Emitter, and bits that require both go into the Translator (however, the translator shouldn't fetch any data from the LRS or Moodle).

**Comment by jlowe64** [comment]
Thanks, that's the direction I was leaning in. `Translator shouldn't fetch any data from the LRS or Moodle` helped a lot.

**Comment by ryasmi** [comment]
Awesome. Super, we should probably have that written up somewhere.
