### ISSUE TITLE
Compatability to certain Moodle versions

### ISSUE THREAD

**Issue by nise** [davidpesce/moodle-logstore_xapi#551]
**Description**
I tried to install the latest plugin version on Moodle 3.3 and it failed. There were missing lines in the version.php and further naming conflicts related to the version.php. In the latter case I had to define $plugin->component = "logstore_logstore_api"; As a consequence the lenguages files could not be found.

**Version**
2018082100

**Steps to reproduce the bug**
1. Install the mentioned version on moodle 3.3

**Expected behaviour**
- Salient installation.

**Actual behaviour**
- About 20 errors of this kind:

> 
> Invalid get_string() identifier: 'endpoint' or component 'logstore_xapi'. Perhaps you are missing $string['endpoint'] = ''; in /lang/en/logstore_xapi.php?
> 
>     line 349 of /lib/classes/string_manager_standard.php: call to debugging()
>     line 7081 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
>     line 24 of /admin/tool/log/store/logstore_xapi/settings.php: call to get_string()
>     line 63 of /admin/tool/log/classes/plugininfo/logstore.php: call to include()
>     line 36 of /admin/tool/log/settings.php: call to tool_log\plugininfo\logstore->load_settings()
>     line 81 of /lib/classes/plugininfo/tool.php: call to include()
>     line 583 of /admin/settings/plugins.php: call to core\plugininfo\tool->load_settings()
>     line 8004 of /lib/adminlib.php: call to require()
>     line 806 of /admin/index.php: call to admin_get_root()

  

**Server information**
- Local installation, Apache 2, MySQL

**Client information**
- OS: Ubuntu 16.04 LTS
- Browser: FF

**Additional information**
- Is there a list compatible plugin versions and tested moodle versions available?

**Comment by davidpesce** [comment]
Hello Nise - How did you go about installing the plugin? Did you clone the repo or use the released zip? We haven't updated the version.php in almost a year an have been relying on git to handle our releases: https://github.com/xAPI-vle/moodle-logstore_xapi/releases

**Comment by davidpesce** [comment]
@nise - I'm looking into this now. It looks as if the $plugin->component = "logstore_xapi"; 

In your issue description, you mention adding logstore_logstore_api. Was there a reason for adding the additional logstore_ at the beginning? And also leaving out the 'x" in xapi?

Closing for now, but please reopen if this continues to be an issue.
