### ISSUE TITLE
Course complete event

### ISSUE THREAD

**Issue by CinecaElearning** [davidpesce/moodle-logstore_xapi#56]
**Motive**
the course completed event is not sent

**Result**
The event is added here, in the translator and in the emitter. Eventually the grade could be sent along and maybe the expander could be affected too.

**Additional information**
A possible implementation is developed in our branch xapi_store_2016031401. The event and the test are added in the moodle-logstore_xapi and the same has been done in the translator and in the emitter.

**Comment by timothyjoh** [comment]
+1 for this, we need it

**Comment by DaTebe** [comment]
+1, with grades in the complete event. For me it would be a cool thing to visualize if there is an Gaussian distribution =)

**Comment by jlowe64** [comment]
Completed by:

https://github.com/xAPI-vle/moodle-logstore_xapi/pull/75
https://github.com/LearningLocker/Moodle-Log-Expander/pull/33
https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/41
https://github.com/LearningLocker/xAPI-Recipe-Emitter/pull/34
