### ISSUE TITLE
dispatch status

### ISSUE THREAD

**Issue by CinecaElearning** [davidpesce/moodle-logstore_xapi#57]
**Motive**
logstore_xapi has no return from the emitter about the connection and the dispatch status.

**Result**
The emit_task.php calls the process_events and receives the dispatch result. Since more events are sent, every event has a dispatch return.

**Additional information**

**Comment by ryasmi** [comment]
Awaiting discussion in the Emitter https://github.com/LearningLocker/xAPI-Recipe-Emitter/issues/26.

**Comment by garemoko** [comment]
Fixed: https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/src/Repository.php#L23-L28

**Comment by ryasmi** [comment]
Happy to close this @garemoko or is there additional work needed?

**Comment by garemoko** [comment]
@ryansmith94 I believe this can be closed
