### ISSUE TITLE
The scoping rules for the use keyword

### ISSUE THREAD

**Issue by mudrd8mz** [davidpesce/moodle-logstore_xapi#6]
The file `classes/log/store.php` uses the `use` keyword inside the class block scope:

```
class store extends php_obj implements log_writer {
    use helper_store;
    use helper_reader;
    use helper_writer;
```

According to the [PHP manual](http://php.net/manual/en/language.namespaces.importing.php#language.namespaces.importing.scope) this is illegal use of the `use` keyword. Am I missing something here?

**Comment by jlowe64** [comment]
I did not know that. I was more or less doing what logstore_standard did in this case. So we should probably move this to the outermost scope?

**Comment by mudrd8mz** [comment]
D'oh! I just found it is in the standard logstore too. Thank for letting me know! I'll report that as an upstream issue.

If I see it right, it seems you can just remove those three lines from the class block. The classes are imported in the global scope already anyway.

**Comment by jlowe64** [comment]
That does appear to be right. I will remove it and see if it throws any errors.

**Comment by jlowe64** [comment]
When removed it throws the following error:

Fatal error: Class logstore_xapi\log\store contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (tool_log\log\writer::write, tool_log\log\store::dispose) in /moodle/admin/tool/log/store/xapi/classes/log/store.php on line 125

Those two functions don't really seem necessary for me to repeat in my code as I don't even use them, so this may be that the logstore system needs to be re-adjusted before we can safely remove these from within the class?

**Comment by mudrd8mz** [comment]
Reported upstream as https://tracker.moodle.org/browse/MDL-50906

**Comment by ryasmi** [comment]
I'm unaware of any other way to use [traits in PHP](http://php.net/manual/en/language.oop5.traits.php)

**Comment by jlowe64** [comment]
Yeah, I think @mudrd8mz was making the assumption that traits weren't being used and that it was just classes. So in the case of traits, this would be a correct use, but if it were classes, this would not be the way it would work. 

I've honestly never seen traits used in Moodle before, so I'll just close this off for now and periodically check that tracker thread at Moodle to see if there's any changes to the logstore system.

**Comment by ryasmi** [comment]
Ok @jlowe64 :+1:

**Comment by mudrd8mz** [comment]
Yup, I can confirm this was my mistake as I had not realized this "use" refers to traits, not classes. Sorry about the false alarm.

**Comment by ryasmi** [comment]
No worries @mudrd8mz
