### ISSUE TITLE
Changing the way the actor's name is generated.

### ISSUE THREAD

**Issue by caperneoignis** [davidpesce/moodle-logstore_xapi#60]
I have been making the change myself for some time. But I was wondering if for the actor we can change it to:
"actor": {
        "objectType": "Agent"
        "name": "John Doe",
        "account": {
            "name": "username",
            "homePage": "https://example.com"
        }

This is because, in our instance, and I know in some other instances, an ID is used as the username, and it is easier to view if the actual name 'first last' is used for the actors name, and the account name is set to the username. Also, I have added a utf8 converter for the name to ensure things like ' get stored correctly, or just removed, since special characters are used with peoples names. 

This way we have the real name attached to the statements, to help with reporting, and also for a better display on things like LearningLocker/watershed. Let me know what you think.

**Comment by ryasmi** [comment]
Hmmm, this might actually be a really good idea. This potentially solves the issue of users getting removed and re-added, etc in #35.

I think there should be settings for this, so that it can be configured, however, I think using a username is a sensible default and can potentially maintain anonymity if the Activity Provider (owner of Moodle installation) wants to.

Any thoughts on this @jlowe64 @garemoko @CinecaElearning?

**Comment by caperneoignis** [comment]
I also really like the idea of it being optional, because then you can use a separate item to look up the user's name based on the ID in another location. However, I have noticed, the fullname seems to get dropped in certain registration events, but the username still appears. That is probably a self introduced bug, though.

Edit: The issue was self introduced, and resolved in this issue #68. Just in case any one stops on this issue, and wants to make the change themselves for the time being.

**Comment by jlowe64** [comment]
Some of our customers use emails as usernames, so it definitely needs to be an optional setting. I was thinking, maybe we could also do a second layer of protection here to give a warning if the user activates this and their LRS is using http, instead of https. If we're concerned about interception between Moodle and the LRS, that is. I'm not too aware of issues of anonymity within the LRS itself.

**Comment by ryasmi** [comment]
I can't remember the exact issue with storing identifiable information in a statement, but I remember the conclusion was that in some countries (probably Germany) it's not ok. There are other problems with using emails too in certain organisations. Not sure if @ht2 can remember the issue here.

**Comment by caperneoignis** [comment]
@jlowe64 and @ryansmith94 The problem is, in some government settings, the full name can be considered PII. Email also believe it or not. That is why the optional item is a good idea. Otherwise, the LRS has to have a risk assessment done with an additional PII constraint, which makes the check more stringent. But if it is optional from the LMS side, then that gives a lot more flexibility for hosting the LRS with potential restrictive customer requirements.

**Comment by garemoko** [comment]
See #35 and the way the tin can launch get actor function works. Thats how I would do it (and indeed how I did do it!) Each Moodle handles usernames and ids differently; there needs to be some solid config options.

**Comment by caperneoignis** [comment]
I add a line to event.php in moodle-xapi-translator 

``` javascript
'user_fullname' => $opts['user']->firstname.' '.$opts['user']->lastname;
```

and modify the function readUser in event.php under xapi-recipe-emitter

``` javascript
  protected function readUser(array $opts, $key) {
        return [
            'name' => $this->convertToUTF8($opts[$key.'_fullname']),
            'account' => [
                'homePage' => $opts[$key.'_url'],
                'name' => $opts[$key.'_name'],
            ],
        ];
    }
```

With the function convertToUTF8 designed to ensure special characters are converted to the correct format before being stored in MongoDB, because MongoDB likes to store characters in UTF8. I had the problem with people like O'Connell being stored with the html value for " ' ". That probably isn't the best way of doing it, but figured I try and contribute something to this discussion. Hope you don't mind.

**Comment by garemoko** [comment]
Statements should be sent in UTF-8, so if they are coming in to Learning Locker not in that format, possibly that's something that needs to be addressed at the TinCanPHP level. Thoughts?

**Comment by caperneoignis** [comment]
Sorry, about that, I clicked on the wrong button.
