### ISSUE TITLE
User activities statement not getting inserted into statement table

### ISSUE THREAD

**Issue by yashbant** [davidpesce/moodle-logstore_xapi#600]
We are using Grassbalde-LRS for our multiple courses. But recently we are facing one issue where the statement is getting inserted into gb_activities_state table but not into gb_all_statements table, specially the passed verb.
Also we are not able to login into grassbalde dashboard as its not responding anything. Please let me know if there any limitation issue(no. of statements).

**Comment by garemoko** [comment]
This sounds like an issue with grassblade and not this plugin. Does it work with another lrs?

**Comment by davidpesce** [comment]
Hello @yashbant - were you able to sort this out? I'm going to close this, but feel free to open if you still need help!
