### ISSUE TITLE
Missing privacy provider, causing failing unit tests

### ISSUE THREAD

**Issue by yao9394** [davidpesce/moodle-logstore_xapi#604]
**Description**
- missing privacy provider is making Moodle complain on unit tests

**Version**
- master at 2d1fd066923dedcdb7368b83fda5c8fc2ea4dcb3 on 2018082100

**Steps to reproduce the bug**
1. run command ```vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php```

**Expected behaviour**
- should see no failing tests

**Actual behaviour**
- we see:
```1) provider_testcase::test_all_providers_compliant with data set "logstore_xapi" ('logstore_xapi', 'logstore_xapi\privacy\provider')
Failed asserting that false is true.

/siteroot/privacy/tests/provider_test.php:178
/siteroot/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php

2) provider_testcase::test_table_coverage
The following tables with user fields must be covered with metadata providers: 
  - plagiarism_turnitin_users (userid)
  - logstore_xapi_log (userid)
  - logstore_xapi_failed_log (userid)
```

**Client information**
- OS: Linux

**Comment by davidpesce** [comment]
Closing in favor of the new feature issue #617
