### ISSUE TITLE
Question: how to debug failed statements

### ISSUE THREAD

**Issue by AlexTo** [davidpesce/moodle-logstore_xapi#608]
I'm using the latest Moodle docker from here https://hub.docker.com/r/bitnami/moodle/

Moodle logstore xapi: v4.4.0

I have an endpoint at http://myip/endpoints/xAPI that uses basic authentication. The endpoint works because from within the docker instance, I run CURL like this and the "something" string is received by the endpoint.

```
curl -X POST -u user:password -d something http://myip/endpoints/xAPI
```
The endpoint is a very simple Spring RestController. It stores whatever String RequestBody sent to it.

I configured xAPI logstore to point to the above endpoint, enable schedule task and manually request http://localhost/admin/cron.php. It says "Cron script completed correctly". However, when I check the "mdl_logstore_xapi_log" table, all the records are moved to mdl_logstore_xapi_failed_log

I tried to copy records from "mdl_logstore_standard_log" and trigger the crop.php but the records are moved to "mdl_logstore_xapi_failed_log"

My silly question is: what should I be looking at? I found nothing in Apache logs (I guess that makes sense because the cron.php script completed correctly".

Thanks a lot

Best,

**Comment by ryasmi** [comment]
Noticed that you're missing `/statements` @AlexTo on the end of that URL (note that the plugin appends this onto your configured endpoint). So you should really be testing the following.

```
curl -X POST -u user:password -d something http://myip/endpoints/xAPI/statements
```

**Comment by ryasmi** [comment]
Forgot to mention that the endpoint also needs to return a 200.

**Comment by davidpesce** [comment]
@AlexTo - were you able to sort this out? Feel free to reopen if not.
