### ISSUE TITLE
logguest - logs guest when off in setting

### ISSUE THREAD

**Issue by HaakonME** [davidpesce/moodle-logstore_xapi#609]
**Description**
- Learning Locker 2.6.3 receives xAPI statements about guest user from Moodle Moodle 3.5.9 (Build: 20191111) using module Logstore xAPI / logstore_xapi version 2018082100, even though this setting is OFF in Moodle.

**Version**
- logstore_xapi version 2018082100

**Steps to reproduce the bug**
1. Log guest actions logstore_xapi | logguests is NOT checked.

**Expected behaviour**
- LL should be NOT receive xAPI statements about guest from Moodle because the setting Log guest actions is NOT set (no checkmark in Moodle).

**Actual behaviour**
- LL is receiving a lot of xAPI statements about Guest user from Moodle.

**Server information**
- MySQL with authentication.

**Client information**
- OS: Debian
- Browser: N/A

**Additional information**
- N/A regarding site.
- Source code referencing logguest at Github repo:
1) https://github.com/xAPI-vle/moodle-logstore_xapi/blob/da6298a14f9d7cbec3a4ee14c0679629a5c6b8b2/settings.php
2) https://github.com/xAPI-vle/moodle-logstore_xapi/blob/b5e699f543da6306f09207136b9a0a36f28c9164/classes/log/store.php
3) https://github.com/xAPI-vle/moodle-logstore_xapi/blob/a467f000d588fb04fe4f6d9ea3b326ee2a60baea/lang/en/logstore_xapi.php

Cheers,
Haakon

**Comment by davidpesce** [comment]
Hi @HaakonME - thanks for submitting this and following the format!

It looks as if you're running a version of the plugin that is very outdated. Would you be able to update to a more recent version (preferably the latest) and let us know if this continues to be a problem?

Please re-open if it's still a problem.
