### ISSUE TITLE
Use context.registration

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#61]
The JISC recipes include a sessionId context extension. Since this extension simply replicates the function of the context.registration property, we should use that instead. context.registration is useful for grouping statements about a single session together. 

To implement this in the plugin, we'll need a way to get the user's session id and then have a look up table to match the session id to the registration UUID.

**Comment by jlowe64** [comment]
I've not messed with Moodle sessions a lot. I know there's a sessions table, but what if a user is using files or memcached for sessions? Is it still stored in the DB?

**Comment by garemoko** [comment]
Definitely needs testing and looking into

**Comment by jlowe64** [comment]
I agree.

**Comment by micaherne** [comment]
It would probably be best to use the Moodle $SESSION global for this (as distinct from the PHP $_SESSION global), which sidesteps having to know how the sessions are stored.

**Comment by ryasmi** [comment]
Closing this since I can't find any decent documentation around the `$SESSION` global. If some documentation is found I'll look into adding this. We'll also need a way to generate a UUID from whatever the session ID is, since I'm assuming it's not going to be UUID itself.
