### ISSUE TITLE
I want to install logstore_xapi but will be blank

### ISSUE THREAD

**Issue by cool3690** [davidpesce/moodle-logstore_xapi#610]
**Description**
I have problem, I use moodle 3.7.2 and I want to install logstore_xapi , I install xapi release V4.4.0 ,but when I finish install, my moodle broken,it blank, I have try many time,please help me, thank.

**Version**
moodle 3.7.2
 xapi release V4.4.0 
**Steps to reproduce the bug**
1. just install logstore_xapi, moodle will shutdown.....

**Expected behaviour**
I expected I can install logstore_xapi

**Actual behaviour**
my moodle will blank after I install logstore_xapi

**Server information**
- 10.4.8-MariaDB

**Client information**
- OS: win10
- Browser: chrome

**Comment by davidpesce** [comment]
Thanks for submitting an issue and following the format!

Can you turn on Moodle debugging and share the error message that appears when you attempt to go to the page? 

If you're unfamiliar with setting the debug settings, please look here: https://docs.moodle.org/37/en/Debugging

You'll want to set it to DEVELOPER mode.

**Comment by cool3690** [comment]
davidpesce, hi
I open the debug,but I dont know where I can see it
I have a video,which record me I install fail
https://drive.google.com/open?id=1x10-O5pnXAZAKmRIxb2amb9WsJZlpaQs

thanks

**Comment by cool3690** [comment]
I install success after I open full debug,thank,
I have set endpoint, but I still can not see the chart on scorm cloud....
