### ISSUE TITLE
moodle use logstore xapi to scorm cloud but not work

### ISSUE THREAD

**Issue by cool3690** [davidpesce/moodle-logstore_xapi#611]
**Version**
- moodle3.7.2
  xampp 3.2.4 
**Expected behaviour**
- it should have record on scorm cloud after I finish quiz

**Actual behaviour**
-No data on scorm cloud after I finish exam

**Client information**
- OS: win10
- Browser: chrome

**Description**
- I have problem to need help.
I use moodle 3.7.2 and install logstore xapi, I hope I can do LRS on scorm cloud.
but It still not work after I install xapi and setting it,

I have build a course and quiz,student also finish quiz.
but my record still not show.
this is my setting picture. xapi setting
image
![image](https://user-images.githubusercontent.com/16379115/72527218-364c0d80-38a3-11ea-9dd4-76095b44934d.png)

this is my record my record
image
![image](https://user-images.githubusercontent.com/16379115/72527243-4237cf80-38a3-11ea-95de-a4b379fc37dd.png)

please help me thanks.

**Comment by davidpesce** [comment]
Hello,

A few things could be causing an issue. 

Did you enable the logstore plugin? Site admin > Plugins > Manage log stores -- make sure the eye icon isn't crossed out.

Do you have cron enabled on your Moodle instance? By default, the plugin uses cron to send the statements in batches.

The last item to check is in the logstore_xapi plugin settings. Make sure that all the events you'd like sent to the LRS have a checkmark next to them.

**Comment by cool3690** [comment]
hello,davidpesce
1. I have enable it. this is picture
<a href="https://imgur.com/Ns9PYZP"><img src="https://i.imgur.com/Ns9PYZP.png" title="source: imgur.com" /></a>

2.I was not install cron, now,I download and install it.
<a href="https://imgur.com/IRXoqRW"><img src="https://i.imgur.com/IRXoqRW.png" title="source: imgur.com" /></a>

3.I all have check
<a href="https://imgur.com/KJ3oTtQ"><img src="https://i.imgur.com/KJ3oTtQ.png" title="source: imgur.com" /></a>

but my record still not show.......
what step I lose it ?
thanks

**Comment by cool3690** [comment]
> Hello,
> 
> A few things could be causing an issue.
> 
> Did you enable the logstore plugin? Site admin > Plugins > Manage log stores -- make sure the eye icon isn't crossed out.
> 
> Do you have cron enabled on your Moodle instance? By default, the plugin uses cron to send the statements in batches.
> 
> The last item to check is in the logstore_xapi plugin settings. Make sure that all the events you'd like sent to the LRS have a checkmark next to them.

hello,davidpesce
1. I have enable it. this is picture
<a href="https://imgur.com/Ns9PYZP"><img src="https://i.imgur.com/Ns9PYZP.png" title="source: imgur.com" /></a>

2.I was not install cron, now,I download and install it.
<a href="https://imgur.com/IRXoqRW"><img src="https://i.imgur.com/IRXoqRW.png" title="source: imgur.com" /></a>

3.I all have check
<a href="https://imgur.com/KJ3oTtQ"><img src="https://i.imgur.com/KJ3oTtQ.png" title="source: imgur.com" /></a>

but my record still not show.......
what step I lose it ?
by the way  My web is build on localhost,Is it available?
thanks

**Comment by davidpesce** [comment]
Hmm, that is strange. Try unchecking the "Send statements by scheduled task?". This should bypass cron.

You can also enable DEVELOPER debug and it'll show the errors in the browser.

**Comment by cool3690** [comment]
> Hmm, that is strange. Try unchecking the "Send statements by scheduled task?". This should bypass cron.
> 
> You can also enable DEVELOPER debug and it'll show the errors in the browser.

hello ,
I dont see this "Send statements by scheduled task?" on my page
<a href="https://imgur.com/KJ3oTtQ"><img src="https://i.imgur.com/KJ3oTtQ.png" title="source: imgur.com" /></a>

I have open DEVELOPER debug,but I dont know where I can see the error log
I read this web [https://docs.moodle.org/38/en/Cron_with_Windows_OS](url)
so I have type
`c:\xampp\php\php.exe -f c:\xampp\htdocs\moodle\admin\cli\cron.php > c:\xampp\htdocs\moodle\admin\cli\cron.log`
on cmd
it build a corn.log

<a href="https://imgur.com/5fLDYBx"><img src="https://i.imgur.com/5fLDYBx.png" title="source: imgur.com" /></a>
but my scorm cloud still not work.
I have no idea.....

I am new in moodle,so many thing I still not understand.(sorry...
so,please help me
thanks

**Comment by davidpesce** [comment]
Ahh, if you don't have that option, then you're running an older version of the plugin. Be sure to download the plugin from here (https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v4.4.0) rather than the Moodle Plugin database.

**Comment by davidpesce** [comment]
Hello @cool3690 - were you able to get this sorted?
