### ISSUE TITLE
Ensure tags are stripped from all language fields (including in examples)

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#62]
Some of the example and probably some of the code has language map properties that include html tags. We need to go through the plugin and strip these out wherever they occur.

**Comment by jlowe64** [comment]
Agreed!

**Comment by jlowe64** [comment]
@garemoko As an example `"commenttext": "<p>test comment<\/p>",` occurs in the AssignmentSubmitted.json doc. You are suggesting stripping the HTML specific tags from this?

**Comment by garemoko** [comment]
I don't think we need to strip them from extensions necessarily, but from the proper xapi properties we should.

**Comment by jlowe64** [comment]
Cool, I will look for those! Thanks @garemoko.

**Comment by garemoko** [comment]
May have been fixed by the sweep you just did? i can't see any now.
