### ISSUE TITLE
Use activity type http://id.tincanapi.com/activitytype/lms to refer to the Moodle site

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#63]
Currently in the examples for logged in, we use activity types http://lrs.learninglocker.net/define/type/moodle/course and http://id.tincanapi.com/activitytype/site to refer to the Moodle site activity. The course one is probably just a documentation error. 

At LAK16 hackathon, the group felt that the activity type http://id.tincanapi.com/activitytype/lms made the most sense here. This should be changed throughout the plugin and docs.

**Comment by jlowe64** [comment]
I think this was mentioned before. Sounds good to me!

**Comment by davidpesce** [comment]
@garemoko over here.

**Comment by davidpesce** [comment]
Fixed in release v2.2.4.

Leaving open because it may be worthwhile to adjust the other activity types more in line with the industry standards.

**Comment by garemoko** [comment]
@davidpesce huh?
