### ISSUE TITLE
Activity types should be designed, not auto-generated and should not contain the term "Moodle"

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#64]
The plugin currently uses auto-generated activity types that consist of a base URI plus the name of the Moodle module. The advantage of this approach is that any Moodle module, including those unknown to the plugin developers is can be given  unique id, so long s the Moodle module name is unique (not guaranteed). 

This advantage of somewhat undermined by the fact that due to other limitations of tracking unknown modules, the plugin only tracks those modules which it is designed to track. 

The problem with this approach is that these activity types are unlikely to be replicated exactly in other LMS/VLEs. For this reason we should move to a system of designed activity types. See the base URI used here: https://github.com/jiscdev/xapi-vle/blob/master/recipes/Module-View.md#example-valid-values (this list needs to be extended)

**Comment by ryasmi** [comment]
> the plugin only tracks those modules which it is designed to track

Whilst this is true, auto-generating activity types saves us writing additional classes sometimes.

> The problem with this approach is that these activity types are unlikely to be replicated exactly in other LMS/VLEs.

This isn't a problem, the activity types are defined in the translator which would be completely re-written in a different LMS/VLE anyway.

**Comment by garemoko** [comment]
@ryansmith94 the goal I'm trying to get to here is that every LMS uses the same activity types. The terms and groupings that Moodle uses may not necessarily be best for all LMSs, for example the Moodle Feedback and Survey modules might make sense as having the same activity type since they are basically the same type of activity

**Comment by ryasmi** [comment]
It might be good to standardise in some cases, but you can't standardise in all cases I don't think

**Comment by ryasmi** [comment]
If we're going to standardise @garemoko, let's do it in the Emitter. Had a call with JISC, we're going to create some governance around the recipes in the Emitter, so I'm happy to standardise them now.

**Comment by nadavkav** [comment]
I have installed the H5P (mod/hvp), and I am already experiencing these issues, as the events generated by hvp are not dispatched to the LRS.
After adding some Controller $routes it started to show up in the LRS. (And I am only started with this, it is not completely finished)
It seems we need a better way to support future and unknown modules.

**Comment by ryasmi** [comment]
Hey @nadavkav, please excuse my ignorance here, what is H5P? I guess it's something to do with [the H5P website](https://h5p.org/), but I'm not sure why that is relevant here.

> After adding some Controller $routes it started to show up in the LRS.

What routes did you add?

**Comment by garemoko** [comment]
@ryansmith94 It's a bit like a content authoring tool. @nadavkav is building a H5P module for moodle, so it'll be an activity type. Rather than emitting the xAPI events directly, the plan is for them to be logged and sent by this logstore plugin. It's a little different as H5P generates the base xAPI statements itself so there won't be much for the translator to do, but I still think its the right approach.

**Comment by ryasmi** [comment]
Thanks @garemoko. So they're basically just trying to add events?

**Comment by garemoko** [comment]
yep

**Comment by ryasmi** [comment]
Right, what's the issue with the $routes then and how is that related to this issue?

**Comment by nadavkav** [comment]
Thank you @garemoko for making it clear :-)
It is exactly as he described it.

I am double checking the routes today with the QA team, and if it all goes well... we'll send a PR.

**Comment by nadavkav** [comment]
I guess I is not exactly part of this issue, but I was probably confused by part of the title "Activity types should be designed, not auto-generated" as it looked to  me a little bit problematic to be needed to add new routes every time we add new modules to Moodle.
But, maybe the H5P is a little bit different and not the common case, as it already dispatching xAPI statements ( which is, sort of, equivalent to the process of the "expander" and the "translation")

**Comment by ryasmi** [comment]
Sorry I forgot to respond @nadavkav. Yeah I can see how that might look problematic and perhaps it is, if so we can make a separate issue for that 👍

**Comment by nadavkav** [comment]
As part of the fixes I am doing in the H5P.org project I already made all the code changes to the "expander", "translator" and "dispatcher". which works just fine. and I like the architecture too.
I am waiting for some PR to get into core H5P before I PR all the new patches/fixes that are relevant to this project.

**Comment by davidpesce** [comment]
Combining external repo issues into main repo:
Per @garemoko in Emitter repo issues (https://github.com/LearningLocker/xAPI-Recipe-Emitter/issues/28):
"I'm designing some statements for another LMS. I think it makes sense to use the same activity type for for all course LMSs, but I'm reticent to use "http://lrs.learninglocker.net/define/type/moodle/course" because that seems Moodle specific.

Right now I'm tempted to coin another identifier for this other LMS, which would be something like http://id.tincanapi.com/activitytype/lms-course"

It was determined that we would use: http://id.tincanapi.com/activitytype/lms-course

**Comment by ryasmi** [comment]
Version 3 will use more "designed" activity types. I'm going to close this, going forward let's create a new issue for each activity type we want to change.

**Comment by ryasmi** [comment]
https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v3.0.0
