### ISSUE TITLE
Include short id in statement (as an optional setting)

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#65]
The JISC fork of this plugin includes an extension called http://xapi.jisc.ac.uk/extensions/vle_mod_id which stores the academic short code of the academic course that the Moodle course relates to. This isn't in the best place, and the working group at the LAK hackathon didn't like the identifier because it's not clear what it is. We proposed that this be an object definition extension within the course object using the id https://w3id.org/learning-analytics/learning-management-system/short-id

This would use the Moodle short code, but would ned to be optional as a config setting since not all Moodle instances will use the Moodle short code in this way.

**Comment by jlowe64** [comment]
@garemoko can you link me to some Moodle specific documentation on this? I've not found any doing a google search. Where is the short code stored?

**Comment by garemoko** [comment]
It's in mdl_course/shortname

**Comment by jlowe64** [comment]
Ah! I figured that's what we were talking about. I think all my customers use it, but it doesn't ever get uitilized. So I agree, optional setting.

**Comment by ryasmi** [comment]
Will be resolved in #182
