### ISSUE TITLE
Assignment object due date extension

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#66]
JISC have an extension http://xapi.jisc.ac.uk/extensions/duedate which contains the assignment due date as an ISO 8601 timestamp. We should use this.

**Comment by ryasmi** [comment]
If we don't want to replicate that, but we want to use their extension, then JISC need to change that before we implement it differently here.

**Comment by ryasmi** [comment]
I think @andrewhickey had an issue with that.

**Comment by ryasmi** [comment]
Which events was this intended to be added to @garemoko?

**Comment by garemoko** [comment]
Both the assignment ones (graded and submitted)

**Comment by ryasmi** [comment]
Ok nice, thanks @garemoko 👍

**Comment by ryasmi** [comment]
Note to self this is for `assignment_graded` and `assignment_submitted`

**Comment by garemoko** [comment]
> Note: the JISC extension has a weird object-with-one-property structure. We shouldn't replicate this.

@ryansmith94 do you know if that's still an issue?

**Comment by ryasmi** [comment]
No it's no longer an issue according to example statements I've seen and [their documentation](https://github.com/jiscdev/xapi/blob/master/recipes/vle/assignment-submitted.md#object).

**Comment by garemoko** [comment]
Edited the issue to remove that note.

**Comment by davidpesce** [comment]
JISC branch has been merged into master. We are good to go here!
