### ISSUE TITLE
Assignment graded should include more score properties

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#67]
The Assignment graded example json should include min score. The actual code already outputs this: https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/src/Events/AssignmentGraded.php#L22-L26

**Comment by jlowe64** [comment]
I saw this when I was adding the scorm tracking.

**Comment by jlowe64** [comment]
Re-generated all the docs for Emitter. It now includes all newest data from the changes made.
