### ISSUE TITLE
Error in Emit Records Task

### ISSUE THREAD

**Issue by jackeapen** [davidpesce/moodle-logstore_xapi#680]
Hi

I installed latest version of logstore_xapi plugin in Moodle 3.8 and gave the API credentials to link with Annulab lRS. when I run the emit records task, below message is received. How do I troubleshoot?

Execute scheduled task: Emit records to LRS (logstore_xapi\task\emit_task)
30 event(s) have failed to send to the LRS.
0 event(s) have been successfully processed.
... used 9 dbqueries
... used 1.7226519584656 seconds
Scheduled task complete: Emit record

**Comment by davidpesce** [comment]
Hello @jackeapen - this is most likely due to the LRS credentials being incorrect. Were you able to resolve this issue on your own?
