### ISSUE TITLE
Back fill logs after an update or by choice

### ISSUE THREAD

**Issue by caperneoignis** [davidpesce/moodle-logstore_xapi#69]
Is there any way currently to back fill logs using xapi? IE. When there is an update, and more items are added to a statement, or a fix that corrects the way a statements is displayed, is there a way or will be a way to get xapi to go though the logs, and convert those in to the proper statements and send it to the LRS? I understand, if it did that with an LRS the LRS might get repeats, but if you can back fill, you can also just create a new LRS. 

Obviously, we have been running the LRS for a while with an xAPI plugin on the LMS side, and some of the earlier statements have fewer items in the statements, or came in different because of the changes between versions. I think it would be a great add-on, if the option to dig into the logs and convert them to xAPI statements existed. I was wondering if anyone has tried doing that or if there was a plan to try and do that.

**Comment by ryasmi** [comment]
Hi @caperneoignis, thanks for your question. I'm not sure if I understand you correctly, but if I have, then you probably want to check out #42. I'll close this question for now, if this is not the answer you were looking for, I can reopen it.

**Comment by caperneoignis** [comment]
You sir, are correct. That is exactly what I was thinking of. Thanks.

**Comment by ryasmi** [comment]
Awesome! You're welcome @caperneoignis 👍
