### ISSUE TITLE
Should the logstore_xapi/endpoint better be PARAM_URL?

### ISSUE THREAD

**Issue by mudrd8mz** [davidpesce/moodle-logstore_xapi#7]

**Comment by jlowe64** [comment]
Do you have a link to where it validates the URL using that? Would it cause issues for endpoints that might not look like standard URLs, for examples those that may include a weird hash as part of the URL?

**Comment by mudrd8mz** [comment]
https://github.com/moodle/moodle/blob/master/lib/moodlelib.php#L1017 There should be unit tests for it somewhere, too. I don't think it is crucial, just caught my eye.

**Comment by jlowe64** [comment]
I'll be committing this change.
