### ISSUE TITLE
{{LRS Endpoint and Installation}}

### ISSUE THREAD

**Issue by DaTebe** [davidpesce/moodle-logstore_xapi#71]
{{Hi, I'm new to this kind of topic. Is it possible to specify an HTTP-Endpoint (maybe logstash) that just receives the Activity-Stream without a special LRS like Learning Locker? Also I was not able to emit an event with this plugin (for example user login/logout). Do I need to install the three other parts using composer (Moodle Log Expander, Moodle to xAPI Translator, xAPI Recipe Emitter). Sorry for my noobish questions.}}?

**Comment by ryasmi** [comment]
#72
