### ISSUE TITLE
LRS Endpoint and Installation

### ISSUE THREAD

**Issue by DaTebe** [davidpesce/moodle-logstore_xapi#72]
Hi, I'm new to this kind of topic. 

Is it possible to specify an HTTP-Endpoint (maybe logstash) that just receives the Activity-Stream without a special LRS like Learning Locker? 

Also I was not able to emit an event with this plugin (for example user login/logout). Do I need to install the three other parts using composer (Moodle Log Expander, Moodle to xAPI Translator, xAPI Recipe Emitter)?

Sorry for my noobish questions.

**Comment by ryasmi** [comment]
Hi @DaTebe, thanks for your questions. I've tried to respond to them below.

> Is it possible to specify an HTTP-Endpoint (maybe logstash) that just receives the Activity-Stream without a special LRS like Learning Locker?

I'm not sure why you'd want to install the plugin in that case. So what is the use case for that?

> Also I was not able to emit an event with this plugin (for example user login/logout). Do I need to install the three other parts using composer (Moodle Log Expander, Moodle to xAPI Translator, xAPI Recipe Emitter)?

Those parts should be installed when you install the plugin. How did you install the plugin? Did you follow the [installation instructions that we provide](https://github.com/jlowe64/moodle-logstore_xapi/blob/master/docs/installation.md)?

**Comment by DaTebe** [comment]
Hi,
thank you for answering my questions so fast =)!

1) For my master thesis I want to visualize learning data from different platforms with the ELK-Stack. One of these platforms is Moodle. It would be nice to receive the JSON Activity Stream vom Moodle in Logstash so it can be easily searched by Elasticsearch and visualized by Kibana. Other platforms will foreword their logging to Logstash, too. I'm hoping for a homogeneous system to generalize the the logging and improve the learning analytics.

2) I copied the plugin folder to "admin/tool/log/store". This was the instruction from the Moodle Plugin page. I should try to install the plugin with the D&D method I guess?

**Comment by ryasmi** [comment]
Hi @DaTebe, you're very welcome.
1. Ok thanks for that information. The thesis sounds very interesting and is similar to a lot of the work that we do with the xAPI and LRSs. Unfortunately, this plugin is setup to connect to an LRS not something like Logstash. However, you could potentially replace the Repository in the Emitter to connect to something like Logstash.
2. Where are those instructions? They certainly shouldn't be the instructions. I'd recommend installing with the D&D method from the instructions that I linked above.

**Comment by DaTebe** [comment]
Hi!

1) That's a plan! But for me it sounds curious that the plugin does not emit simple JSON and a receiver can work on that data.

2) I found this instructions on "https://moodle.org/plugins/pluginversions.php?plugin=logstore_xapi"
Click on "Version" and on "learn more" (current version). Scroll down to "Default installation instructions for plugins in category Log storage". I thought default should work, too.

**Comment by ryasmi** [comment]
1. I can see why that sounds curious. However, the xAPI is a specification that defines a JSON schema for tracking experiences specifically and an LRS can understand this schema. Therefore, more often than not, an LRS is involved because it can validate, organise, and analyse the data in ways that Logstash or similar tools unfamiliar with the xAPI cannot.
2. I see, those instructions do make sense, how did you download the plugin?

**Comment by DaTebe** [comment]
1. Will the JSON string be build in the xAPI Plugin or on the LRS side? 
2. I downloaded it from the Moodle page. Unzipped the package  and put the folder inside the "admin/tool/log/store" folder. The installation started and finished successfully. Maybe the plugin is working but does not emit anything because of an missing LRS. I only have a little Node.js script that listens on a port an prints everything to console for testing purposes. The Endpoint is defined as "http://localhost:3000". Username and password are empty.

**Comment by ryasmi** [comment]
1. The xAPI Plugin builds the JSON.
2. Ok it sounds to me like it should have installed correctly. Your Node server needs to return 204 as the response code when it receives a HTTP request containing data.

**Comment by DaTebe** [comment]
Hi,

I was able to receive something with my node app. At least the plugin tried to establish an connection! Tomorrow I will look what data will be transmittet.

**Comment by ryasmi** [comment]
Awesome, thanks for the update @DaTebe.

**Comment by DaTebe** [comment]
@ryansmith94 Hi there!
Is it possible to emit an demo event? I thought it would work but somehow I was not able to repeat the success from Monday. It shouldn't be this hard to get some data from the xAPI Plugin. But I'm stuck.

**Comment by ryasmi** [comment]
Hi @DaTebe, the easiest event trigger would be viewing a course, so if you create a course and just keeping viewing it by refreshing the page, etc that should emit an event each time.

**Comment by DaTebe** [comment]
Unfortunately nothing seems to work. Is there any demo LRS endpoint?

**Comment by ryasmi** [comment]
No there isn't a demo LRS any more. Can I take a look at the code you have running in Node? 😄

**Comment by DaTebe** [comment]
I only have a very basic routing for testing if anything tries to connect (I take a look inside my node logs):

```
router.get('/', function(req, res) {
  res.status(204);
});

router.post('/', function(req, res) {
  res.status(204);
});

```

I can CURL `localhost:3000` and everything works. The Node log tells me a 204 is send.
Moodle does not seem to emit something. I also played around with docker and linked my Containers. Same effect. I can access my node app with CURL.

**Comment by garemoko** [comment]
@DaTebe If you just need an LRS rather than Learning Locker specifically you can register a free SCORM Cloud account and use the LRS there: https://cloud.scorm.com/sc/guest/SignUpForm

Other LRSs also have free plans.

**Comment by ryasmi** [comment]
Where are you hosting Moodle @DaTebe? You may also want to try changing the endpoint to "http://localhost:3000/", although I don't think that should make a difference.

**Comment by DaTebe** [comment]
I have two different Setups. 
On the first everything is installed directly on Ubuntu. Moodle runs on an nginx server.
The second one uses Docker to visualize everything. I have two containers. One for nginx with moodle and one for node. Inside my moodle container I can curl my node app with "nodeapp:3000". 

Does the xApi Plugin have a log-file?  

Edit: Scorm Cloud does not receive any Statements. I have a Activity Provider. What are the user credentials (login data or key&secret)?

**Comment by ryasmi** [comment]
Ok, I was just wondering if there was some sort of firewall preventing Moodle accessing your Node server.

> Does the xApi Plugin have a log-file?

Yes, but logging is disabled by default. You'd have to change the [`$loggingenabled` variable to `true` in "classes/log/store.php"](https://github.com/jlowe64/moodle-logstore_xapi/blob/master/classes/log/store.php#L54) inside the plugin's directory. I think logs are emitted into "classes/log/error_log.txt".

**Comment by DaTebe** [comment]
It seems that the plugin does not create a error_log.txt 

Edit: I'll reinstall the plugin with the D&D method. Then I'll try Scorm again.
Edit2: The connection with Scorm is working!
Edit3: Now I have something. The Plugin tries to connect to my node app. It POSTs to 'nodeapp:3000/statements'. That's something I can work with.

**Comment by DaTebe** [comment]
Wow. 
Now I can receive JSON Strings! The D&D install method was the key. I changed nothing on my setup and now everything seems to work out of the box!

**Comment by ryasmi** [comment]
That's great to hear @DaTebe! 👍  is it ok to close this issue now?

**Comment by DaTebe** [comment]
Jep!
Thanks for the trouble!
