### ISSUE TITLE
Emitted xAPI statement version

### ISSUE THREAD

**Issue by DaTebe** [davidpesce/moodle-logstore_xapi#73]
Hi,

I searched a little bit through your documentation but could not find anything. Which version of xAPI does this plugin emit? 

Regards,
Daniel

**Comment by ryasmi** [comment]
Hi @DaTebe, currently [version 1.0.0 according the statements produced](https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/docs/examples/AssignmentGraded.json#L2). I think that's probably compatible with the latest version of the xAPI, although @garemoko could probably confirm.
