### ISSUE TITLE
"Identify users by id" setting does not work, flawed test

### ISSUE THREAD

**Issue by gavbaa** [davidpesce/moodle-logstore_xapi#733]
**Description**
Enabling the "Identify users by id" setting does not send the username in the xAPI statement.

**Version**
Release 4.6.0, which appears to be current master.

**Steps to reproduce the bug**
1. Go to Site Administration -> Plugins -> Logging -> Logstore xAPI
2. Tick the box named “Identify users by id”.
3. View a course activity.
4. The statements sent to the LRS have an actor of:
    "actor": {
        "name": "Admin User",
        "account": {
            "homePage": "https://lms.com",
            "name": "2"
        }
    }

**Expected behaviour**
The statements sent to the LRS have an actor of:
    "actor": {
        "name": "Admin User",
        "account": {
            "homePage": "https://lms.com",
            "name": "admin"
        }
    }

**Actual behaviour**
    "actor": {
        "name": "Admin User",
        "account": {
            "homePage": "https://lms.com",
            "name": "2"
        }
    }

**Server information**
- Ubuntu 19.04
- Moodle 3.7
- MySQL 5.7.25

**Client information**
- OS: Mac OS Catalina
- Browser: Chrome 83.0.4103.97

**Additional information**
Changing the test on https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/src/transformer/utils/get_user.php#L32 from

    if (array_key_exists('send_username', $config) && $config['send_username'] === true) {

to

    if (array_key_exists('send_username', $config) && $config['send_username'] == true) {

appears to resolve the issue.

**Comment by davidpesce** [comment]
This was resolved in #745 and will be merged into main repository soon.
