### ISSUE TITLE
not able to send statements from moodle to learning locker using logstorexapi plugin

### ISSUE THREAD

**Issue by santosh40781** [davidpesce/moodle-logstore_xapi#744]
**Description**
- 
I want the logs of moodle activities to be reflected/stored in learning locker.The scheduled task shows "emit task to LRS" completed successfully but "events failed to send to LRS" is what i get after running CRON job.

Execute scheduled task: Emit records to LRS (logstore_xapi\task\emit_task)
... started 03:45:15. Current memory use 28.6MB.
1 event(s) have failed to send to the LRS.
0 event(s) have been successfully processed.
... used 6 dbqueries
... used 0.12826490402222 seconds
Scheduled task complete: Emit records to LRS (logstore_xapi\task\emit_task)

**Version**
- 
moodle:3.7  
php 7.2

**Steps to reproduce the bug**
1. installed logstorexapi plugin in moodle.
2. perform activity like create user.
3. run the cron task

**Expected behaviour**
statement should be sent to LRS.

**Actual behaviour**

statements not showing up.

**Comment by davidpesce** [comment]
Hi @santosh40781 - thanks for following the issue template! It sounds like you've got an issue with the LRS URL/credentials. Have you verified that they are correct?
