### ISSUE TITLE
Allow customization of identifying actors

### ISSUE THREAD

**Issue by sei-ebram** [davidpesce/moodle-logstore_xapi#777]
**Description**
- Right now, actors can only be identified by the following:

1. homePage - Always set to app_url
2. name - Either username, or id, depending on a setting.

Both of these are quite limiting.  homePage set to app_url makes sense for local accounts, but not for OAuth2 accounts according to the xAPI spec.  If a user is accessing Moodle via OAuth2, then the homePage should reflect the OAuth2 issuer, and _not_ Moodle.

In addition, in the specific case of OAuth2 users, but most likely others, both "id" and "username" aren't relevant identifiers for an account.  Instead, this should be more freely customizable and include a list of user properties to choose from.

**Comment by sei-ebram** [comment]
![image](https://user-images.githubusercontent.com/61522167/98144522-6e572800-1e98-11eb-819d-e79552432cf6.png)

**Comment by davidpesce** [comment]
Happy to review PRs, but will be closing this as part of a cleanup/roadmap focus.
