### ISSUE TITLE
Fix .gitignore

### ISSUE THREAD

**Issue by ghost** [davidpesce/moodle-logstore_xapi#782]
**Description**
- The `.gitignore` file includes `version.php`, therefore when we commit the xAPI plugin to our internal Moodle repo, it does not include `version.php`, which is of course a required file for Moodle. Whilst we can manually modify the `.gitignore`, the source then deviates from the plugin, potentially resulting in merge conflicts. Regardless, the `version.php` file should not be in `.gitignore` anyway.

**Version**
- `master` at `e5be1b7e55d16e3bba244e91f663cb75169a8a50` on `2018082100`

**Steps to reproduce the bug**
1. Copy the xAPI plugin into an existing Moodle Git repository 
2. Push this to the remote

**Expected behaviour**
- `version.php` should be included, without needing to modify `.gitignore`

**Actual behaviour**
- `version.php` is not pushed, as it is in `.gitignore`.

**Comment by davidpesce** [comment]
This has been resolved. We are now using the plugin-release github actions from Moodle HQ.
