### ISSUE TITLE
New Event is not getting creating

### ISSUE THREAD

**Issue by rswethashankar92** [davidpesce/moodle-logstore_xapi#785]
**Description**
- I am trying to create an event and i followed the document as mentioned in https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/docs/new-events.md

- One Such event was successfully created. Whereas another event which has to get the DB info and log is not happening. 
- DB connection is intact since i had tried printing the details on webpage. 

**Steps to reproduce the bug**
1. created a folder named mod_vidtrack under src\transformer\events\
2. In which .php file is created

3. progress is added in the get_event_function_map() function.

**Expected behaviour**
- Event progress must be created. 

**Actual behaviour**
- Event is not created.

**Comment by stephen-oh** [comment]
Having a quick glance over your code I would remove the following 2 lines
`echo "Progress Info: ";
print_object($progress_info);`

And remove the closing PHP tags from the end of the file too
`?>`
