### ISSUE TITLE
Way to get logs from certain courses only

### ISSUE THREAD

**Issue by OlcayGoeren** [davidpesce/moodle-logstore_xapi#786]
Hello,

Currently my logstore sends all data to the lrs. Is there a way to get only logs from certain courses.

**Comment by stephen-oh** [comment]
This isn't a feature of the plugin at present. 

You can customise which events are sent to the LRS but not based on the course.

**Comment by davidpesce** [comment]
No, the better way to handle this is on the LRS side. Filter the statements based on the courses you're looking to query.
