### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ghendo** [davidpesce/moodle-logstore_xapi#789]
It appears this has not been updated for a year which would be a red flag to review if suitable to use.
What is the status of this project

**Comment by davidpesce** [comment]
Yes, it's still maintained, but new events have not been added in a while. We run this in production on the latest versions of Moodle.

**Comment by andrew-tobey-educaro** [comment]
@davidpesce: thanks your commenting on that. I was wondering whether it runs with current versions of Moodle as the version v4.6.0 (2020032801) available for download is said the work with Moodle 3.8 only. So, would it be safe to use it with Moodle 3.10. too?

**Comment by davidpesce** [comment]
I've used it all the way up to Moodle 3.11 without issues.
