### ISSUE TITLE
Moodle Plugin Type

### ISSUE THREAD

**Issue by billnobes** [davidpesce/moodle-logstore_xapi#79]
Hi,

I am trying to install the Moodle plugin from https://github.com/xAPI-vle/moodle-logstore_xapi. 

When I attempt to install the plugin Moodle asks for a "Plugin Type" and I don't see any reference to that in your documentation.

Can you provide any guidance?

Thanks

**Comment by jlowe64** [comment]
Hi,

If you go here: https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v1.1.0

You can download the .zip file, unzip and install it under /admin/tool/log/store/

Then you can go through moodle's normal install process.

The version of the plugin in this repo is for development purposes, all official releases meant for installation are either in the Moodle plugin directory or in the official release on Github.
