### ISSUE TITLE
required verison

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#8]
The required version for this plugin is 2014111002. By chance, I happened to have 2014111001.06 installed so modified the version.php accordingly. The plugin _seems_ to work fine, so you may want to say you support 2014111001 (2.8.1) or even 2014111000 (2.8.0)?

**Comment by jlowe64** [comment]
Good suggestion. I'll do that.

Just out of curiosity, what LRS are you using?

**Comment by garemoko** [comment]
I haven't got that far yet, but I will be using SCORM Cloud in the first instance. I may well try a few.

**Comment by garemoko** [comment]
("seems to work" is limited right now - I'll keep you updated)

**Comment by jlowe64** [comment]
That's great. I've only used LearningLocker myself, so having others on record as being supported is good.

**Comment by jlowe64** [comment]
Fixed the supported Moodle version: commit https://github.com/jlowe64/moodle-logstore_xapi/commit/0ad7398dfee6b00e307c776fe63490cfb64d6a0f

**Comment by garemoko** [comment]
I have statements in SCORM Cloud!

**Comment by ryasmi** [comment]
Nice! That's good news @garemoko! :+1:
