### ISSUE TITLE
Send short course name is enabled but not emitted to Learninglocker

### ISSUE THREAD

**Issue by ismetbuyar** [davidpesce/moodle-logstore_xapi#801]
**Description**
- Send short course name is enabled but not emitted to Learninglocker when using h5p plugin

**Version**
-  Logstore xAPI v4.6.0, bitnami/moodle:3, bitnami/mariadb:10.2,  learninglocker/xapi-service:2.1.10, learning locker v2.8.2, h5p 1.20.2

**Steps to reproduce the bug**
1. Install h5p and logstore xapi plugin 
2.  Setup connection between learninglocker and Moodle
3.  create h5p question
4. Enable Send short course name
5. Answer h5p question
6. Look into Learning locker for answered statement

**Expected behaviour**
- Answered statement should return short course name 

**Actual behaviour**
- does not return short course name

**Server information**
- {{database}} with {{authentication}}.

**Client information**
- OS: macOS
- Browser: Google chrome

**Additional information**
- {{additionalInfo}})

**Comment by gordonmacqueen-lp** [comment]
@ismetbuyar can you complete the issue template with the requested details?
Also, if you can detail what you have tried it will enable someone to help

**Comment by ismetbuyar** [comment]
Can you look into this @gordonmacqueen-lp ? Thanks.

**Comment by ismetbuyar** [comment]
Or somebody else? Updated learning locker to v.7.10

**Comment by davidpesce** [comment]
Confirmed that this is working properly in the latest release of jisc branch. Will be merged into main soon.
