### ISSUE TITLE
Installation of Logstore xAPI v4.6.0 (2020032801) on Moodle 3.11.3 results in Exception

### ISSUE THREAD

**Issue by AlexeiRubin** [davidpesce/moodle-logstore_xapi#805]
**Description**
- Installation of Logstore xAPI v4.6.0 (2020032801) results in the following error. 
- Exception - syntax error, unexpected token "," "More information about this error"
- Site Administration cannot be accessed because of the same error.

**Version**
-  Logstore xAPI v4.6.0 (2020032801) with Moodle 3.11.3

**Steps to reproduce the bug**
1. Installation of the Plugin - Logstore xAPI v4.6.0 (2020032801) on Moodle 3.11.3.

**Expected behaviour**
- The Logstore xAPI v4.6.0 (2020032801) should work as it's intended and emit records.

**Actual behaviour**
- The following Exception occurs :
- Exception - syntax error, unexpected token ","
   "More information about this error" Link Leads to https://docs.moodle.org/311/en/error/moodle/generalexceptionmessage
- Site Administration cannot be accessed because of the same error.

**Server information**
- The general steps were followed during installation.
- PHP 8.0 is used.
- Lubuntu 20.04 LTS.

**Comment by davidpesce** [comment]
Thank you for reporting this. The only thing that stands out to me is the PHP version. Moodle 3.11 doesn't yet support PHP 8.0. Can you try downgrading to a supported version and see if it works?

**Comment by davidpesce** [comment]
Confirming that this has been resolved in the v4.7.0 release. We currently support 3.9, 3.11, and 4.0
