### ISSUE TITLE
Json is malformed at contextActivities>extensions>other, I think

### ISSUE THREAD

**Issue by deedey** [davidpesce/moodle-logstore_xapi#81]
Hi!
I have a JSON error in a malformed string at **"contextActivities>extensions>other"** derived from "other" field of "mdl_logstore_standard_log"
See this exemple on this field : "a:1:{s:19:"coursesectionnumber";i:-1;}" and note that there is double quotes into this field.
we obtain this malformed JSON:
      "extensions":{
         "http://lrs.learninglocker.net/define/extensions/moodle_logstore_standard_log":{
            "eventname":"coreeventcourse_viewed",
            "component":"core",
            "action":"viewed",
            "target":"course",
            "objecttable":null,
            "objectid":null,
            "crud":"r",
            "edulevel":2,
            "contextid":88,
            "contextlevel":50,
            "contextinstanceid":"7",
            "userid":"2",
            "courseid":"7",
            "relateduserid":null,
            "anonymous":0,
            **"other":"a:1:{s:19:"coursesectionnumber";i:-1;}",**
            "timecreated":1468847486,
            "origin":"web",
            "ip":"194.167.15.238",
            "realuserid":null
         },
with this error:
_**Error: Parse error on line 104:
..."other":"a:1:{s:19:"coursesectionnumber"
-----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'undefined'**_

What do you think about replacing Double Quotes by Single Quotes or deleting them to resolve this error.

**Comment by ryasmi** [comment]
Need some input from @jlowe64 @garemoko

**Comment by jlowe64** [comment]
Which LRS are you using?

This is the standard way that Moodle stores extra data into the event that otherwise wouldn't be easily obtainable. They use double quotes in the database. This is a `serialized` array, so it would need to be `unserialized` in order to be interacted with.

We haven't had issues with Learning Locker so far, so it may be worth noting what's actually throwing the error here.

**Comment by deedey** [comment]
I use my own LRS located on formagri.educagri.fr/lrs.
I know that Moodle uses double quotes in this 'OTHER' field. But in JSON writing, I think that double quotes in final data between final brackets aren't justified.
Errors are shown in and by JSON Editor Online Chrome Extension

In my LRS, I store JSON text like it come.
There is an example:

`{"actor":{"objectType":"Agent","name":"Dey Bendifallah","account":{"name":"2","homePage":"http://qualif.test-moodle.educagri.fr"}},"verb":{"id":"http://id.tincanapi.com/verb/viewed","display":{"en":"viewed"}},"context":{"contextActivities":{"category":[{"objectType":"Activity","id":"http://moodle.org","definition":{"type":"http://id.tincanapi.com/activitytype/source","name":{"en":"Moodle"},"description":{"en":"Moodle is a open source learning platform designed to provide educators, administrators and learners with a single robust, secure and integrated system to create personalised learning environments."}}}],"grouping":[{"objectType":"Activity","id":"http://qualif.test-moodle.educagri.fr","definition":{"type":"http://id.tincanapi.com/activitytype/site","name":{"en":"Qualif Test Moodle"},"description":{"en":"Plateforme Moodle de test"},"extensions":{"http://lrs.learninglocker.net/define/extensions/moodle_course":{"id":"1","category":"0","sortorder":"1","fullname":"Qualif Test Moodle","shortname":"Q.T.Moodle","idnumber":"","summary":"<p>Plateforme Moodle de test</p>","summaryformat":"0","format":"site","showgrades":"1","newsitems":"3","startdate":"0","marker":"0","maxbytes":"0","legacyfiles":"0","showreports":"0","visible":"1","visibleold":"1","groupmode":"0","groupmodeforce":"0","defaultgroupingid":"0","lang":"","calendartype":"","theme":"","timecreated":"1402906277","timemodified":"1467099437","requested":"0","enablecompletion":"0","completionnotify":"0","cacherev":"1468842775","type":"site","url":"http://qualif.test-moodle.educagri.fr"}}}}]},"platform":"Moodle","language":"en","extensions":{"http://lrs.learninglocker.net/define/extensions/moodle_logstore_standard_log":{"eventname":"coreeventcourse_viewed","component":"core","action":"viewed","target":"course","objecttable":null,"objectid":null,"crud":"r","edulevel":2,"contextid":39,"contextlevel":50,"contextinstanceid":"5","userid":"2","courseid":"5","relateduserid":null,"anonymous":0,**_"other":"a:1:{s:19:"coursesectionnumber";i:-1;}",_**"timecreated":1468849510,"origin":"web","ip":"194.167.15.238","realuserid":null},"http://lrs.learninglocker.net/define/extensions/info":{"https://moodle.org/":"3.1.1 (Build: 20160711)","https://github.com/LearningLocker/Moodle-Log-Expander":"1.1.0","https://github.com/LearningLocker/Moodle-xAPI-Translator":"1.1.0","https://github.com/LearningLocker/xAPI-Recipe-Emitter":"1.0.0"}}},"timestamp":"2016-07-18T15:45:10 02:00","object":{"objectType":"Activity","id":"http://qualif.test-moodle.educagri.fr/course/view.php?id=5","definition":{"type":"http://lrs.learninglocker.net/define/type/moodle/course","name":{"en":"Formagri=>Moodle"},"description":{"en":"Ce cours permet de tester les modules exportu00e9s depuis Formagri (Cnpr et Supervision) en mode Export-Xml et Scorm"},"extensions":{"http://lrs.learninglocker.net/define/extensions/moodle_course":{"id":"5","category":"4","sortorder":"650003","fullname":"Formagri=>Moodle","shortname":"Fm01","idnumber":"Fm01","summary":"<p>Ce cours permet de tester les modules exportu00e9s depuis Formagri (Cnpr et Supervision) en mode Export-Xml et Scorm</p>","summaryformat":"1","format":"onetopic","showgrades":"1","newsitems":"5","startdate":"1423522800","marker":"0","maxbytes":"0","legacyfiles":"0","showreports":"1","visible":"1","visibleold":"1","groupmode":"1","groupmodeforce":"1","defaultgroupingid":"0","lang":"","calendartype":"","theme":"","timecreated":"1423473068","timemodified":"1466681097","requested":"0","enablecompletion":"0","completionnotify":"0","cacherev":"1468842775","type":"course","url":"http://qualif.test-moodle.educagri.fr/course/view.php?id=5"}}}}}`

**Comment by jlowe64** [comment]
Okay, it looks like we aren't escaping the serialized array when it gets put into the JSON structure. I'm guessing that my LRS is handling it somehow, as when I try to look at a statement with a serialized array in it, there's only `"other": "N;"` on the other end. 

Thanks for finding that!

**Comment by garemoko** [comment]
Honestly, I think we should remove these extensions of raw data entirely. If the data is useful, we should be processing it and putting it somewhere more accessible.

**Comment by deedey** [comment]
Thank you for your réponse. 
You are right. 
When the "other" field is NULL, it return "N;" and this is a common situation. But sometimes it return à serialized data. 
I find often this case.

**Comment by deedey** [comment]
Hi @Andrew, 
Or we can just put antislashes in data. 
JSON accept this notation. 
But I think like you :
There's too datas collected by this API and a simplification is welcome.

**Comment by deedey** [comment]
Hi @Andrew, 
Or we can just put antislashes in data. 
JSON accept this notation. 
But I think like you :
There's too datas collected by this API and a simplification is welcome.

**Comment by ryasmi** [comment]
Happy for the extensions to be removed if they're not of use. They were added initially because:
1. We weren't sure what data would be used.
2. We need some raw event info to make sure the statements were correct.

**Comment by deedey** [comment]
Here another kind of **"other" field** returned by Moodle logstore where it return a user enrolment log:
      "extensions":{
         "http://lrs.learninglocker.net/define/extensions/moodle_logstore_standard_log":{
            "eventname":"coreeventuser_enrolment_created",
            "component":"core",
            "action":"created",
            "objecttable":"user_enrolments",
            "objectid":1,
            "crud":"c",
            "contextid":427,
            "contextlevel":50,
            "contextinstanceid":"12",
            "userid":"2",
            "courseid":"12",
            "relateduserid":"7",
            **"other":"a:1:{s:5:"enrol";s:6:"manual";}",**
            "timecreated":1467967807,
            "origin":"web",
            "ip":"194.167.15.238",
            "object":"user_enrolment"
         },
I think that the better solution is deleting "**extensions**" from statements to garanted their JSON format

**Comment by ryasmi** [comment]
Shouldn't be closed until fixed.

**Comment by deedey** [comment]
Sorry Ryan, just a mistake from the keyboard of my smartphone.

**Comment by ryasmi** [comment]
No worries @deedey

**Comment by garemoko** [comment]
@deedey please can you raise that as a separate issue?

**Comment by deedey** [comment]
I've opened another issue @garemoko. 
Thank's for this suggestion.

**Comment by ryasmi** [comment]
https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v3.0.0
