### ISSUE TITLE
Error when Moodle is installed with Oracle DB

### ISSUE THREAD

**Issue by jaume77** [davidpesce/moodle-logstore_xapi#848]
**Description**
- When accessing the "Logstore xAPI Error Log" configuration, a DB error is displayed (Debug info: ORA-00932: inconsistent data types: expected - CLOB obtained)

**Version**
$plugin->component = 'logstore_xapi';
$plugin->version = 2022101800;
$plugin->requires = 2020061500;
$plugin->supported = [39, 400];
$plugin->maturity = MATURITY_STABLE;
$plugin->release = '';

**Steps to reproduce the bug**
- Site administration -> Plugins -> Logging -> Logstore xAPI Error Log

**Server information**
- Moodle 3.10, Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production.

![error Ora00932 xapi](https://github.com/xAPI-vle/moodle-logstore_xapi/assets/2485232/42f8f245-922a-42ce-96a7-1ea2fdbe7dad)

**Comment by davidpesce** [comment]
Unfortunately, the plugin does not support Oracle and it looks like Moodle relies on volunteers to maintain it's use: https://docs.moodle.org/403/en/Oracle

If you could submit a PR with the necessary fixes (and it doesn't break any of the existing functionality), I can review and merge it.
