### ISSUE TITLE
Support H5P module xAPI states

### ISSUE THREAD

**Issue by izendegi** [davidpesce/moodle-logstore_xapi#852]
Since Moodle 4.2 the core supports xAPI states and H5P module (mod_h5p) saves the content state using xAPI states: https://tracker.moodle.org/browse/MDL-67789

Would it be possible to add those events to this plugin in order to send them to the LRS?

Thank you!

**Comment by davidpesce** [comment]
Thanks for submitting this request. It is certainly possible, but is not on our roadmap. I'm happy to review and merge PRs though!
