### ISSUE TITLE
integrate with external lrs

### ISSUE THREAD

**Issue by amirayounis** [davidpesce/moodle-logstore_xapi#854]
**Description**
did not integrate with external lrs ,I'm sure about the endpoint and cardinalities because I test it by Postman but logstore xapi plugin doesn't emit any statements to my lrs , for testing purposes I work on the local host and also I installed sqlrs local is that might be the problem

**Comment by davidpesce** [comment]
Yeah, local isn't the best place to test it. You probably don't have CRON set up and no SSL certificates.
