### ISSUE TITLE
Error when doing test made a fix to resolve the issue

### ISSUE THREAD

**Issue by caperneoignis** [davidpesce/moodle-logstore_xapi#88]
Hey,

I noticed two errors, or I should say warnings but they failed the test, when running unitTest to try and figure out what was happening with the user_loggedin/out event trigger (#83) within the xapi plugin. Both errors came from the moodle-xapi-translator/src/Events/FeedbackSubmitted.php starting on line 28 and another fix on line 46. However, it's the test from the main xapi log store plugin that the errors were produced. I'm including the file so you can see the changes I made. Two simple changes to allow the test to pass. All other test have passed. 
[fix.txt](https://github.com/xAPI-vle/moodle-logstore_xapi/files/590486/fix.txt)

Like I said stumbled on to this while testing to see what could be causing the issue with #83. Let me know if you want this in a pull request, and I'll try and make that happen soon.

**Comment by ryasmi** [comment]
Hi Lee, thanks for spotting this, please do submit a PR 👍

**Comment by caperneoignis** [comment]
No problem! I'll submit here in a couple.

**Comment by ryasmi** [comment]
Awesome, thanks Lee.

**Comment by davidpesce** [comment]
This is resolved with v1.2.0
