### ISSUE TITLE
Feature Request: add the option to have exceptions printed

### ISSUE THREAD

**Issue by caperneoignis** [davidpesce/moodle-logstore_xapi#89]
Yea, after debugging the last issue, I noticed the try catch statement does not have any method to print if an exception is caught. I was thinking of adding a simple check box that allows admins to select if they want exceptions printed, like a normal Moodle error throw. Then we would just let Moodle handle the error message as it does with other error messages, either print it to a log or print it on screen. I think this may speed up error finding, especially for us testers who run the plugin in a test environment that reflects a semi-production environment. 

I can add the check box, and then the config lookup. I was thinking of adding it the print here in the controller.php file of LogExpander:

````java
    /**
     * Creates new events.
     * @param [String => Mixed] $events
     * @return [String => Mixed]
     */
    public function createEvents(array $events) {
        $results = [];
        foreach ($events as $index => $opts) {
            $route = isset($opts['eventname']) ? $opts['eventname'] : '';
            if (isset(static::$routes[$route]) && ($opts['userid'] > 0 || $opts['relateduserid'] > 0)) {
                try {
                    $event = '\LogExpander\Events\\'.static::$routes[$route];
                    array_push($results , (new $event($this->repo))->read($opts));
                }
                catch (\Exception $e) {
                    // Error processing event; skip it.
                   //add the if () and print statement here. if exception is caught. 
                }
            }
        }
        return $results;
    }
````

I'm thinking this may only take a couple of lines to actually implement, since it will be using Moodle API for error printing. 

Let me know what you guys think.

**Comment by garemoko** [comment]
Rather than adding a checkbox why not use the moodle error settings? 

https://github.com/garemoko/moodle-mod_tincanlaunch/blob/601bab77a42727ccd1cd178f37404db166fb101f/launch.php#L128

**Comment by caperneoignis** [comment]
I'm completely good with that. Since that is something I normally have set
any way. I'll be happy to add it if no one has an issue with it.

**Comment by caperneoignis** [comment]
Actually, after looking it up, since not everyone has access to their config, but do have access to the debug settings, we could just add this line. 

debugging({string message}, {debug_level}); 

As specified here, on weblib.php at line 2934

````java 
/**
 * Standard Debugging Function
 *
 * Returns true if the current site debugging settings are equal or above specified level.
 * If passed a parameter it will emit a debugging notice similar to trigger_error(). The
 * routing of notices is controlled by $CFG->debugdisplay
 * eg use like this:
 *
 * 1)  debugging('a normal debug notice');
 * 2)  debugging('something really picky', DEBUG_ALL);
 * 3)  debugging('annoying debug message only for developers', DEBUG_DEVELOPER);
 * 4)  if (debugging()) { perform extra debugging operations (do not use print or echo) }
 *
 * In code blocks controlled by debugging() (such as example 4)
 * any output should be routed via debugging() itself, or the lower-level
 * trigger_error() or error_log(). Using echo or print will break XHTML
 * JS and HTTP headers.
 *
 * It is also possible to define NO_DEBUG_DISPLAY which redirects the message to error_log.
 *
 * @param string $message a message to print
 * @param int $level the level at which this debugging statement should show
 * @param array $backtrace use different backtrace
 * @return bool
 */
function debugging($message = '', $level = DEBUG_NORMAL, $backtrace = null) {
````

**Comment by caperneoignis** [comment]
So if you set the debugging on the settings page, you can automatically get the output as specified by the settings section. so we could make the actual call,

````debugging($e, DEBUG_MINIMAL);```` at the line I listed earlier and forgoing the if condition, since the function takes the debugging level into account. It will only print to system log or the window only if the settings has been enabled. or we could also do an if condition, just in case someone also marked the $CFG->debug, we can have a var_dump or something along those lines.

**Comment by garemoko** [comment]
Good job finding that. 

This is actually just doing the same thing as the approach I suggested but in a nicer way. $CFG->debug reads those debug settings (unless you've overwritten it in the config file, but that would also affect the debugging function).

**Comment by ryasmi** [comment]
Added into V3 https://github.com/xAPI-vle/moodle-logstore_xapi/pull/172/commits/0f562bb09135c973593b6bbab5484987da762b9f

Thanks for the extra info @caperneoignis @garemoko, will close this when V3 is merged and released.
