### ISSUE TITLE
Share LRS settings and lang strings with Tin Can Launch plugin? 

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#9]
**Motive**
It would be nice to have a single place to enter LRS settings in Moodle. It would also be nice not to have multiple lang strings for the same thing. Further, @davidpearce has recently done some work on help text for the Tin Can Launch Link plugin which would also be helpful in this plugin. 

**Result**
Would you consider either making the Tin Can Launch Link a requirement for this plugin or having a third "LRS Settings" plugin that all xAPI plugins can reference and depend on for language strings and LRS settings?

**Additional information**
https://github.com/garemoko/moodle-mod_tincanlaunch

**Comment by ryasmi** [comment]
It's possible that you might want different LRSs for different tasks hence more than one place to enter LRS settings. Don't really mind having multiple lang strings, I suppose the lang strings could be combined into a library that both plugins could depend on via Composer.

**Comment by garemoko** [comment]
A shared plugin could also share some functions e.g.

https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/locallib.php#L525
https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/lib.php#L578-608
It could also share a copy of TinCanPHP

@ryansmith94 duplicating lang strings means extra work and translation costs (a translation company will charge for the same translation twice for sure!) It's also more maintenance. 

Composer is a nice solution for the launch plugin doesn't currently use composer and it still means duplicated PHP files on the Moodle server, which might even be included twice in some cases. Agree that it would be good to be able to overwrite LRS settings for individual plugins (and to send to multiple LRSs for that matter). The launch plugin allows you to overwrite LRS settings at activity level but has global defaults.

**Comment by ryasmi** [comment]
This plugin is structured very differently so I don't think a lot of that code could be reused (certainly not the second link).

True, I'm happy to share lang strings if they're maintained in another repo.

You're right it does mean duplicated files, but that isn't so much a plugin issue as it is a platform issue. Definitely not concerned by duplicated files, memory is cheap. However, I do agree it would be nice to share the lang strings since people's time is expensive.

**Comment by davidpesce** [comment]
@ryansmith94 with the latest version of the tincanlaunch plugin, you have both global LRS settings as well as an override option within each activity.
