### ISSUE TITLE
BUG: log expander Attempt event using wrong id when getting question attempt

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#90]
This line in AttemptEvent.php:

`$attempt->questions = $this->repo->readQuestionAttempts($attempt->id);`

Here we are passing the attempt id, however we really need to be passing the questionusageid. See https://github.com/moodle/moodle/blob/MOODLE_32_STABLE/lib/db/install.xml#L1308

So: `$attempt->questions = $this->repo->readQuestionAttempts($attempt->uniqueid);`

I'll submit a pr when I get a chance.

**Comment by ryasmi** [comment]
Thanks @garemoko 👍

**Comment by davidpesce** [comment]
This was resolved in v1.3.0
