### ISSUE TITLE
random quiz question statements fail because question ids do not match

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#91]
The question url seems to be dropping out between the log expander and the emitter. I need to do some more digging.

**Comment by garemoko** [comment]
This seems to be specific to random questions. What happens is that the expander gets the questions associated with the quiz, which are the random question placeholders, and the ids of the questions attempted which are the actual questions displayed. They therefore don't match up when the translator tries to get data about the attempted questions. We need to modify the expander to get the actual questions asked, rather than the placeholders.

**Comment by ryasmi** [comment]
Thanks Andrew, good digging!

**Comment by davidpesce** [comment]
This was resolved in v1.3.0
