### ISSUE TITLE
Feature request: Add SCORM events

### ISSUE THREAD

**Issue by berthelemy** [davidpesce/moodle-logstore_xapi#92]
Hi there,

Now that Moodle logs much more information about SCORM data, are there any plans to include this data in the logstore_xapi plugin?

Specifically:

\mod_scorm\event\status_submitted
\mod_scorm\event\scoreraw_submitted

Thanks,

Mark

**Comment by joshwillcock** [comment]
When I initially added those events to Moodle last year and then spoke with @jlowe64 who definitely made one for both: ScormScorerawSubmitted andScormStatusSubmitted. I can see it is in the scorm-events branch, but not master, any reason for this?

**Comment by ryasmi** [comment]
Hey @berthelemy @joshwillcock, not really sure what the status is of that, hopefully @jlowe64 can comment.

**Comment by jlowe64** [comment]
@berthelemy I just need to sit down and do the work to finish it off and merge!

**Comment by berthelemy** [comment]
@jlowe64 That's excellent. Is there anything a techie non-developer like me can do to help?

**Comment by jlowe64** [comment]
@berthelemy maybe a list of the types of information you're trying to pull from this experience would help. I'm pulling what I expect folks to want, but don't know beyond that. :)

**Comment by berthelemy** [comment]
@jlowe64 OK, it's not too much:

## Status

- Activity:
    * SCO name
    * SCO URL
- Context:
    * Course:
        + Course name
        + Course URL
    * LMS:
        + Moodle site name
        + Moodle site URL
- Result:
   * cmi.core.lesson_status
   * cmi.core.total_time
- Date/time of status achieved

## Score

- Activity:
    * SCO name
    * SCO URL
- Context:
    * Course:
        + Course name
        + Course URL
   * LMS:
        + Moodle site name
        + Moodle site URL
- Result:
    * cmi.core.score.raw
    * cmi.core.score.max
    * cmi.core.score.min
- Date/time of score achieved

**Comment by berthelemy** [comment]
Just thinking about this further...

It would be more useful to have a single statement of the form:

{actor} {attempted} {SCO} with {result (status or score) }

Does that make sense?

**Comment by jlowe64** [comment]
@berthelemy yes, but isn't that something that would be best suited for getting your information out of the LRS? This plugin just simply throws a bunch of information into the LRS, and that's about the extent of it.

**Comment by berthelemy** [comment]
I'm sure that'll be fine. :-)

**Comment by garemoko** [comment]
I'd actually like to see this plugin do more intelligent processing of the information, like we do for the quiz module. If we're just throwing garbage into the LRS, it's much more of a challenge to get anything useful out. 

That said, as @jlowe64 said for himself, it all comes down to having the time to actually sit down and look at it and make it all work well.

**Comment by berthelemy** [comment]
I can probably spend some time over the next couple of days coming up with a sample statement, if that would be useful?

**Comment by berthelemy** [comment]
Hi all,
It turns out that ADL have already done the work to create a SCORM to xAPI profile:

https://adl.gitbooks.io/scorm-profile-xapi/content/xapi-scorm-profile.html

Of particular interest are the [common scenarios](https://adl.gitbooks.io/scorm-profile-xapi/content/xapi-scorm-profile.html#common-scenarios)

It would be great if the Moodle xAPI logstore could follow this pattern.

Mark

**Comment by garemoko** [comment]
@berthelemy good catch. I feel bad that i didn't think of that myself.

**Comment by davidpesce** [comment]
Just released v1.4.0 with support for SCORM events.
