### ISSUE TITLE
QUESTION: LRS Vendor detection

### ISSUE THREAD

**Issue by mpellicer** [davidpesce/moodle-logstore_xapi#93]
I've used this plugin to integrate successfully 4 instances of Moodle, works really fine so far, congratulations!

Currently i'm experiencing a problem with another instance of Moodle, for some reason the plugin is not registering any event and shows an error in the log:

Invalid argument supplied for foreach() in XXXXX/admin/tool/log/store/xapi/vendor/rusticisoftware/tincan/src/RemoteLRS.php 

Seems is detecting the wrong Vendor because should use LearningLocker instead of Rustici.

Any idea in mind? Thanks!

**Comment by ryasmi** [comment]
Hey @mpellicer, glad to hear it's working well on 4 other instances and thanks for reporting your problem. Do you have any more information from the log? The reason you're seeing "Rustici", is that the plugin uses Rustici's TinCanPHP library to send statements to the LRS.

**Comment by ryasmi** [comment]
That's unfortunate. Possibly, I wonder if there is an event that happens in production that does not happen locally. It's possible that such an event might not be handled correctly, hence potentially causing the error on [line 403 in the RemoteLRS](https://github.com/RusticiSoftware/TinCanPHP/blob/master/src/RemoteLRS.php#L403). I think @garemoko has more experience with that library, perhaps this is something you've seen before Andrew?

**Comment by mpellicer** [comment]
Yeah, we're working on it. Our problem is in this line:

https://github.com/RusticiSoftware/TinCanPHP/blob/master/src/RemoteLRS.php#L433

**Comment by mpellicer** [comment]
Seems a firewall is blocking the output queries 👍 so non issue, thank you so much.

**Comment by ryasmi** [comment]
Awesome thanks for letting us know @mpellicer 👍
