### ISSUE TITLE
Table "{$a}" does not exist

### ISSUE THREAD

**Issue by ryasmi** [davidpesce/moodle-logstore_xapi#96]
Just got an email from someone with this problem. Judging from the `Table "{$a}" does not exist` and the stack trace, my guess is that the Moodle installation doesn't have a table (course_modules) that we expected to be there in the ModuleEvent recipe.

### Version
Moodle: 3.1.2 (20160912)
Plugin: 1.0.0 (2016012900)

### Steps to reproduce the problem
Unsure

### Expected Behaviour
Cron sends statements.

### Actual Behaviour
Cron doesn't send any statements and emits the error below. However both the standard and xAPI tables exist and they have data.

```
Execute scheduled task: Emit records to LRS (logstore_xapi\task\emit_task)
... started 09:07:23. Current memory use 3.3MB.
... used 7 dbqueries
... used 0.014888048171997 seconds
Scheduled task failed: Emit records to LRS (logstore_xapi\task\emit_task),Table "{$a}" does not exist
Backtrace:
* line 1477 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
* line 25 of /admin/tool/log/store/xapi/vendor/learninglocker/moodle-log-expander/src/Repository.php: call to moodle_database->get_record()
* line 47 of /admin/tool/log/store/xapi/vendor/learninglocker/moodle-log-expander/src/Repository.php: call to LogExpander\Repository->readStoreRecord()
* line 59 of /admin/tool/log/store/xapi/vendor/learninglocker/moodle-log-expander/src/Repository.php: call to LogExpander\Repository->readObject()
* line 12 of /admin/tool/log/store/xapi/vendor/learninglocker/moodle-log-expander/src/Events/ModuleEvent.php: call to LogExpander\Repository->readModule()
* line 78 of /admin/tool/log/store/xapi/vendor/learninglocker/moodle-log-expander/src/Controller.php: call to LogExpander\Events\ModuleEvent->read()
* line 104 of /admin/tool/log/store/xapi/classes/log/store.php: call to LogExpander\Controller->createEvents()
* line 53 of /admin/tool/log/store/xapi/classes/task/emit_task.php: call to logstore_xapi\log\store->process_events()
* line 75 of /lib/cronlib.php: call to logstore_xapi\task\emit_task->execute()
* line 81 of /admin/cron.php: call to cron_run()
```

### Additional Information
Cron for emitting records was last successful February 25th 2017 at 4:30 AM. No changes to the plugin files or any Moodle files that *might* effect the plugin at that time (nor any time near that).

**Comment by garemoko** [comment]
It would be pretty weird is the course_modules table didn't exist. Without looking at the stack trace, could it be that the table for the specific module  didn't exist i.e. if the module was uninstalled after the event was generated but before it was processed?

**Comment by ryasmi** [comment]
Yeah I agree that would be pretty weird. Yeah I think that is one possibility.

**Comment by andrewhickey** [comment]
Moodle version 3.1.2 (Build 20160912)
Logstore xAPI Plugin version 2016012900

**Comment by ryasmi** [comment]
They reinstalled the plugin and all works now.

> Communication between Logstore xAPI and Learning Locker has been restored after we reinstalled the plugin. Not sure what the source of the problem was, but we’re good-to-go now.

**Comment by garemoko** [comment]
Assuming the cause was uninstalling a module, I'm guessing reinstalling the logstore plugin worked because it cleared out all the old log events (i.e. they lost data).

**Comment by ryasmi** [comment]
Yeah I think so @garemoko, although I can neither confirm or deny that hypothesis haha
